### ISSUE TITLE
new rule to disallow multiple await keywords next to each other 

### ISSUE THREAD

**Issue by capaj** [standard/standard#1000]
This is actually a valid JS-the editor won't show squigly lines or anything like that.
```javascript
const result = await await query(
```

Would be nice if standard could catch this typo as it can easily occur when refactoring.

**Comment by feross** [comment]
I don't have any immediate plans to work on this issue, so I'm going to close it. If you (or anyone else) wants to tackle it, the right place to send a PR is to the `eslint` project: https://github.com/eslint/eslint

Once they accept the rule, we'll be happy to include it here.
