### ISSUE TITLE
Wont disable check on one line

### ISSUE THREAD

**Issue by hovancik** [standard/standard#1001]
Hi, how can I disable one line? Adding stuff from readme is not working for me. 
 
`test.js`: 
```
/*eslint-disable*/
return // eslint-disable-line
/*eslint-enable*/
```

` ./node_modules/.bin/standard test.js`: 

```
standard: Use JavaScript Standard Style (https://standardjs.com)
test.js:2:1: Parsing error: 'return' outside of function
```

**Comment by bcomnes** [comment]
Thats a syntax parsing error so disabling styles rules won't have any effect there.

**Comment by hovancik** [comment]
Ah, ok. Is there way to ignore it then?

**Comment by Flet** [comment]
The error is happening when eslint attempts to parse the code itself. Unfortunately there is no way to disable this type of error. If I get an error like this, usually it means I have a `return` statement in the wrong place.

I'm closing this issue as don't think we can fix it, but feel free to reply with questions.

**Comment by hovancik** [comment]
I added `"babel-eslint": "^8.0.1",` and I am not getting it anymore.
