### ISSUE TITLE
false result for: return new Promise(async (resolve) => { 

### ISSUE THREAD

**Issue by liesislukas** [standard/standard#1006]
Doesn't work with this sample:

```
module.exports = function userLogin({email, password}) {
  return new Promise(async (resolve) => {
    ...
  });
};

```

It says 

`Expected parentheses around arrow function argument     arrow-parens`
for line with `return new Promise...`

**Comment by ematipico** [comment]
I've never seen the statement `async` before an arrow function, especially inside a `Promise`. Do you have the same issue if you transform the arrow function in a normal function?

**Comment by liesislukas** [comment]
No, without arrow function it works fine e.g.:

```
  return new Promise(async function foo(resolve) {
```

But I often use arrows and async together.

**Comment by feross** [comment]
Just tested and this is not an issue anymore. I believe it was fixed in `standard` version 11.
