### ISSUE TITLE
Should automatically lint *.mjs files

### ISSUE THREAD

**Issue by feross** [standard/standard#1009]
ES6 module support is coming to Node.js. That means a new file extension (*.mjs) that denotes an ES6 module file. `standard` should automatically lint this file extension, since that's what users will expect.

**Comment by yoshuawuyts** [comment]
Sounds reasonable.

Side note tho: from talking to TSC members, this may change in the future.
My understanding is that the
`.mjs` extension was brought in place so the module spec could be
implemented and tested, but now
that that's happened, they'll be digging into ergonomics, which means
figuring out compat with just a `.js`
extension. It's unsure what will come from it, but yeah it might be prone
to change. Kinda just sharing
what I've overheard in recent weeks (:

**Comment by ematipico** [comment]
Yeah they've made a big of a mess

**Comment by feross** [comment]
@yoshuawuyts Cool, thanks for sharing. I've just started playing around with `--experimental-modules`. We'll keep an eye on this!

**Comment by feross** [comment]
Only one repo started failing from this change (`merge2`) and it was because they had lint errors in their `.mjs` files and weren't manually running standard on them. So, this is a great change!

This will ship in `standard` 14.

**Comment by feross** [comment]
I just remembered that `.cjs` files are also coming to Node, so I'll add those by default too.
