### ISSUE TITLE
Add Eaze to the list of users

### ISSUE THREAD

**Issue by feross** [standard/standard#1010]
Someone I know who works there confirmed they use `standard`.

**Comment by Flet** [comment]
Related :)
https://github.com/standard/standard/issues/744#issuecomment-303205510

**Comment by LinusU** [comment]
Would like to add my company, Ctrl Alt Deseat, as well 🙋‍♂️ 

Can personally confirm that we are using standard 😄

**Comment by LinusU** [comment]
I can submit a PR for both, it also seems like the current formatting is broken?

<img width="587" alt="screen shot 2017-11-02 at 10 03 13" src="https://user-images.githubusercontent.com/189580/32320256-0f348f6a-bfb5-11e7-9a5d-127092985a94.png">

I'll try to fix that as well...
