### ISSUE TITLE
Adding custom rules to standard

### ISSUE THREAD

**Issue by sebasgarcep** [standard/standard#1016]
Is there a way to add custom rules to standard through the `package.json` config without using `standardx`. I'm using the standard extension on visual studio code and I want something that works out of the box even if I change computers.

**Comment by Flet** [comment]
Part of the philosophy of `standard` is:
>No configuration. The easiest way to enforce consistent style in your project. Just drop it in.
>No decisions to make. No .eslintrc, .jshintrc, or .jscsrc files to manage. It just works.

That being said, there are a few ways to do what you're trying to do.

One way to do it while maintaining really great support in IDEs/editors is to switch to using `eslint` directly with the `eslint-config-standard` configuration.

Here is how to do it:

1. Install necessary packages:
Run this command to save the required packages to `devDependencies`:
```bash
npm install --save-dev eslint@3 eslint-config-standard eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node
``` 

2. Add config to `package.json`
Add this key to `package.json` to enable the `eslint-config-standard` config:
```js
"eslintConfig": {
  "extends": "standard"
}
```

3. Use `eslint` for your linting needs.
Just run `eslint` and `eslint --fix` for your linting needs. There is fantastic support for `eslint` in IDEs including vscode :)

4. Tweak stuff
Prefer double quotes everywhere? Override the rule by adding it to the config in `package.json`
```js
"eslintConfig": {
  "extends": "standard",
  "rules": {
    "quotes": ["error", "double"]
  }
}
```

Its also possible to put config elsewhere (like `.eslintrc`). Check out the eslint docs for all the details: https://eslint.org/docs/user-guide/configuring

I hope this info helps! I'm closing this issue now, but feel free to comment!

P.S. adding `standardx` support to the vscode plugin for standard is a good idea! I opened an issue on that repo to see what they think! :) https://github.com/chenxsan/vscode-standardjs/issues/49

**Comment by sebasgarcep** [comment]
Thanks @Flet for your answer!

I want to point out that I'm ok with how `standard` works right now for vanilla JS and the rules I want to add are React-specific. I find it confusing that `standard` already covers JSX but not React, specially when these two are almost always used together. It would be nice to include some react rules, or at least allow a way to activate these rules.
