### ISSUE TITLE
Error in "The Rules" on front page

### ISSUE THREAD

**Issue by Thom1729** [standard/standard#1019]
> - **Never start a line with (, [, or `**
>     - This is the **only* gotcha with omitting semicolons – *automatically checked for you!*

Emphasis original. If you omit semicolons, you also must not start a line with `/` (unless you're beginning a comment).

The error is repeated under the Semicolons heading.

**Comment by Flet** [comment]
Huh, Yeah this gives an unexpected token error:

```js
/foo/.test('foo bar')
/bar/.test('foo bar')
```

**Comment by Thom1729** [comment]
Oh, and also ``` ` ```. You can't safely start a line with a backtick.

**Comment by feross** [comment]
We only included likely characters in the list of things to watch for. You'll notice in @Flet's example that the return values from the `.test` method are being discarded, which defeats the whole point of calling `.test`.

However, I've heard others point this out before, so I included the full list in this commit: https://github.com/standard/standard/commit/ccbbd92ee880f9c6e3605c78d8c2ed4e181b6668#diff-fc204564835eac10577935faecd0dc71R1304
