### ISSUE TITLE
New version bump

### ISSUE THREAD

**Issue by ematipico** [standard/standard#1021]
Should we consider a plan to release a new major version of Standard? `v11.0.0` should support new major version of `eslint` and maybe we could inject additional rules

**Comment by Flet** [comment]
Yes!

We've published `standard@11.0.0-beta.0` under the `beta` tag now.

This only includes upgrading `eslint` though. It should fix a lot of weird errors and give better linting/fixing right away with the new version. 

I think v12 will be the next opportunity for adding new rules. There is not really a protocol for adding new rules (and there are so many opinions :)). I don't know how to organize this in a sane way though. Better to get whats needed out right away before painting the bike shed. :)

**Comment by feross** [comment]
🗣 Standard 11 is released! Run `npm install standard@latest --save-dev` to update to the latest version. This will also update the version in `package.json` ✨

Changelog: https://github.com/standard/standard/blob/master/CHANGELOG.md#1100---2018-02-18
