### ISSUE TITLE
Double quotes permitted outside when nested singlequotes

### ISSUE THREAD

**Issue by bodurkalukasz** [standard/standard#1022]
Below scripts are both valid currently:

` countryCodeInput: "input[name='country-code']"`

` countryCodeInput: 'input[name="country-code"]'`

Shouldn't one of those be preferred?

**Comment by feross** [comment]
In general, single quotes are preferred. However, sometimes you have a string with lots of single quotes in it (that can't be replaced with double quotes like in your example) and it's desirable to be able to use a double quote string to avoid many escape sequences.

I'm curious how much breakage there would be in the ecosystem if we tightened this rule up, but I'm not so sure this is actually a good idea.
