### ISSUE TITLE
Don't iterate over files and folders that should be ignored

### ISSUE THREAD

**Issue by watson** [standard/standard#1023]
In a project of mine, I have a build directory that quickly gets really large. It's ignored via `.gitignore`, so standard doesn't fail on it, but it still runs through all files in the directory. It results in a running time of 13 seconds as opposed to 1 second without the build directory.

I know this have been discussed before (#680) and it seems to be a "feature" inherited from eslint. But I'm opening this issue to hopefully start a discussion on how to work around this or how to potentially fix it (either in standard or in eslint).

**Comment by Flet** [comment]
Maybe this fixes it in eslint 4?
https://github.com/eslint/eslint/pull/8706

**Comment by watson** [comment]
Hmm not sure. I'm not sure why caching should fix it, but I know almost nothing about eslint internals, so I could very well be wrong.

**Comment by ematipico** [comment]
AFAIK `standard` doesn't support `eslint` 4. I am right?

**Comment by watson** [comment]
@ematipico Correct. I think what @Flet was hinting at was if the solution to this might come automatically when at some point standard is upgraded to 4.x

**Comment by Flet** [comment]
@watson could you try with `standard@beta`? It uses the latest version of eslint. At least we could determine if its fixed? :)

**Comment by watson** [comment]
@Flet doesn't seem to fix it unfortunately:

![image](https://user-images.githubusercontent.com/10602/34054920-43097848-e1cd-11e7-8f0a-b5216e29f5d5.png)

**Comment by watson** [comment]
hmmm hang on... might have spoke too soon. Let me just check something

**Comment by watson** [comment]
Nah, I wanted to try to also ignore the folder inside package.json, but no dice. Here you can also see the time it takes if I delete the folder:

![image](https://user-images.githubusercontent.com/10602/34055168-4644fe64-e1ce-11e7-843a-3ad65516523f.png)

**Comment by Flet** [comment]
Aww, was worth a shot :(

**Comment by GantMan** [comment]
I'm having this same issue.  Fix is traversing ignored paths and complaining with a exit code 1

**Comment by searls** [comment]
Can confirm, I have the same issue with a very-very-very large (almost cyclic) `examples/node_modules` directory in testdouble.js (still existing at [this commit](https://github.com/testdouble/testdouble.js/tree/97ce780d04c8ba38ffce6ec66188367555ac3b85)). All major versions of Node.js literally run out of heapspace attempting to scan it.

**Comment by feross** [comment]
The issue seems related to `deglob`. Posting more info from @searls:

<img width="378" alt="screen shot 2018-02-27 at 3 41 09 pm" src="https://user-images.githubusercontent.com/121766/36761630-d42686a4-1bd4-11e8-9b96-c9df32eaceaa.png">
<img width="386" alt="screen shot 2018-02-27 at 3 41 14 pm" src="https://user-images.githubusercontent.com/121766/36761632-d59dd8de-1bd4-11e8-9b34-de3b030a4093.png">

**Comment by searls** [comment]
LOL amazing issue report

**Comment by Flet** [comment]
Nice thank you for digging @serls :)

**Comment by watson** [comment]
I took at stab at this and found that this is a combination of a few issues.

As @searls pointed out, the issue is inside deglob.

1. Diving further, the time is spend inside the glob module: https://github.com/standard/deglob/blob/bce559a275faf286395c52912a82c601a6740f2d/index.js#L23-L27
1. The `ignore` option passed to the glob module does not contain patterns found in the `.gitignore` file, so files only ignored here will still be processed by glob
1. Even if the lines from the `.gitignore` file were passed to the `ignore` option, these would have to end with `/**` to ignore whole directories. This is inconsistent with how `.gitignore` works and with what's [documented](https://github.com/standard/standard#how-do-i-ignore-files) in the README

Suggested solution:

1. Document that you need to append `/**` to directories you wish to ignore in the package.json `standard.ignore` array 
1. [Convert](https://www.npmjs.com/package/gitignore-to-glob) the patterns from `.gitignore` to patterns compatible with the glob module and add them to the list of ignored glob patterns

@feross what do you think of this?

**Comment by searls** [comment]
My preferred solution would be to update deglob to behave like the [glob](https://www.npmjs.com/package/glob) module or `.gitignore` when it comes to `foo/**/*` style patterns. 

I realize it could be seen a breaking change, but one person's breaking change is another's patch fix! Based on the popularity of using `**/*` to mean "all files, recursively" I can't imagine anyone is intentionally passing `deglob` ignore rules of that type with an expectation they will not be ignored recursively.

Is that on the table?

**Comment by feross** [comment]
I'm removing `deglob` for `standard` 16. So this issue will be fixed for free!

**Comment by searls** [comment]
Woohoo! Thanks @feross!

**Comment by feross** [comment]
This will be fixed in `standard` 16
