### ISSUE TITLE
Standard reports unfixable errors for Flow code

### ISSUE THREAD

**Issue by strager** [standard/standard#1045]
I followed these instructions to set up Standard with Flow support: https://standardjs.com/#can-i-use-a-javascript-language-variant-like-flow-or-typescript

Unfortunately, Standard reports problems I don't know how to fix. For example, in the following code, I have a Flow-annotated class property called `_greeting`:

```javascript
// @flow

class Greeter {
  _greeting: string

  constructor () {
    this._greeting = 'hello world'
  }

  greet (): void {
    console.log(this._greeting)
  }
}

new Greeter().greet()
```

For this code, Standard reports the following problem:

```
  /Users/mg/Projects/standard-js-flow-issue/index.js:4:3: '_greeting' is not defined.
```

If I remove line 4 which declares `_greeting`, Standard no longer reports the problem, but now Flow complains:

```
Error: index.js:5
  5:     this._greeting = 'hello world'
              ^^^^^^^^^ property `_greeting`. Property not found in
  5:     this._greeting = 'hello world'
         ^^^^ Greeter

Error: index.js:9
  9:     console.log(this._greeting)
                          ^^^^^^^^^ property `_greeting`. Property not found in
  9:     console.log(this._greeting)
                     ^^^^ Greeter


Found 2 errors
```

How can I make both Standard and Flow happy for this code?

The following script lets you reproduce the problem from scratch: https://gist.github.com/strager/02f2dbebb3a4f5aafeb0b0fa4041936f/b77094b402bb8ed5cb55e304205a206543696b78#file-set_up-sh (That Gist also includes my yarn.lock file so you can see what version of the packages I installed.)

**Comment by on3iro** [comment]
This is an issue with babel-eslint. Try to downgrade babel-eslint to 8.0.3 then it should work :)

**Comment by strager** [comment]
@on3iro, thanks! I confirm that running the following command makes `yarn run standard --parser babel-eslint --plugin flowtype` report no issues:

```bash session
$ yarn add --dev babel-eslint@8.0.3
```

Even with this workaround, I'm still having problems with my real project. I'll investigate some more and close this issue if my other problems are unrelated.

**Comment by strager** [comment]
I think I figured out what's wrong with my project.

Installing `lab` (a project which I think is unrelated to Standard) re-breaks Standard:

```shellsession
$ yarn add --dev lab
...
$ yarn run standard --parser babel-eslint --plugin flowtype
yarn run v1.3.2
$ /Users/mg/Projects/standard-js-flow-issue/node_modules/.bin/standard --parser babel-eslint --plugin flowtype
standard: Use JavaScript Standard Style (https://standardjs.com)
  /Users/mg/Projects/standard-js-flow-issue/index.js:4:3: '_greeting' is not defined.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

`lab` has a dependency on `eslint@4.9.x`, and it looks like Standard starts using that version of the `eslint` package instead of its own version (`eslint@~3.19.0`).

I'm not very familiar with Node's module system. Is Standard using eslint incorrectly? Is this a bug in Yarn? Is something broken in lab?

I tried to work around this issue by explicitly installing `eslint@3.19.0` in my project, but that seemed to have no effect.

```shell session
$ yarn add --dev eslint@3.19.0
...
$ yarn run standard --parser babel-eslint --plugin flowtype
yarn run v1.3.2
$ /Users/mg/Projects/standard-js-flow-issue/node_modules/.bin/standard --parser babel-eslint --plugin flowtype
standard: Use JavaScript Standard Style (https://standardjs.com)
  /Users/mg/Projects/standard-js-flow-issue/index.js:4:3: '_greeting' is not defined.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Script to reproduce: https://gist.github.com/strager/02f2dbebb3a4f5aafeb0b0fa4041936f/74231871320c68db7dd08be67fb8c0aff80270ef#file-set_up-sh

Side note: Standard's cache is broken. I had to run `rm ~/.standard-cache/.cache_*` in many cases while figuring out what's wrong.

**Comment by strager** [comment]
I had the same issue with npm, so I don't think this issue is Yarn's fault:

```shellsession
$ rm -rf node_modules
$ npm install
...
$ ./node_modules/.bin/standard --parser babel-eslint --plugin flowtype
standard: Use JavaScript Standard Style (https://standardjs.com)
  /Users/mg/Projects/standard-js-flow-issue/index.js:4:3: '_greeting' is not defined.
```

**Comment by strager** [comment]
With lab installed, installing `babel-eslint@7.2.1` makes Standard much more tolerable:

```
$ yarn add --dev babel-eslint@7.2.1
```

I have no idea why this works or why `babel-eslint@8.0.3` worked without lab.

**Comment by feross** [comment]
`standard` v12 (released a few months ago) now uses ESLint 4 internally so perhaps this issue is fixed now?

**Comment by lithium2013** [comment]
@feross Maybe you mean `v11` instead of `v12`?
