### ISSUE TITLE
jest-standard-runner - a link, maybe? ;)

### ISSUE THREAD

**Issue by lgandecki** [standard/standard#1046]
Hey guys

I've created a jest-runner-standard yesterday. I think it works beautifully and enables a really nice dev experience. I hope you like as well - I'm open to feedback. 
https://github.com/TheBrainFamily/jest-runner-standard

**Comment by LinusU** [comment]
Looks awesome!

Maybe we should add a "related packages" part to the readme?

**Comment by feross** [comment]
We have a [page on the website](https://standardjs.com/awesome.html) where we feature ecosystem projects. I think that's the place for this!

Send a PR to add the link here: https://github.com/standard/awesome-standard
