### ISSUE TITLE
def.split is not a function

### ISSUE THREAD

**Issue by emnloc** [standard/standard#1047]
Unexpectedly standard stop to work

```
standard: Unexpected linter output:

TypeError: def.split is not a function
    at Config.globals.reduce (/Users/eoc/workspace/web/node_modules/standard/node_modules/eslint/lib/config.js:215:31)
    at Array.reduce (native)
    at new Config (/Users/eoc/workspace/web/node_modules/standard/node_modules/eslint/lib/config.js:214:48)
    at CLIEngine.executeOnFiles (/Users/eoc/workspace/web/node_modules/standard/node_modules/eslint/lib/cli-engine.js:590:28)
    at /Users/eoc/workspace/web/node_modules/standard-engine/index.js:109:61
    at /Users/eoc/workspace/web/node_modules/deglob/index.js:51:12
    at end (/Users/eoc/workspace/web/node_modules/run-parallel/index.js:16:15)
    at done (/Users/eoc/workspace/web/node_modules/run-parallel/index.js:20:10)
    at each (/Users/eoc/workspace/web/node_modules/run-parallel/index.js:26:7)
    at /Users/eoc/workspace/web/node_modules/run-parallel/index.js:41:37

If you think this is a bug in `standard`, open an issue: https://github.com/standard/standard/issues
```

Any idea?

**Comment by lordspecter13** [comment]
No e blokeado nada ya no tengo acceso a esta cuenta tampoco te dije que
estoy siendo atacado y no puedes detener a ese grupo revisa la página es
mía pero fue tomada por hackers no conosco a ninguno de ese grupo pero y
usan este medio para enviarme modificaciones vía server y TCPIP 5037 ahí
están ellos por favor invalida cada cambio echo y deja libre mis cuentas

**Comment by lordspecter13** [comment]
Mira esa persona no soy yo y hizo el cambio
https://github.com/standard/standard/issues/1050

**Comment by LinusU** [comment]
(removed some spam)

**Comment by catdaddy23** [comment]
Thanks for the removal

**Comment by bcomnes** [comment]
@emnloc can you provide a file that triggers the problem?

**Comment by TeffenEllis** [comment]
@bcomnes @emnloc,

This seems to be an error with the change to the package.json global declaration:

```json
{
  "standard": {
    "globals": {
      "foo": true,
      "bar": true
    }
  }
}
```

This can be fixed with an array instead:

```json
{
  "standard": {
    "globals": [
      "foo",
      "bar"
    ]
  }
}
```

Given how many existing setups there are, can we keep support for the old format?

Cheers 🍻

**Comment by emnloc** [comment]
@bcomnes  @TeffenEllis I changed my package.json and it works now but I agree about the idea of keep support for the old format

**Comment by feross** [comment]
I don't think we explicitly changed this ourselves (unless I'm forgetting). This probably happened in an update to ESLint. It seems like a sufficiently niche issue that I'm not going to worry about it.
