### ISSUE TITLE
How to `--fix` through stdin without getting errors?

### ISSUE THREAD

**Issue by gerardabello** [standard/standard#1048]
I want to format a string of code that might contain non-fixable errors. If I want the formatted output through stdin I get both the code and the non-fixable errors, so it is difficult to extract the formatted code from there.

Is there any way to ignore non-fixable errors when using `--fix` through stdin?

Thanks

**Comment by bcomnes** [comment]
Editor plugins do this by dealing with errors when try spawn a process to try and perform the fix.

**Comment by feross** [comment]
@gerardabello The "fixed" code goes to `stdout`, while the error messages go to `stderr`, so you can filter out just what you need.

Concrete example: 

```bash
echo 'var x = 4;' | standard --stdin --fix > out.txt
```

Now "out.txt" contains the fixed file. The unfixable errors still get printed to `stderr` and appear in the terminal.
