### ISSUE TITLE
static proptypes and decorators

### ISSUE THREAD

**Issue by Rachomir** [standard/standard#1049]
Hey I am having problems with standardJS linting warnings regarding static proptypes and decorators
<img width="643" alt="screen shot 2018-01-24 at 21 55 02" src="https://user-images.githubusercontent.com/13520099/35358194-15f46b30-0156-11e8-827a-3e32d7eb5d9b.png">
<img width="797" alt="screen shot 2018-01-24 at 22 07 14" src="https://user-images.githubusercontent.com/13520099/35358203-1cc70224-0156-11e8-8583-99b2cff05983.png">

I red loads loads of topics about it but I couldnt find the right solution for me. Any idea how to fix it?

**Comment by Rachomir** [comment]
Before someone call me lazy - I did add parser to package.json / webpack.config
<img width="577" alt="screen shot 2018-01-24 at 22 33 31" src="https://user-images.githubusercontent.com/13520099/35358358-b425b8c2-0156-11e8-9cef-ee88bd7a5e39.png">
<img width="470" alt="screen shot 2018-01-24 at 22 17 38" src="https://user-images.githubusercontent.com/13520099/35358367-ba150b2a-0156-11e8-90c1-878ad2321a75.png">

**Comment by frangeris** [comment]
@Rachomir use `// eslint-disable-line` for now until they resolve it...

**Comment by frangeris** [comment]
This is happening with any decorator:

Error 1: `action` is defined but never used. (no-unused-vars)
Error 2: `refreshing` is not defined. (no-undef)

![image](https://user-images.githubusercontent.com/811381/35405895-2d9b6a78-01e6-11e8-97db-d2998bfa2ada.png)

**Comment by Rachomir** [comment]
I hope they will solve this issue soon. Thanks a lot for your participation @frangeris

**Comment by silky098** [comment]
Has there been any updates to this issue, it's really annoying

**Comment by feross** [comment]
Update to `standard` v11 to resolve this issue. Cheers! ✨
