### ISSUE TITLE
Misaligned indentation for wrapped object parameter

### ISSUE THREAD

**Issue by pgraham** [standard/standard#1050]
I'm seeing a function call that requires multiple parameters, one of which is an object literal, with unexpected indentation for the object literal:

``` js
const { argv } = require('yargs')
  .command(
    ['status', '$0'],
    'The status command, very useful.',
  {
    builder: {},
    handler: argv => {
      console.log('Status:')
    }
  }
  )
  .help().argv
```

I'm expecting the braces of the object literal to be aligned with previous string arguments. Is this expected? If so, what's the reason for using a different indentation level for the object literal parameter?

**Comment by feross** [comment]
@pgraham Thanks for opening this issue. Sorry that you never got a timely response.

I just double-checked and it looks like this issue was fixed in `standard` v12. Running `standard --fix` on the code you pasted formats the code as you expected:

```js
const { argv } = require('yargs')
  .command(
    ['status', '$0'],
    'The status command, very useful.',
    {
      builder: {},
      handler: argv => {
        console.log('Status:')
      }
    }
  )
  .help().argv
```
