### ISSUE TITLE
Use with sublime text 3

### ISSUE THREAD

**Issue by mesqueeb** [standard/standard#1053]
One of the great paragraphs in the Readme is called:

**Is there an automatic formatter?**

I was wondering: Is there any way to automatically format files open in Sublime Text 3?

**Comment by WalterBoles** [comment]
I don’t know I’m just happy to find booth of my accounts

**Comment by TriMoon** [comment]
> I was wondering: Is there any way to automatically format files open in Sublime Text 3?

Yes there is, use [eslint](https://github.com/eslint/eslint)

**Comment by feross** [comment]
There's currently a separate plugin for formatting. Search for `StandardFormat` on Package Control.
