### ISSUE TITLE
indentation issue in template literals after upgrading to 11.0.0-beta.0

### ISSUE THREAD

**Issue by egorovli** [standard/standard#1056]
Hi.

After upgrading to `11.0.0-beta.0` started to experience weird indentation errors in CSS-in-JS (template literals) syntax. See screenshots attached.

<img width="547" alt="screen shot 2018-02-02 at 11 35 56" src="https://user-images.githubusercontent.com/5165202/35724034-7047414e-080d-11e8-92e7-9bf21a18157b.png">
<img width="540" alt="screen shot 2018-02-02 at 11 37 52" src="https://user-images.githubusercontent.com/5165202/35724105-a604e336-080d-11e8-98fa-5e5d3ce05f09.png">
<img width="563" alt="screen shot 2018-02-02 at 11 38 22" src="https://user-images.githubusercontent.com/5165202/35724112-a9b6cbb6-080d-11e8-9dcd-09db39242d00.png">

If I set indentation how it wants me to, it gets really weird:

<img width="528" alt="screen shot 2018-02-02 at 11 41 00" src="https://user-images.githubusercontent.com/5165202/35724258-2174caae-080e-11e8-9dd1-263ac035cfab.png">

Have to say that I had to upgrade to `11.0.0-beta.0` because of [this issue with babel-eslint](https://github.com/babel/babel-eslint/issues/564):

<img width="542" alt="screen shot 2018-02-02 at 11 45 01" src="https://user-images.githubusercontent.com/5165202/35724374-8bc66aac-080e-11e8-887e-b5061fef51b3.png">

**Comment by finnp** [comment]
Standard 11 seems to have problems with tagged template strings and indentation. Not sure what changed with eslint. I'll stay with 10 for now.

**Comment by ArmorDarks** [comment]
Same issue here.

Here it requires 2 spaces for two lines (note that it's for two lines, not for 3):

![sublime_text_2018-03-24_22-35-47](https://user-images.githubusercontent.com/4460311/37868725-d923a1e4-2fb3-11e8-9353-b45499a28f76.png)

And here even weirder 4 spaces instead of 12:

![sublime_text_2018-03-24_22-38-05](https://user-images.githubusercontent.com/4460311/37868736-0cc406ce-2fb4-11e8-9923-7ac8312396f3.png)

**Comment by lidel** [comment]
I see similar indentation problems with string interpolation and standard v11.0.1 run against [this codebase](https://github.com/ipfs/ipfs-companion).

`standard --fix` produces this mess:

```diff
index 3ebd809..a593fe2 100644
--- a/add-on/src/popup/page-action/header.js
+++ b/add-on/src/popup/page-action/header.js
@@ -10,12 +10,12 @@ module.exports = function header ({ isIpfsContext, pageActionTitle }) {
     <div class="fade-in ph2 br2 br--top bg-light-gray bb b--black-20">
       <h2 class="ma0 pt1 pb2 pl2 tl">
         ${logo({
-          size: 20,
-          path: '../../../icons',
-          ipfsNodeType: 'external',
-          isIpfsOnline: true,
-          heartbeat: false
-        })} <span class="pl1 f6 fw4 v-mid">${pageActionTitle || '…'}</span>
+    size: 20,
+    path: '../../../icons',
+    ipfsNodeType: 'external',
+    isIpfsOnline: true,
+    heartbeat: false
+  })} <span class="pl1 f6 fw4 v-mid">${pageActionTitle || '…'}</span>
       </h2>
     </div>
   `
```

Note how line with  `${logo({`  is left untouched.

**Comment by feross** [comment]
Wow, this is not good. Will look into fixing this for standard 12

**Comment by Janpot** [comment]
This is kind of blocking me to move past v11. I'm not quite sure how this can be fixed. But maybe this issue should stay open?

**Comment by ArmorDarks** [comment]
Yeap, definitely stale...

**Comment by ArmorDarks** [comment]
I wonder why was it closed? It is a critical bug. Or has it been fixed?

**Comment by LinusU** [comment]
I interpreted your comment to mean that it was fixed, I'd be happy to reopen if it's still a problem in Standard 12...

**Comment by ArmorDarks** [comment]
As far as I know, it wasn't fixed

**Comment by feross** [comment]
Sorry for the delay on this issue! This appears to be fixed.

**Comment by feross** [comment]
Actually, I just tested with another code sample from this issue (https://github.com/standard/standard/issues/1056) and it seems it's still an issue. Let's move discussion to that issue.
