### ISSUE TITLE
pre-commit error

### ISSUE THREAD

**Issue by zhangyuang** [standard/standard#1060]
![image](https://user-images.githubusercontent.com/17424434/35900213-b3acfddc-0c0b-11e8-86fe-b9074ab14eb8.png)
![image](https://user-images.githubusercontent.com/17424434/35900261-eb0443a8-0c0b-11e8-8103-0ea466a025a2.png)

**Comment by feross** [comment]
Thanks for helping out, @jandockx!

One other workaround might be to install GNU grep using [homebrew](https://brew.sh/) (a package manager for macOS).

```bash
brew install grep
```

This installs GNU grep as a binary called `ggrep` (note the extra leading `g` character). So, just change the references to `grep` to `ggrep` and you should be good :)
