### ISSUE TITLE
npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.1.0

### ISSUE THREAD

**Issue by kevzdev** [standard/standard#1078]
# EDIT: WORKAROUND IS TO INSTALL VERSION 10.0.3 `npm install standard@10.0.3 -g`

Problem occured when: `npm install standard -g`
Output:
```
C:\Users\Kevzdev\AppData\Roaming\npm\standard -> C:\Users\Kevzdev\AppData\Roaming\npm\node_modules\standard\bin\cmd.js
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

+ standard@11.0.0
added 224 packages in 4.381s

C:\Users\Kevzdev\Desktop\jsfolder>
```

`node -v` = `v9.5.0`
`npm -v` = `5.6.0`
Windows 10 Pro x64 v1709

It breaks NPM! When running `npm list -g --depth=0` output:
```
C:\Users\Kevzdev\AppData\Roaming\npm
`-- standard@11.0.0

npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.1.0
```

**Comment by kevzdev** [comment]
I've checked, `npm install standard -g`, `npm install standard@latest -g` and `npm install standard@11.0.0 -g ` all have this issue. Seems to be an issue with `standard@11.0.0`

**workaround is to install version 10.0.3: `npm install standard@10.0.3 -g`**

**Comment by kevzdev** [comment]
Issue persists on both Windows 10 Pro x64 (version 1709) and macOS High Sierra (version 10.13.3) with node versions `8.9.4` (LTS) and `9.5.0` (current) and npm version `5.6.0` (current).

**Comment by kevzdev** [comment]
It's probarely an issue in a dependency: https://www.diffchecker.com/mMdOuh7l (compared 10.0.3 to 11.0.0)

**Comment by kevzdev** [comment]
I've narrowed down the issue to the dependency `"eslint": "~4.18.0"`.
This is a working version `"eslint": "~3.19.0"` however `"eslint-config-standard": "11.0.0"` and `"eslint-config-standard-jsx": "5.0.0"` depends on `"eslint": "~4.18.0"` so we need to downgrade them aswell to `"eslint-config-standard": "10.2.1"` and `"eslint-config-standard-jsx": "4.0.2"` since they depend on `"eslint": "~3.19.0"`.

**Comment by kevzdev** [comment]
Replicating the issue @ematipico 

Remove any standard packages installed
`npm uninstall standard -g`

This will give an error
`npm install standard -g`

Remove any standard packages installed
`npm uninstall standard -g`

This is fine
`npm install standard@10.0.3 -g`

**Comment by bcomnes** [comment]
I wonder if this is a windows specific bug, can't reproduce on macOS.

**Comment by bcomnes** [comment]
Wait, this issue is just about the warning?

**Comment by bcomnes** [comment]
Never mind seeing that as well.

**Comment by kevzdev** [comment]
@bcomnes both on Windows (10) and macOS (High Sierra).
It's a warning, but it will break standard and other NPM features.

**Comment by bcomnes** [comment]
https://github.com/eslint/eslint/pull/10022#issuecomment-368575323

You can ignore the warning, its an upstream issue with eslint that they are tracking.

**Comment by bcomnes** [comment]
Ah, perhaps shrink-wrap?  It sounds like it's an issue with the table package.

**Comment by feross** [comment]
As @bcomnes says, this is an npm issue https://github.com/npm/npm/issues/19877 that will be worked around when eslint merges https://github.com/eslint/eslint/pull/10022/files and releases a new version.

In the meantime, if this is causing issues for you, I recommend pinning `standard` to version 10.0.3.

**Comment by devondahon** [comment]
After running this on osx:
```
npm uninstall standard -g
npm install standard@10.0.3 -g
npm list
```

I still get the error:
```
npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.1.0
npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.1.0
npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.1.0
```

**Comment by newtonsheikh** [comment]
I am getting the same error 

npm install
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

Repo: https://github.com/newtonsheikh/vscode-vsts-extension-react
