### ISSUE TITLE
Idea: add some explanation about adding the pre-commit hook in a project

### ISSUE THREAD

**Issue by PestoP** [standard/standard#1084]
I think it could be cool to tell developers how to use the pre-commit hook.

I don't know if it's the right way but I used [Husky](https://github.com/typicode/husky) :

```bash
"scripts": {
    "precommit": "./hooks/standard.sh"
  },
```

And I put the code in the standard.sh file.

What do you think about that ?

**Comment by feross** [comment]
You could also just do:

```
"scripts": {
    "precommit": "standard"
}
```

which is even simpler.

If you want to update the docs to mention `husky`, that'd be much appreciated :)
