### ISSUE TITLE
using with eslint-plugin-security

### ISSUE THREAD

**Issue by lakamsani** [standard/standard#1085]
Hi, is it possible to use standard.js and  https://github.com/nodesecurity/eslint-plugin-security at the same time or do we have to switch back to eslint to check our code with Node Security Platform (nsp at https://nodesecurity.io/opensource).

**Comment by LinusU** [comment]
That plugin seems amazing! I think we should investigate adding it by default 🚀 

In the meantime, I would recommend you to use [standardx](https://github.com/standard/standardx) which will allow you to add rules. Something like:

```diff
{
   "scripts": {
-    "test": "standard && mocha"
+    "test": "standardx && mocha"
   },
   "dependencies": {
     "standard": "^11.0.0"
+    "standardx": "^2.0.0"
+    "eslint-plugin-security": "^1.4.0"
   },
+  "eslintConfig": {
+    "plugins": [
+      "security"
+    ],
+    "extends": [
+      "plugin:security/recommended"
+    ]
+  }
}
```

**Comment by lakamsani** [comment]
We tried that suggestion and it works great. Thank you.

**Comment by lakamsani** [comment]
FYI, if anyone is trying this with WebStorm, it won't work from the editor thought it will from command line/npm script. Added an issue for Jetbrains (seller of WebStorm). https://youtrack.jetbrains.com/issue/WEB-31624

**Comment by LinusU** [comment]
Opened an issue for adding the plugin to standard: #1086
