### ISSUE TITLE
symlink for English documentation does not work

### ISSUE THREAD

**Issue by peerhenry** [standard/standard#1095]
Go to "https://github.com/standard/standard/blob/master/docs/RULES-en.md"

Expected: the English documentation.
Actual: it only reads "../README.md".

**Comment by feross** [comment]
Sorry that this was confusing. We put the English documentation in `README.md` and `RULES.md` in the root of the repo. The symlinks `docs/README-en.md` and `docs/RULES-en.md` are only used when generating the website.

Unfortunately, GitHub doesn't follow the symlink and render the linked content 👎
