### ISSUE TITLE
tabs should be allowed in template literal strings

### ISSUE THREAD

**Issue by DarrenCook** [standard/standard#1096]
```
`   0	0048	H
   1	0065	e`
```

I'm getting "Unexpected tab character." complaints on the above string. I think specifying exact whitespace is one of the points of using template literals, so it should not be complaining?

Yeah, I've put:

    /* eslint-disable no-tabs */

at the top of the file and moved on. But that seems like overkill - a template literal string is the only place I can think that I would want tab characters.

**Comment by Yamboy1** [comment]
Why are you using tabs specifically? Why not indent it using spaces?

**Comment by DarrenCook** [comment]
Because I need tabs not spaces ;-)

In this case it was a unit test validating tab-separated output from a function. But, more generally, a lint checker should not be checking anything at all inside a template _literal_ string (except the code inside the `${}` sections, of course).

**Comment by LinusU** [comment]
> In this case it was a unit test validating tab-separated output from a function. But, more generally, a lint checker should not be checking anything at all inside a template literal string

I personally think that this is debatable.

I see your point and use case, and it's definitely valid. But I also think that it might be hard to spot that when glancing over the file, and personally would prefer explicitly writing `\t` in this case. It's similar to trailing whitespace, should that be allowed in template strings? I've actually broken a test in a project by simply saving a file with Atom, as it trimmed trailing spaces. It would probably have been better to be explicit in those cases and do `${' '}` at the end of that line...

Just my 2¢

**Comment by Yamboy1** [comment]
That was my thought as well

**Comment by feross** [comment]
@DarrenCook Does @LinusU's solution of using an explicit `\t` work for you? It sounds reasonable to me. But do share if there's something we're missing.
