### ISSUE TITLE
'xx' is not defined for arrow functions in react 

### ISSUE THREAD

**Issue by btmdave** [standard/standard#1097]
I'm receiving errors that a function is not defined within a react component, on the line of the function, i.e.,

```
submit = () => {}
```
gives me 'submit' is not defined.  I know I can `// eslint-disable-line` but is there anyway to have standard recognize this? I'm using with babel-eslint.

**Comment by LinusU** [comment]
Are you intentionally trying to set a global variable? In that case, you can add `/* global submit */` to the top of the file. Otherwise, you probably want `const`, `let` or `var` before that line, e.g:

```js
const submit = () => {}
```

**Comment by btmdave** [comment]
That was a method of a class, this is in a react component, such as:

```
class Example extends React.Component {
  submit = () => {}
}
```

**Comment by feross** [comment]
This issue is fixed by updating to `standard` v11. Cheers! ✨
