### ISSUE TITLE
Indent is confused and disabling the rule doesn't appear to work either

### ISSUE THREAD

**Issue by kaihendry** [standard/standard#1102]
https://s.natalian.org/2018-03-29/standardjs-indent.mp4

Using 11.0.1

Here is the code that triggers it https://github.com/unee-t/frontend/blob/master/imports/ui/dialogs/invite-dialog.jsx#L187

**Comment by feross** [comment]
Hey there! Sorry for the delay in responding to you. Looks like this issue is resolved on the latest version of `standard`. Hope you got it figured out: )
