### ISSUE TITLE
Disable all rules on a specific line does not work

### ISSUE THREAD

**Issue by danhandrea** [standard/standard#1105]
`import type { MyType } from './my-file'  // eslint-disable-line`

Still shows 

> Parsing error: Unexpected token {

Nevermind, it's not the only issue. I'll just stop using standard.

**Comment by feross** [comment]
It looks like you're using Flow or TypeScript. You need to use a plugin to help ESLint to parse these (since they're not JavaScript).

Take a look at the readme section which explains how to do it: https://standardjs.com/#can-i-use-a-javascript-language-variant-like-flow-or-typescript
