### ISSUE TITLE
Relax rule: JSX: Consider the global scope when checking for defined Components (react/jsx-no-undef)

### ISSUE THREAD

**Issue by DusanDimitric** [standard/standard#1115]
Hi, I'm using `standard` with `react-native` and `babel-plugin-jsx-control-statements`.

## Problem
`standard` shows errors for `babel-plugin-jsx-control-statements` globals such as `If`, `Choose` etc. even though they're declared in `package.json standard.globals` ***and*** the `babel-plugin-jsx-control-statements` is specified in `.babelrc` (as seen below)

```
file: package.json
...
  "standard": {
    "parser": "babel-eslint",
    "globals": [
      "describe",
      "test",
      "it",
      "jest",
      "beforeAll",
      "beforeEach",
      "afterAll",
      "afterEach",
      "expect",
      "fetch",
      "navigator",
      "__DEV__",
      "XMLHttpRequest",
      "FormData",
      "React$Element",
      "If",
      "Choose",
      "When",
      "Otherwise",
      "For",
      "With"
    ]
  }
...
```

```
file: .babelrc
...
  "plugins": [
    "jsx-control-statements"
  ],
...
```

## Example output
```
$ standard --verbose | snazzy
...
  36:14  error  'Choose' is not defined     react/jsx-no-undef
  37:16  error  'When' is not defined       react/jsx-no-undef
  40:16  error  'Otherwise' is not defined  react/jsx-no-undef
  45:12  error  'Choose' is not defined     react/jsx-no-undef
  46:14  error  'When' is not defined       react/jsx-no-undef
  49:14  error  'Otherwise' is not defined  react/jsx-no-undef
  53:12  error  'Choose' is not defined     react/jsx-no-undef
  54:14  error  'When' is not defined       react/jsx-no-undef
  57:14  error  'Otherwise' is not defined  react/jsx-no-undef
...
```

## Expected behavior

`standard` should not throw `react/jsx-no-undef` errors for variables declared in package.json > standard.globals:

```
      "If",
      "Choose",
      "When",
      "Otherwise",
      "For",
      "With"
```

I've seen this line in the CHANGELOG.md:

```
Fix jsx-no-undef will not check the global scope by default.
```

But I guess it doesn't relate to this case.

Let me know if I can provide any more details.
Thanks a lot,
D.D.

**Comment by DusanDimitric** [comment]
This ***Important*** note seems related:

https://github.com/vkbansal/eslint-plugin-jsx-control-statements#important

**Comment by DusanDimitric** [comment]
Doing some investigation I found this:

https://github.com/standard/standard/commit/749eec91e07c79044228ae9eb4d9a91c2fd6d085#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR39

Can this `react/jsx-no-undef` rule be changed so it reads the globals in any way ?

**Comment by feross** [comment]
@DusanDimitric Yep, we can include this in the next release.

**Comment by DusanDimitric** [comment]
Thanks ;)

**Comment by feross** [comment]
I'm going to leave this issue open so that I remember to include this in the next release.

**Comment by bovas85** [comment]
I can see it's still giving an error here, can we please check this?

**Comment by ForkInSpace** [comment]
I second this ^

**Comment by soratobukuroneko** [comment]
in package.json I have
```javascript
"eslintConfig": {
    "plugins": [
      "jsx-control-statements"
    ],
    "extends": [
      "plugin:jsx-control-statements/recommended",
      "react-app"
    ],
    "rules": {
      "react/jsx-no-undef": [2, { "allowGlobals": true }]
    }
  }
```

and

```javascript
"babel": {
    "presets": [
      "@babel/preset-env",
      "react-app"
    ],
    "plugins": [
      "jsx-control-statements"
    ]
  }
```

but I'm still getting `'If' is not defined  react/jsx-no-undef`... what am I missing?

**Comment by soratobukuroneko** [comment]
Any update? :(

**Comment by tenjojeremy** [comment]
Hi @feross , any updates on this feature?

**Comment by feross** [comment]
Sorry for the delay – this will be fixed in `standard` 16!
