### ISSUE TITLE
improve glob support

### ISSUE THREAD

**Issue by zaynv** [standard/standard#1117]
Let's say I have a folder structure like this:

```
└── src
    ├── 1.js
    └── 2.js
```

If I run `eslint src` with the `eslint-config-standard` setup, it works as expected:

```
/Users/zaynv/Desktop/test/src/1.js
  1:5   error  'x' is assigned a value but never used  no-unused-vars
  1:11  error  Extra semicolon                         semi

/Users/zaynv/Desktop/test/src/2.js
  1:5   error  'y' is assigned a value but never used  no-unused-vars
  1:11  error  Extra semicolon                         semi
```

But if I run `standard src`, I get no output. To get it to work, I would need to do `standard src/*.js` instead. Is it possible to add support for this in `standard` as well? 

I think this is where `eslint` is doing this:

https://github.com/eslint/eslint/blob/b32d1f48cecc1eecd1352a978d7b393ad047337c/lib/util/glob-util.js#L25-L73

**Comment by feross** [comment]
I suppose we should consider this since it's probably surprising to most users.

@Flet do you have thoughts about the viability of adding this to `deglob`?

**Comment by Flet** [comment]
Yeah this makes sense to me!

**Comment by matthewadams** [comment]
Supporting globs including recursive ones like `standard 'src/**/*.js'` would also be great.  For now, I have to execute commands like `find src -name '*.js' | xargs standard --verbose`, which is both more verbose and also not platform-agnostic.

**Comment by feross** [comment]
This will be fixed in `standard` 16
