### ISSUE TITLE
Git pre-commit hook work with all files but without ignored

### ISSUE THREAD

**Issue by Leesson** [standard/standard#1118]
Git pre-commit hook demo just work with JSX files for now.   
how do i modify it to work with all files but ignore the files or folders that appear in standard.ignore?
(in other words, how git pre-commit hook work with standardjs' configuration in package.json)

**Comment by LinusU** [comment]
The regex should be `.jsx?` (the `?` makes the `x` optional, thus matching both `js` and `jsx`), are you sure it's not working?

**Comment by Leesson** [comment]
Sorry, I did not fully understand it. It did not work well just because I repalced `js` with `es`.

**Comment by feross** [comment]
Is this issue resolved? Closing it since it's not clear to me, but feel free to continue discussion.
