### ISSUE TITLE
Semicolon before IIFE should be mandatory

### ISSUE THREAD

**Issue by mattisback** [standard/standard#1123]
The following code produces a rather cryptic javascript error when run
```js
console.log("hello world")
(function () {
  // Extra logic goes here. (see below)
})()
```
Here's the console output you get when you run it: (try running it in your browser now (ctrl-shift-j))
```
VM46685:1 hello world
VM46685:2 Uncaught TypeError: console.log(...) is not a function
    at <anonymous>:2:1
(anonymous) @ VM46685:2
```
Eslint does not give any warnings or errors.  The standard mode forces us to omit semicolons, so I propose that a rule to help avoid this case should be added to the standard.  Those with more experience than me can probably better suggest an implementation.

A starting point could be:
```
any line starting with a ( character should require a ; before it
```

**Comment by CiQL** [comment]
There already exists a rule for this:

> Never start a line with `(`, `[`, or `` ` ``. This is the only gotcha with omitting semicolons, and standard protects you from this potential issue.
> eslint: [`no-unexpected-multiline`](http://eslint.org/docs/rules/no-unexpected-multiline)

I don't know why it doesn't give you any warnings or errors, though.

**Comment by lukehutton** [comment]
I don't get any errors when have code like this in separate js file, shouldn't there be error for no-unexpected-multiline ?

```
// ✗ avoid
(function () {
  window.alert('ok')
}())
```

**Comment by feross** [comment]
@mattisback What version of `standard` are you using?

Using `standard@11.0.1` I get an error with your example:

```
/Users/feross/code/standard/t.js:2:1: Unexpected newline between function and ( of function call.
```

I think you're likely using an old version of `standard`.

**Comment by feross** [comment]
@lukehutton You're referring to a separate issue. See https://github.com/standard/standard/issues/786
