### ISSUE TITLE
Unexpected newline between object and [ of property access

### ISSUE THREAD

**Issue by HoffmannP** [standard/standard#1135]
**What version of standard?**
8.6.0

**What operating system, Node.js, and npm version?**

    $ uname -a
    Linux ber 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    $ node --version
    v7.10.1
    $ npm --version
    4.2.0

**What did you do?**
lint the following code

    export class c {
      f (a) {
        let [b, c] = a
        [this.d, this.e] = b
        return [c]
      }
    }

  
**What did you expect to happen?**
No error

**What actually happened?**

    standard: Use JavaScript Standard Style (http://standardjs.com)
    /tmp/test.js:4:5: Unexpected newline between object and [ of property access.
    /tmp/test.js:4:12: Unexpected use of comma operator

**Comment by feross** [comment]
You need to use a leading semicolon before the array destructuring:

```js
export class c {
  f (a) {
    let [b, c] = a
    ;[this.d, this.e] = b
    return [c]
  }
}
```

We should show a warning about this case. This looks like an ESLint bug to me. 

(Leaving this issue open as a reminder to report this to the ESLint team.)

**Comment by TheRauven** [comment]
It's been 6 months, and still nothing has been done to improve the error readability of Destructuring Assignments. I was confused by ESLint not recognizing it, until I finally found this thread

**Comment by feross** [comment]
@TheRauven Glad you figured out your issue.

**Comment by feross** [comment]
Upon reconsideration, I actually think this error message is actually fine. ESLint sees the code as a property access and since we're omitting semis we know we need to add a leading semi. If anyone disagrees, feel free to file an upstream ESLint issue to attempt to make this clearer.
