### ISSUE TITLE
Issues working with Standard + Flow/ Flowtype (question/ asking for help!)

### ISSUE THREAD

**Issue by frednomoon** [standard/standard#1139]
**What version of standard?**
standard@10.0.3
eslint@4.19.1
eslint-plugin-flowtype@2.46.3

**What operating system, Node.js, and npm version?**

npm 5.6.9
node 10.1.0
macos 10.12.6

**What did you expect to happen?**

I'm trying to use flow to enforce some interface types in my code, but struggling to get standard to recognise valid flow syntax.

Currently I have written:

```

interface Response {
  email: string;
  nickname: string;
  id: number;
}

var val: Response = {
  email: "1",
  nickname: "123",
  id: 1,
}
```

Which should return no errors

**What actually happened?**

Standard is underlining `Response` just after the keyword `interface` with the message:
`[standard] Response is not defined. (no-undef)`.

In my package.json I have added the following as instructed by the docs
```
  "standard": {
    "parser": "babel-eslint",
    "plugins": [
      "flowtype"
    ]
  },
```

I expect I am lacking some config somewhere, but have had no luck getting to the bottom of this! Any help / suggestions much appreciated

**Comment by feross** [comment]
According to this comment https://github.com/standard/standard/issues/984#issuecomment-346831391, the best workaround is to pin `babel-eslint` to `7.2.1`.

As far as I'm aware, this is a bug in `babel-eslint`.
