### ISSUE TITLE
<React.Fragment></React.Fragment>  JSX shorthand <></> [standard] Strings must use singlequote. (quotes)

### ISSUE THREAD

**Issue by chinacoolboyzz** [standard/standard#1146]
**What did you expect to happen?**
react v16 <React.Fragment></React.Fragment>  JSX shorthand <></>
[standard] Strings must use singlequote. (quotes)

**Comment by statico** [comment]
Related: https://github.com/eslint/eslint/issues/9662

**Comment by johnnykramer** [comment]
swears to <></>:
[standard] Strings must use singlequote. (quotes)

**Comment by feross** [comment]
This is fixed in `standard` 12.
