### ISSUE TITLE
Standard not working in tests

### ISSUE THREAD

**Issue by amaurymartiny** [standard/standard#1147]
**What version of standard?**

11.0.1

**What operating system, Node.js, and npm version?**

macOs High Sierra
node v10.1.0
npm v6.1.0

**What did you expect to happen?**

Following https://github.com/standard/standard/issues/122#issuecomment-217151207, I would expect that , by putting `"env": [ "mocha" ]` to the `package.json`, I could use standard to lint my test files.

**What actually happened?**

```bash
$ yarn lint
yarn run v1.7.0
$ standard src/main.test.js
standard: Use JavaScript Standard Style (https://standardjs.com)
  /Users/amaurymartiny/Workspace/standard-in-tests/src/main.test.js:2:3: 'expect' is not defined.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here is a small demo repo: https://github.com/amaurymartiny/standard-in-test.

**Comment by LinusU** [comment]
As far as I know, `expect` is not part of mocha. Setting `env: mocha` adds `describe` and `it`, which seems to work for you.

**Comment by Flet** [comment]
Yep!

`eslint` uses the `globals` package to get the mocha globals and I don't see `expect` listed there :)
https://github.com/sindresorhus/globals/blob/master/globals.json#L1024

If you're using some assertion library that has `expect` as a global, you can tell `standard` to [ignore it using one of these ways](https://standardjs.com/#i-use-a-library-that-pollutes-the-global-namespace-how-do-i-prevent-variable-is-not-defined-errors):


1. put this at the top of the JS file that references `expect`: `/* global expect */`

2. add this to package.json:
```
 "standard": {
    "globals": [ "myVar1", "myVar2" ]
  }
```

Hope this helps! I'm closing this issue, but feel free to reply if you have other questions!
