### ISSUE TITLE
EPERM error with .symlink

### ISSUE THREAD

**Issue by mulligan121** [standard/standard#1149]
- Standard:  11.0.1
- OS: Windows 10
- Node: 10.4 & 8.11.2
- NPM: 6.1.0 &  5.6.0

When running standard I get this error due to .symlink's I believe.
![Error Image](http://mulligan.tech/wp-content/uploads/2018/06/error.png)

- This is a test app. 
- Here is a [link](https://github.com/mulligan121/test-issue) to the repo
I did a little more investigation and this is what's happening oddly enough. When I have it in the initial folder and name it `test`, use `npm run prod` to generate the .symlink files, and then `npm run standard` it will fail. BUT if I cd out of the folder then `ren test test2` to rename the folder, CD back into it, then run `npm run standard` it runs fine. I'm assuming that renaming the folder breaks the links which is why it is working for some reason, but I'm looking to fix the issue itself.

This is the folder that keeps failing
![Error Image](http://mulligan.tech/wp-content/uploads/2018/06/Capture4.png)

I also added:
```
"standard": {
    "ignore": [
       "/public"
     ]
}
```
to my package.json plus it's already in my .gitignore

Any help would be appreciated I'm not sure if this is an issue with Standard on Windows or what.
Thanks!

**Comment by mulligan121** [comment]
This issue isn't stale. Standard still throws errors on Windows due to symlinks

**Comment by kethinov** [comment]
For context on why this was closed, we observed that the bug doesn't happen when the symlink is created using the [junction option](https://nodejs.org/api/fs.html#fs_fs_symlink_target_path_type_callback). As such, it probably was never a bug with Standard.
