### ISSUE TITLE
Support optional chaining operator

### ISSUE THREAD

**Issue by alberto-esposito** [standard/standard#1151]
Is there any plan to add support for[ Optional Chaining Operator](https://github.com/tc39/proposal-optional-chaining)?

Also [nullish coaleshing operator ](https://github.com/tc39/proposal-nullish-coalescing)would be nice :)

I'm using standard@11, on node 10 and Ubuntu 17.10

**Comment by LinusU** [comment]
We are supporting whatever upstream eslint is supporting. If you need those features I would recommend using the `babel-eslint` as the parser:

https://github.com/standard/standard#how-do-i-use-experimental-javascript-es-next-features
