### ISSUE TITLE
New rule: No unnecessary regex global flags

### ISSUE THREAD

**Issue by tom-sherman** [standard/standard#1152]
I recently came across an ugly pattern in Regex regarding the `g` flag. See here for details: https://stackoverflow.com/questions/2630418/javascript-regex-returning-true-then-false-then-true-etc

Would have been nice for the linter to warn that I'm using a global flag when I was using `^` and `$` characters at the beginning and end of the regex.

Thoughts?

**Comment by LinusU** [comment]
This sounds very nice! @tom-sherman, is there an existing ESLint rule for this?

**Comment by tom-sherman** [comment]
@LinusU It doesn't look to be. Should I create an issue in ESlint to discuss adding it?

**Comment by LinusU** [comment]
Yes please ☺️
