### ISSUE TITLE
MutationObserver is not defined

### ISSUE THREAD

**Issue by wheelhot** [standard/standard#1159]
Hmm, considering this is part of JavaScript, any particular reason why StandardJS throws this error?

<img width="696" alt="screen shot 2018-07-05 at 21 53 55" src="https://user-images.githubusercontent.com/12379413/42336909-b114a838-80b7-11e8-8d90-34ee6fead669.png">

And what can I do to fix it? Thanks!

**Comment by LinusU** [comment]
It will probably get added to ESLint sooner or later, but in the mean time you can add:

```js
/* global MutationObserver */
```

to the top of your file.
