### ISSUE TITLE
Parsing error: Cannot read property 'ecmaFeatures' of undefined (null)	

### ISSUE THREAD

**Issue by camux** [standard/standard#1163]
**What version of standard?**
11.01

**What operating system, Node.js, and npm version?**
Ubuntu,  Node v9.0.0, npm 6.1.0

**What did you expect to happen?**
This linter warning should not appear

**What actually happened?**
In Atom editor appear this message in all js files
Provider: js-standard  Parsing error: Cannot read property 'ecmaFeatures' of undefined (null)	

My package.json
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-eslint": "^8.2.5",
    "babel-jest": "20.0.3",
    "babel-polyfill": "^6.26.0",
    "eslint": "^5.0.1",
    "eslint-plugin-react": "^7.10.0",
    "jest": "20.0.4",
    "react-test-renderer": "^16.3.2",
    "standard": "^11.0.1"
}

This problem occurs after update several devs packages

**Comment by Autre31415** [comment]
I found a way to replicate this issue:

It has to do with package-lock.json. I've seen many repos that have both eslint 5+ and standard without issue, but if you delete the package-lock.json and rebuild it from scratch (via `npm i`) that app will now experience this bug.

**Comment by camux** [comment]
thanks @Autre31415 at this moment I downgrade to eslint package to version 4.19.1 and problem was solved!

**Comment by bonesoul** [comment]
any fixes for this?

**Comment by likeshumidity** [comment]
See response by @tmilar [xojs issue #336](https://github.com/xojs/xo/issues/336):
```
npm install --save-dev --save-exact eslint-plugin-node@7.0.1
```
this fixes for me.

NOTE: I am not running xojs, just happened upon that as a fix.

**Comment by lannonbr** [comment]
With the update of Standard v12, this bug seems to be resolved.

**Comment by Kikobeats** [comment]
For me this appeared after v12 version :(

**Comment by lannonbr** [comment]
If you have a package that installs both ESLint 4.x and 5.x, this will occur to a bug with acorn

**Comment by lannonbr** [comment]
@wmhilton Prettier-standard has a dependency of eslint@4.x so yes

**Comment by wmhilton** [comment]
Hmm... I think I'm seeing this bug even after I've removed everything depending on eslint@4.x from my project.

**Comment by Autre31415** [comment]
> Hmm... I think I'm seeing this bug even after I've removed everything depending on [eslint@4.x](mailto:eslint@4.x) from my project.

Double check those dev dependencies to make sure, then wipe out `package-lock.json` and `node_modules` and do a fresh `npm install`.

**Comment by ceefour** [comment]
I am having this issue on NodeJS 8.11.1 Win64 and my only libs are:

```
  "dependencies": {
    "@feathersjs/express": "^1.2.7",
    "@feathersjs/feathers": "^3.2.3"
  },
  "devDependencies": {
    "nodemon": "^1.18.4",
    "standard": "^12.0.1"
  }
```

Is it nodemon ?

**Comment by ceefour** [comment]
Thanks to @favadi's https://github.com/standard/standard/issues/1189#issuecomment-418323326. Workaround works for me is:

```
npm i --save-dev standard@11
```
