### ISSUE TITLE
Parsing errors when using named groups in regexes

### ISSUE THREAD

**Issue by Janpot** [standard/standard#1174]
**What version of standard?**

11.0.1

**What operating system, Node.js, and npm version?**

macOS: 10.13.6
node: v10.7.0
npm: 6.10.0

**What did you expect to happen?**

It would be able to lint code that contains regexes with named groups ([stage 4 proposal](https://github.com/tc39/proposal-regexp-named-groups))

**What actually happened?**

It fails with a parsing error when you use a regex like that.
```
Parsing error: Invalid regular expression: /(?<name>[a-z]+)/: Invalid group
```

**Comment by LinusU** [comment]
To use experimental syntax you have to use babel-eslint, please see this part of the documentation:

https://github.com/standard/standard#how-do-i-use-experimental-javascript-es-next-features
