### ISSUE TITLE
Idea: Include files using `standard.include` in `package.json`

### ISSUE THREAD

**Issue by danielbankhead** [standard/standard#1177]
**What version of standard?**
11.0.1

**What operating system, Node.js, and npm version?**
OS: macOS 10.11.6
Node: 8.11.3
npm: 6.2.0

**What did you expect to happen?**
A way to include files that were excluded from `.gitignore`.

**What actually happened?**
No way to include files from `.gitignore`

**Details**
Say you're working on a project that compiles to JavaScript (e.g. TypeScript) and you'd like those distributable files to be formatted in `standard`, but not committed in your `git` repo itself. Adding this feature would give a user the flexibility to include files ignored from `.gitiginore` and `standard.ignore`.

I'm interested in creating a PR in [`standard-engine `](https://github.com/standard/standard-engine) for this feature if you think its a good idea.

**Comment by LinusU** [comment]
I will be able to review ☺️ 

It would be nice to get some signals on what the other maintainers think of the idea, e.g. @feross, @Flet  😀
