### ISSUE TITLE
monorepo support

### ISSUE THREAD

**Issue by Janpot** [standard/standard#1182]
I'd like to reopen https://github.com/standard/standard/issues/746
We're more than a year and a half later and monorepo structure becomes more and more prevalent. The issue can be easily worked around by ignoring `**/node_modules/**`. But I think it should be the standard behavior.

**Comment by LinusU** [comment]
Ignoring `**/node_modules/` out of the box seems fine by me 👍

**Comment by rstacruz** [comment]
I second this, seems like a reasonable thing to do.

For background: the problem stems from a repo structure like so:

```
/
  packages/
    a/
      node_modules/
    b/
      node_modules/
    c/
      node_modules/
```

Running `standard` in the top-level can cause unnecessary traversions down into node_modules/. There's a workaround :point_up:, but I agree it makes sense to be default behavior.

**Comment by Janpot** [comment]
Is this default provided by `eslint`? Maybe it should be a default in `eslint`?

**Comment by brodybits** [comment]
I would personally favor consistency with `eslint`, assuming there is no good reason otherwise.

**Comment by Janpot** [comment]
Yes, that makes sense. I've been digging through their tickets and found this PR https://github.com/eslint/eslint/pull/10092
Not sure whether they're not open to expand the default, or whether it was just easier to document than fix

**Comment by feross** [comment]
This issue should be fixed in standard v16 because of an improvement to `standard-engine`.

It would be great if someone could test this on your project to confirm, once `standard` 16 is released.
