### ISSUE TITLE
`object-curly-spacing` errors 

### ISSUE THREAD

**Issue by noygal** [standard/standard#1192]
Hi, just upgraded to 12.0.1 and I'm getting an errors, the `eslint` shows `object-curly-spacing` errors (via `eslint-config-standard` plugin).

`index.js`

```js
console.log({a: 1})
``` 

Running version 11.0.1 produce no errors but on 12.0.1 I'm getting:

```bash
$ npx standard@12.0.1 index.js
npx: installed 207 in 3.896s
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /Users/gal/dev/profile-admin-server/index.js:1:13: A space is required after '{'.
  /Users/gal/dev/profile-admin-server/index.js:1:18: A space is required before '}'.
```

Is there been any standard specs updates that I've missed or does it related to eslint? 

**What version of standard?**
12.0.1

**What operating system, Node.js, and npm version?**
Latest stable MacOS, node v8.11.1, npm 5.6.0

**What did you expect to happen?**
Not to display Errors

**What actually happened?**
I'm getting `object-curly-spacing` error from eslint

**Comment by LinusU** [comment]
> Is there been any standard specs updates that I've missed 

Yes, we now enforce curly spacing. See discussion here: https://github.com/standard/standard/issues/609#issuecomment-400826566
