### ISSUE TITLE
Fixer for eslint-plugin-promise breaks code functionality

### ISSUE THREAD

**Issue by adrianmcli** [standard/standard#1194]
**What version of standard?** v12.0.1

This problem stems from the `eslint-plugin-promise` [project](https://github.com/xjamundx/eslint-plugin-promise), and specifically the `param-names` [rule](https://github.com/xjamundx/eslint-plugin-promise/blob/master/__tests__/param-names.js).

## Reproduction

Run the ESLint fixer on the following code:

```js
new Promise((yes, no) => { yes("hello") })'
```

**Expected behavior:**

```js
new Promise((resolve, reject) => { resolve("hello") })'
```

**Actual behavior:**

```js
new Promise((resolve, reject) => { yes("hello") })'
```

## Additional Information

Rather than trying to change people's code, I think it's better to remove the fixer rather than change variable names everywhere. I have submitted an issue to the eslint-plugin-promise repo: https://github.com/xjamundx/eslint-plugin-promise/issues/145

If and when there is a resolution to that issue, we should take steps to update accordingly.

**Comment by adrianmcli** [comment]
Update:

- A maintainer has agreed that we should remove the fixer:
  - https://github.com/xjamundx/eslint-plugin-promise/issues/145#issuecomment-419317646
- PR has been submitted:
  - https://github.com/xjamundx/eslint-plugin-promise/pull/146

**Comment by adrianmcli** [comment]
v4.0.1 has been released and published, and this issue should now be fixed.

Github release link: https://github.com/xjamundx/eslint-plugin-promise/releases/tag/v4.0.1
NPM link: https://www.npmjs.com/package/eslint-plugin-promise

**Comment by feross** [comment]
Thanks @adrianmcli
