### ISSUE TITLE
no-new needs exception for Notification api

### ISSUE THREAD

**Issue by juliangruber** [standard/standard#1197]
**What version of standard?**

12.0.1

**What operating system, Node.js, and npm version?**

macOS, node v10.9.0, npm 6.2.0

**What did you expect to happen?**

This should pass standard:

```js
const { Notification } = window

new Notification('test')
```

**What actually happened?**

I got the error `Do not use 'new' for side effects.`

Since this API is out of my control, I have to introduce a wrapper like this:

```js
const { Notification } = window

const notify = (...args) => new Notification(...args)

notify('test')
```

**Comment by LinusU** [comment]
@juliangruber sorry that no-one got the time to look at this 😞 

https://eslint.org/docs/rules/no-new

The upstream eslint rule doesn't have any configuration for this, so it would be great if you could open an upstream issue to either add the exception there, or allow a list of exceptions to be passed to the rule.

Thanks 🍻
