### ISSUE TITLE
Feature suggestion: .standardignore file

### ISSUE THREAD

**Issue by bookmoons** [standard/standard#1200]
Proposing a `.standardignore` (or `.lintignore`?) file for listing files, directories, and globs to ignore.

ESLint supports [a `.eslintignore` file](https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories) for listing files to ignore. The syntax is the same as `.gitignore`. Tried using this to ignore files but `standard` doesn't seem to pick it up.

The `standard` ignore feature takes input from a property in the `package.json` manifest. I try to keep my manifest clean and shift everything dependency specific out.

**Comment by bookmoons** [comment]
Was hoping for something outside the manifest. Right now [my `package.json`](https://github.com/bookmoons/cashshufflejs/blob/214b7b77471258fb5600f115c072d08bc86b757b/package.json) is mostly all about my package, but with that 1 little `"standard"` section to ignore 1 file. Would rather have that next to the rest of my dotfiles.

**Comment by LinusU** [comment]
Would personally prefer that we support `.eslintignore` instead of rolling our own file. Maybe it's just a switch to turn it on?

**Comment by brodybits** [comment]
??

**Comment by brodybits** [comment]
?

>

**Comment by feross** [comment]
There was a reason that we initially did not support `.eslintignore` but now I can't remember it. Anyone remember?

**Comment by bookmoons** [comment]
Wonder if it's because of the custom parsers. Maybe they don't all support it.
