### ISSUE TITLE
Standard does not warn of adding properties to non-extensible objects.

### ISSUE THREAD

**Issue by setpill** [standard/standard#1201]
**What version of standard?**
`12.0.1`

**What operating system, Node.js, and npm version?**
OS: Ubuntu 18.04
Node.js: v8.12.0
npm: 6.4.1

**Example code**
```js
'use strict'

var obj = {}
Object.preventExtensions(obj)

obj.test = 'this throws a TypeError'
```

**What did you expect to happen?**
Standardjs to warn me of the TypeError that running this code throws.

**What actually happened?**
Standardjs gives no warning and the code throws a TypeError.

**Comment by LinusU** [comment]
Is there an ESLint rule that would warn against that?

**Comment by setpill** [comment]
I'm not sure if a new one would need to be written or if one already exists.

**Comment by setpill** [comment]
After discussion in the ESLint gitter, it seems unlikely that such a rule will be added, so closing this issue.
