### ISSUE TITLE
Can I add Japanese translation for document?

### ISSUE THREAD

**Issue by munierujp** [standard/standard#1202]
Hi, I'm Japanese engineer (and native Japanese speaker)🇯🇵
I'd like to translate documents to Japanese.
Can I do that?

like this:

![2018-09-21 0 10 57](https://user-images.githubusercontent.com/20086673/45828196-f6b6f500-bd32-11e8-97f4-e1db600eff1d.png)

**Comment by feross** [comment]
Yes, please! Thank you for offering :) Send a pull request when you're ready for us to review it.

**Comment by munierujp** [comment]
I'll try it😎

**Comment by munierujp** [comment]
This is my note for translation:

* Avoid ~：〜しないでください。
* No ~：〜してはいけません。/〜があってはいけません。
* 〜 should 〜：〜すべきです。
* 〜 must 〜：〜しなければなりません。/〜する必要があります。
* 〜 not allowed 〜：〜してはいけません。/〜があってはいけません。
* Use ~：〜を使用してください。/〜を用いてください。
* Add ~：〜を入れてください。
* その他：〜してください。

**Comment by munierujp** [comment]
## TODO
- [x ] translate  RULES.md
- [ ] translate README.md
