### ISSUE TITLE
Enforce the array bracket spacing rule

### ISSUE THREAD

**Issue by flipxfx** [standard/standard#1203]
Originally discussed here https://github.com/standard/standard/issues/609#issuecomment-419025829. The object-curly-spacing rule was added, but not the array-bracket-spacing rule.

The array-bracket-spacing should be set to `"array-bracket-spacing": ["error", "never"]`, as shown by the ecosystem impacts and discussions.

**Comment by LinusU** [comment]
Still think this is relevant

**Comment by LinusU** [comment]
Still think this is relevant

**Comment by feross** [comment]
@LinusU Btw, the way to get the bot to not mark an issue as stale is to add any other label. :)

**Comment by feross** [comment]
This will be included in `standard` 13.
