### ISSUE TITLE
Support for BigInt

### ISSUE THREAD

**Issue by synaptiko** [standard/standard#1207]
**What version of standard?**
^12.0.1

**What operating system, Node.js, and npm version?**
x86_64 GNU/Linux; v10.11.0; 6.4.1

**What did you expect to happen?**
When I specify `10n` or `BigInt(10)` it shouldn't trigger an ESLint error. The support is now added to Node and Chrome/Chromium. More info here: https://developers.google.com/web/updates/2018/05/bigint

**Comment by justinkalland** [comment]
The [proposal for BigInt](https://github.com/tc39/proposal-bigint) is in [Stage 3](https://tc39.github.io/process-document/). [ESLint](https://github.com/eslint/eslint) will not support it until Stage 4 (finished).
