### ISSUE TITLE
reconsider func-call-spacing

### ISSUE THREAD

**Issue by smuemd** [standard/standard#1208]
**What version of standard?**
^12.0.1

**What operating system, Node.js, and npm version?**
OSX, node v8.9.3, npm v6.4.1

**What did you expect to happen?**

This is a proposal:

_When applying a function,_
1. _allow a space before the opening paren._

These styles are currently allowed in standard
```js
f(x, y, z)

f(x)(y)(z)

f(g(x, y), h(z))

f(g(x)(y))(h(z))
```
This proposes to also allow the following call styles (effectively not enforcing eslint rule  [http://eslint.org/docs/rules/func-call-spacing](http://eslint.org/docs/rules/func-call-spacing))
```js
f (x, y, z)

f (x) (y) (z)

f (g (x, y), h (z))

f (g (x) (y)) (h (z))
```

**Rational**
This addresses readability problems associated with `)(` style when dealing with regular curried functions. 
For example:
```js
// defining get as curried function
function get (prop) {
  return function (obj) {
    return obj[prop]
  }
}

// calling get
get ('foo') ({ foo: 'bar' })
```
(for more context see https://github.com/sanctuary-js/sanctuary/issues/438)

Note that this has been previously discussed in issue #530
Reconsidering your stance on `func-call-spacing` may help better accommodate functional programming styles.

**Comment by brodybits** [comment]
??
