### ISSUE TITLE
docker centos use standard command exit

### ISSUE THREAD

**Issue by mayuelei66** [standard/standard#1218]
**What version of standard?**
standard 10.0.2 

**What operating system, Node.js, and npm version?**

node 
  v8.11.3
npm 
  5.6.0
docker container info

CentOS Linux release 7.5.1804 (Core) 
Derived from Red Hat Enterprise Linux 7.5 (Source)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core) 
CentOS Linux release 7.5.1804 (Core) 
cpe:/o:centos:centos:7

**What did you expect to happen?**
use spawn stdin execute command in container and get stdout the cmd exit code then continue execute other commands

1.create a container
2.use spawn attach the container
3.change directory to project (spawn stdin `cd to/project/;echo "exitcodeis"$? \n`)
4.npm install (spawn stdin `npm install;echo "exitcodeis"$? \n`)
5.before test, execute sth (spawn stdin `echo before;echo "exitcodeis"$?   \n`)
6. standard(spawn stdin `standard ;echo "exitcodeis"$?  \n`)
7. after test execute sth (spawn stdin `echo after ;echo "exitcodeis"$?  \n`)
8.check finish, kill container

**What actually happened?**
1.create a container
2.use spawn attach the container
3.change directory to project (spawn stdin `cd to/project/  \n`)
4.npm install (spawn stdin `npm install   \n`)
5.standard(spawn stdin `standard   \n`) then get standard command exit code is 0,after a while  the container exit with code 0(unexpected, it should not stop by the standard)
7.'after test' does not execute, program sleeped

**Comment by jprichardson** [comment]
Typo? `standrad`?

**Comment by mayuelei66** [comment]
> Typo? `standrad`?

sorry, fix it
