### ISSUE TITLE
Standard considers static class properties as parsing error in version 12

### ISSUE THREAD

**Issue by Visya** [standard/standard#1225]
**What version of standard?**
standard@12.0.1

**What operating system, Node.js, and npm version?**
MacOS, Node.js v8.12.0, npm 6.4.1

**What did you expect to happen?**
Standard allows static properties in classes

**What actually happened?**
```
class HomeScreen extends React.Component {
  static navigationOptions = {
    title: "MyApp"
  }
  ...
```
Standard output:
```
../screens/Home.js:7:28: Parsing error: Unexpected token =
```

**Comment by xiaweiss** [comment]
ES7 is not supported.
Same problem:
```
class Foo {
    myFunction  = () => {
  
   }
}
```

**Comment by brodybits** [comment]
??

**Comment by xiaweiss** [comment]
the above code will report lint error.
but in standard version 10.0.3, it worked, no error

**Comment by xiaweiss** [comment]
it also might be a bug of package [linter-js-standard](https://atom.io/packages/linter-js-standard) of atom editor

**Comment by lovetingyuan** [comment]
same problem, anyone will fix it?

**Comment by brodybits** [comment]
?

**Comment by feross** [comment]
Hi everyone,

You need to `npm install babel-eslint` and tell `standard` to use it as the parser. See: https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features

Once this is a Stage 4 language proposal *and* ESLint adds support for it, then the babel parser will no longer be required.
