### ISSUE TITLE
IIFE with leading semicolon wants to be intended when directly after imports

### ISSUE THREAD

**Issue by kjg** [standard/standard#1227]
**What version of standard?** 11.0.1

**What operating system, Node.js, and npm version?** MacOS 10.14.2, Node 8.9.3, NPM 6.4.1

**What did you expect to happen?**

This code should not cause any errors
```js
import $ from 'jquery'

// Bootstrap
;(() => {
  window.$ = $
})()
```

**What actually happened?**
I get the error `Expected indentation of 2 spaces but found 0.`

Interestingly if I move this IIFE to below other code, I don't get the error only when it's the first bit of code after the import statement.

**Comment by kjg** [comment]
Reported https://github.com/eslint/eslint/issues/11082

**Comment by kjg** [comment]
Fixed https://github.com/eslint/eslint/pull/11085

**Comment by feross** [comment]
Thanks for reporting this issue and getting it fixed in ESLint @kjg. Much appreciated!
