### ISSUE TITLE
Unused variables don't output warnings

### ISSUE THREAD

**Issue by jmz7v** [standard/standard#1228]
## Problem:

The following small React component `link.js` has a useless destructured variable, it is not being caught by Standard.

```jsx
import React from 'react'

const Link = ({ url, useless, children }) => (
  <a href={url}>{children}</a>
)

export default Link
```

**What version of standard?**

Standard: `12.0.1`

**What operating system, Node.js, and npm version?**

OS: `macOS 10.14 (18A391)`
Node: `v10.11.0`
NPM: `6.4.1`

**What did you expect to happen?**

To get an error like
```
link.js:3:22: 'useless' is assigned a value but never used.
```

**What actually happened?**

From what I can recall this would previously output an error since this is a conflict with one of the rules of Standard `No unused variables`.

Output:
```
empty output
```

**Comment by justinkalland** [comment]
From the best I can tell [StandardJS has always skipped checking for unused arguments](https://github.com/standard/eslint-config-standard/blame/15f684d323b8c30b4743e39fd9b1b61b184a87ff/index.js#L144).

I have created a pull request that changes the behavior.

**Comment by feross** [comment]
Discussion moving here: https://github.com/standard/eslint-config-standard/pull/136
