### ISSUE TITLE
The link of "blog.izs.me" in README.md is broken.

### ISSUE THREAD

**Issue by constdrop** [standard/standard#1230]
The link of README.md line 70 (following) is broken.
[1]: http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding

**Comment by brodybits** [comment]
Looks ok now

**Comment by LinusU** [comment]
Works for me as well 👍

**Comment by constdrop** [comment]
Sorry, I can see that page now. DNS lookup is failed when I had posted.
