### ISSUE TITLE
Preact `'h' is defined but never used. (no-unused-vars)`

### ISSUE THREAD

**Issue by alex996** [standard/standard#1231]
> This a follow up to #351. The issue was re-opened in May, but went stale and got auto-closed. I read the thread and didn't find any definitive solution, so I'd like to bring it up again.

I have a Preact project that defines an `h` pragma, as per the [docs](https://preactjs.com/guide/getting-started#global-pragma)

```json
"plugins": [
  ["@babel/transform-react-jsx", { "pragma":"h" }]
]
```

Unfortunately, this pragma raises `no-unused-vars` error, as in

```js
import { h } from 'preact' // 👎 'h' is highlighted in the editor
const App = props => <div />
```

At the same time, `React` pragma in `react` is auto-magically ignored, which is correct

```js
import React from 'react' // 👍 doesn't raise 'no-unused-vars`
const App = props => <div />
```

 The only known workaround in Preact is to include `/* eslint-disable no-unused-vars */` at the top of **each** component file, which is redundant. I tried other options, including

- creating `.eslintrc` with `"rules"` key, but Standard ignores it by design
- `"rules": {"no-unused-vars": [0, { "varsIgnorePattern": "^h$" }]}` in `package.json`, no effect
- adding `"globals": ["h"]` - of course, no effect either
- `"settings"` key, suggested [here](https://github.com/developit/preact-boilerplate/issues/100#issuecomment-294979565), but it also seems to be ignored
- just about every trick suggested in #351, no luck 😞

Is there anything at that can be done about this? It not only affects `preact`, but other libs like `deku` or `hyperapp`. The way I see it, Standard could
- allow ignoring rules (which I think you have a firm stance against 😃)
- ignore `h` by default, just like `React`
- add a new setting (?)

Any thoughts? Thanks

---

**What version of standard?**
`^12.0.1`

**What operating system, Node.js, and npm version?**
- **`node -v`**: `11.2.0`
- **`npm -v`**: `6.4.1`

**What did you expect to happen?**
It should ignore the `h` pragma.

**What actually happened?**
It reports `'h' is defined but never used. (no-unused-vars)`

**Comment by LinusU** [comment]
I think that there is a special comment that you can use to instruct eslint of the pragma you are using 🤔 something like: `/* @jsx h */`

**Comment by stevenzeck** [comment]
I'm receiving somewhat similar errors with probot work using standard and typescript-eslint-parser.  I'll import classes, such as `import { Application, Context } from 'probot'` and then when I use them like the below, I get `Application is defined but never used`.

```
export = (app: Application) => {
// code here
}
```

**Comment by alex996** [comment]
@LinusU It doesn't seem to have any effect in `standard@^12.0.1`. Ex:

```js
/* @jsx h */
import { h, render } from 'preact' // 'h' is defined but never used
```

Besides, it also requires to be added to every file. It's surely a bit more succinct than

```js
import { h, render } from 'preact' // eslint-disable-line no-unused-vars
```

but still, annoying. Tbh, I'm sure most people can live with that, but couldn't we have a config option for this?

**Comment by LinusU** [comment]
@alex996 did you try having some JSX in the file as well? Otherwise, I think that it will, correctly, warn for no usage...

```js
/* @jsx h */
import { h } from 'preact' // 'h' is defined but never used

module.exports = function test () {
  return <div>Test</div>
}
```

**Comment by alex996** [comment]
@LinusU Same, it doesn't work with JSX either.

```js
/* @jsx h */
import { h, render } from 'preact' // 'h' is defined but never used
export const Component = props => <div />
```

**Comment by JerryGreen** [comment]
It definitely needs a setting for that. I think this should ideally be an environment config's part, like this:

```
"env": ["browser", "jest", "preact"]
``` 

But these [environments are part of eslint](https://eslint.org/docs/user-guide/configuring#specifying-environments), not standard. And, unfortunately, looks like it's not possible to add custom environments yet (I haven't found such a documentation, also - look [this](https://github.com/eslint/eslint/issues/1130) and [that](https://github.com/eslint/eslint/issues/4782))

**Comment by doubleswirve** [comment]
@LinusU, @alex996 I had luck with the `@jsx` comment by using two `*` at the beginning of the comment, e.g.,

```javascript
/** @jsx h */
import { h, render } from 'preact'
```

I think you were using `/* @jsx h */`. Hope that helps! :)

**Comment by LinusU** [comment]
Ahhhhhh, that's it 🤦‍♂️ 😄 

@doubleswirve good find 👍

**Comment by kilgarenone** [comment]
I add this to my eslintrc to fix it:

```
"settings": {
    "react": {
      "pragma": "h"
    }
}
```
