### ISSUE TITLE
Weird documentation language on pt-BR

### ISSUE THREAD

**Issue by LuanComputacao** [standard/standard#1232]
**What version of standard?**
v12.0.1 (Aug 30)

**What operating system, Node.js, and npm version?**
Any

**What did you expect to happen?**
Clear documentation language on pt-BR/

**What actually happened?**
Weird documentation language on pt-BR

**Comment by LinusU** [comment]
Would you mind elaborating a bit? Which part of weird? Would you be able to submit a PR to fix it?

**Comment by LuanComputacao** [comment]
In Brazil, It's necessary to be careful with slangs. A slang can have different meanings over the country.
I think we can change the "Dá boa, sério!" e the "funciona logo de cara" to a more used expression.
I'll spend some time in the next week to help with the pt-BR version.

**Comment by herodrigues** [comment]
@LuanComputacao yeah, the translation is too weird. It seems Google translator was used.

I can help on this too

**Comment by herodrigues** [comment]
@LuanComputacao just sent a PR. Can you help me with this?

**Comment by LuanComputacao** [comment]
I don't sent.
Yes, I can help you.
I have started the code review. But I'll finish Wednesday.
Thank you for your collaboration! :)
