### ISSUE TITLE
using "class" results in "Unexpected reserved word" error

### ISSUE THREAD

**Issue by mojoaxel** [standard/standard#1235]
**What version of standard?**
* standard@^12.0.1

**What operating system, Node.js, and npm version?**
* node: v10.10.0
* npm: v6.4.1
* OS: ubuntu 18

**What actually happened?**

index.js:
```js
class abc {
  constructor() {
    console.log("It's alive!");
  }
}
module.exports = abc
```
Calling `standard` without any special configuration results in an error:
```
Error: Use JavaScript Standard Style (https://github.com/feross/standard)
  index.js:1:1: Unexpected reserved word
```

**Comment by LinusU** [comment]
I cannot reproduce this 🤔 

<img width="573" alt="screenshot 2018-12-10 at 13 56 15" src="https://user-images.githubusercontent.com/189580/49736936-5dd5ad00-fc83-11e8-9c46-655e5e359dbc.png">

**Comment by mojoaxel** [comment]
@LinusU Thanks for your response. Maybe I'm doing something wrong? I have this project in this project: https://github.com/nbesli/pdf-merger-trvl

**Comment by LinusU** [comment]
Works for me.

<img width="592" alt="screenshot 2018-12-10 at 14 14 36" src="https://user-images.githubusercontent.com/189580/49737919-efdeb500-fc85-11e8-9bf6-2d9273d6495b.png">

Could it be that you have an old version of standard earlier in your `$PATH`? What does `standard --version` print?

**Comment by mojoaxel** [comment]
> Could it be that you have an old version of standard earlier in your $PATH? What does standard --version print?

Yes that was the problem :man_facepalming: I feel so stupid, but I guess we all have days like that...
@LinusU Thanks again for the help! Enjoy the holidays.
