### ISSUE TITLE
'no-unused-vars' outputs errors instead of warnings

### ISSUE THREAD

**Issue by DAmNRelentless** [standard/standard#1241]
**What version of standard?**
1.2.3

**What operating system, Node.js, and npm version?**
OS: Windows 10 64bit 1809
Node: 10.15.0
npm: 6.4.1

**What did you expect to happen?**
I expected that StandardJS highlights the unused variables only as warnings and not as errors.

**What actually happened?**
StandardJS highlights unused variables as  errors and not as warning although I changed it to warnings in my .eslintrc.
```js
        "no-unused-vars": [
          "warn",
          {
            "args": "all"
          }
        ]
```

**Comment by LinusU** [comment]
The policy for Standard is to not have any warnings at all and just have errors. This is since warnings often get ignored and won't actually cause any tests to fail, etc.

Why do you feel that `no-unused-vars` specifically should just be a warning?

**Comment by DAmNRelentless** [comment]
When a project is still in development, I often have vars that are not used yet especially libraries but that will be used later on. So I just need a reminder that I still have this library left and therefor a warning is enough in my opinion. But no worries, if that's the policy, I simply close this issue.
