### ISSUE TITLE
Destructuring with empty sections throws off standard into an endless loop

### ISSUE THREAD

**Issue by lukasoppermann** [standard/standard#1243]
**What version of standard?**
- typescript@3.2.4
- typescript-eslint-parser@22.0.0
- standard@12.0.1
`standard --parser typescript-eslint-parser --plugin typescript`

**What operating system, Node.js, and npm version?**
- Mac OSX
- Node v11.7.0
- NPM 6.5.0

**What actually happened?**

I have this line of code:

`Promise.all([homepage, litHtml, layout]).then(([homepageHtml, , ]) => {`
The error I get is `Expected consistent spacing`. However if I remove the space after the last comma, I get `space missing`.

So I am at a loss at what to do. Thanks for your help.

**Comment by LinusU** [comment]
I'm not exactly sure on what you are trying to do with the commas there 🤔 

The only reason I can see to have empty elements is to skip certain elements and then get a value at the end. But in your case, you don't have a final variable, and this you could just write it like this?

```js
Promise.all([homepage, litHtml, layout]).then(([homepageHtml]) => {
```

**Comment by lukasoppermann** [comment]
Darn, that is of course correct. Thanks for your help.
