### ISSUE TITLE
Error reported when destructuring with comments in place of skipped variables.

### ISSUE THREAD

**Issue by wjhir** [standard/standard#1244]
| Standard | OS | node | npm |
| --- | --- | --- | --- |
| 12.0.1 | Windows 10 | 10.2.0 | 5.6.0 |

When destructuring an array and skipping unused indices, I like to include a comment to annotate what's being skipped. When the destructuring is a single line and there is a comment either before the first item or after the last, it causes an unexpected error: `Expected consistent spacing (standard/array-bracket-even-spacing)`. This happens whether or not the brackets are padded with spaces. The error does not occur when the destructuring is split over multiple lines.

Examples:
```javascript
const [/* match */, $1, $2] = regex.exec(str)
const [ match, $1 /* $2 */ ] = regex.exec(str)
const [/* match */, $1 /* $2 */] = regex.exec(str)
const [ /* comment */ match, $1 ] = regex.exec(str)
const [/* comment */ match /* $1 */] = regex.exec(str)
```

**Comment by feross** [comment]
In `standard` 13 we settled on disallowing spaces in arrays. 

But you're right, that comments causing the rule to trigger is not ideal. Unfortunately, there is no way to tell ESLint to not treat this as an error. If you'd like to get this fixed, could you open an issue on the ESLint repo and see what the team thinks about adding an exception to allow a space when there's a inline `/* */` style comment present. 

Cheers!
