### ISSUE TITLE
Get error because of third party package

### ISSUE THREAD

**Issue by inyutin** [standard/standard#1245]
Standard version: 12.0.0

Operating system: Manjaro 18.0.2 Illyria
Node.js: v11.6.0
npm: 6.7.0

In my project I use this side package:
https://github.com/alexandercerutti/node-telegram-operation-manager

So, I have this line:
`let reply = new Reply['default']()`

I get an error `A constructor name should not start with a lowercase letter.`, because of "default" in declaration. However I can't change it, because this is how it written in side package, I use.

**Comment by LinusU** [comment]
duplicate of #892
