### ISSUE TITLE
travis build error. CRA react scripts don't want to be friends with standard

### ISSUE THREAD

**Issue by atherdon** [standard/standard#1249]
**What version of standard?**
12.0.1
*What operating system, Node.js, and npm version?**
Linux, 11.6.0, 6.7.0
**What did you expect to happen?**
i just find this package and only install it to my CRA project.
**What actually happened?**
Travis CI trigger a build and notify me about the issue. Details are here: https://travis-ci.org/ChickenKyiv/recipe-antd/jobs/492270612
as per advice from `react-scripts test` option 7 - I printed a tree of eslint.
this is what i got
```
│ └─┬ standard@12.0.1
│   ├── eslint@5.4.0
│   └─┬ eslint-plugin-import@2.14.0
│     └── eslint@5.12.0  extraneous
└─┬ react-scripts@2.1.5
  └── eslint@5.12.0
```

Thank you for your help and awesome tool. I like it!

**Comment by DiegoRBaquero** [comment]
This seems like a problem of yarn dep tree, did you try:

>  To fix the dependency tree, try following the steps below in the exact order:
>   1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
>   2. Delete node_modules in your project folder.
>   3. Remove "eslint" from dependencies and/or devDependencies in the package.json file in your project folder.
>   4. Run npm install or yarn, depending on the package manager you use.

**Comment by atherdon** [comment]
sure i did. this is why i mention that after going to option 7(so i did all suggestions) - i get that printed tree, where standard has `eslint5.4` and latest `react-scripts` has `eslint5.12`

**Comment by feross** [comment]
FYI - StandardJS has upgraded to ESLint v6 which should have resolved this problem.

**Comment by atherdon** [comment]
Thank you
