### ISSUE TITLE
Bug - Closing curly brace does not appear on the same line

### ISSUE THREAD

**Issue by perezLamed** [standard/standard#1253]
**What version of standard?**
"standard": "^12.0.1",
**What operating system, Node.js, and npm version?**
Node v10.1.0
npm  v5.6.0
**What did you expect to happen?**
No error for following code block (or another style error):
```
    if (colour === '') {
      throw new Error(`Expected token '}' not found on line:'${lineNo} \n-> '${line}'.\n`)
    }
```
**What actually happened?**
**error**  Closing curly brace does not appear on the same line as the subsequent block

**Comment by LinusU** [comment]
Interesting, this seems like a bug in eslint, would you mind submitting an upstream issue report there? ☺️

**Comment by feross** [comment]
I just tested this on standard v13 and it's not an issue, so it seems like if this was an issue it has since been fixed.
