### ISSUE TITLE
Documentation should be updated in TypeScript section

### ISSUE THREAD

**Issue by mehmetnyarar** [standard/standard#1255]
Hi,

`typescript-eslint-parser`and `eslint-plugin-typescript`packages are deprecated. I think the documentation should be updated based on this fact.

```shell
npm install @typescript-eslint/parser @typescript-eslint/eslint-plugin --save-dev
```

```json
{
  "standard": {
    "parser": "@typescript-eslint/parser",
    "plugins": [ "@typescript-eslint/eslint-plugin" ]
  }
}
```

**Comment by LinusU** [comment]
Neat, PRs welcome ☺️

**Comment by mehmetnyarar** [comment]
Gladly, but I don't know how. This would be my first open-source contribution, so forgive my ignorance :)

**Comment by cdaringe** [comment]
even with the plugin, it doesn't load right in standard.  see https://github.com/standard/standard/issues/1252
