### ISSUE TITLE
Standard 12.0.1 uses eslint version 5.4.0 when 5.6.0 is specified in the package.json

### ISSUE THREAD

**Issue by 7373Lacym** [standard/standard#1256]
**What version of standard?**
12.0.1
**What operating system, Node.js, and npm version?**
      System Version: macOS 10.13.6 (17G4015)
      Kernel Version: Darwin 17.7.0
      npm Version: 6.5
      node Version: v11.8.0
**What did you expect to happen?**
Installing standard as a dev dependency in an empty project would use eslint 5.6
**What actually happened?**
Installing standard as a dev dependency in an empty project would use eslint 5.4
Here is my package.json
```
{
  "name": "test-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "standard": "^12.0.1"
  }
}
```

Running `npm ls eslint` yields
```
test-project@1.0.0 ~/test-project
└─┬ standard@12.0.1
  └── eslint@5.4.0
````
Eslint 5.4.0 does not play well with create-react-app.  Might be related or the same thing as https://github.com/standard/standard/issues/1249

**Comment by LinusU** [comment]
It's bumped to 5.6.0 in master, but not released yet.

@feross would you mind releasing a `12.0.2` release to fix the problems with `create-react-app`?

also, is there a reason `eslint` is pinned with `~` intead of `^`? 🤔

**Comment by 7373Lacym** [comment]
Ahhh okay.  Sorry for the misunderstanding.

**Comment by ovhemert** [comment]
I would also like to see the new version published. It seems to resolve a high severity vulnerability also.

`standard@12.0.1 › eslint@5.4.0 › js-yaml@3.13.0`

You can see it [here](https://app.snyk.io/test/npm/js-yaml/3.13.0) on Snyk.

cc: @LinusU @feross

**Comment by LinusU** [comment]
unfortunately, I don't have access to releasing new versions, ping @feross

**Comment by ovhemert** [comment]
Would be great.. Thanks 👍🏻

**Comment by LinusU** [comment]
#1270 🚀

**Comment by feross** [comment]
Standard 13 is released which uses ESLint 6 🚀So, I'll close this issue now.
