### ISSUE TITLE
Cannot find module 'babel-eslint' (both standard and babel-eslint already installed locally)

### ISSUE THREAD

**Issue by inovramadani** [standard/standard#1257]
**What version of standard?**
12.0.1

**What operating system, Node.js, and npm version?**
Windows 10
Node v10.15.1
NPM v.6.8.0

**What did you expect to happen?**
I install both standard and babel-eslint on devDependencies (locally).
I run `standard --parser babel-eslint`
I get the standard use babel-eslint parser to recognize babel code style and not stating it as style error

**What actually happened?**
I install both standard and babel-eslint on devDependencies (locally).
I run `standard --parser babel-eslint`
I get error:  Cannot find module 'babel-eslint'

I read from previous issues [85](https://github.com/standard/standard/issues/85) [1167](https://github.com/standard/standard/pull/1167), it should be fixed when they are installed on the same level. But it does not happen on mine.

I have tried to put config below on package.json:
```
"standard": {
    "parser": "babel-eslint"
  }
```
But it does not resolve the issue.

**Comment by LinusU** [comment]
Just tried this in an empty directory, and it works for me:

```sh
$ echo {} > package.json

$ npm add standard babel-eslint
+ babel-eslint@10.0.1
+ standard@12.0.1

$ echo 'export class Foo { test = 3 }' > index.js

$ standard --parser babel-eslint 
```

**Comment by timoxley** [comment]
@inovramadani can you post your `package.json` and the exact steps to reproduce?

**Comment by timoxley** [comment]
@inovramadani what happens if you run `npx standard --parser babel-eslint`

**Comment by inovramadani** [comment]
> Just tried this in an empty directory, and it works for me:
> 
> ```shell
> $ echo {} > package.json
> 
> $ npm add standard babel-eslint
> + babel-eslint@10.0.1
> + standard@12.0.1
> 
> $ echo 'export class Foo { test = 3 }' > index.js
> 
> $ standard --parser babel-eslint 
> ```

It does not work either for me.

> @inovramadani what happens if you run `npx standard --parser babel-eslint`

It works with this one!

**Comment by inovramadani** [comment]
> @inovramadani can you post your `package.json` and the exact steps to reproduce?

As I explained in the beginning:
I install both standard and babel-eslint on devDependencies (locally).
I run standard --parser babel-eslint
I get error: Cannot find module 'babel-eslint'

**Comment by timoxley** [comment]
@inovramadani ok the problem is that without `npx` you're running a globally installed `standard`, not the locally installed version of `standard` in `node_modules`. The local version works because  `babel-eslint` is installed locally. Always use `npx` to use locally installed executables.

**Comment by inovramadani** [comment]
@timoxley you are right, I forgot I have installed standard globally long time before. After installing eslint also globally I can use `standard --fix` and `standard --parser babel-eslint` now.
Thanks!
