### ISSUE TITLE
Require semicolons

### ISSUE THREAD

**Issue by cup** [standard/standard#1258]
thank you

http://airbnb.io/javascript#semicolons

**Comment by cup** [comment]
https://github.com/tc39/ecma262/pull/1062

**Comment by DiegoRBaquero** [comment]
Standard is and will be no semicolons. See previous issues. https://github.com/standard/standard/issues/78 https://github.com/standard/standard/issues/5

**Comment by manisenkov** [comment]
There's https://github.com/Flet/semistandard

**Comment by LinusU** [comment]
Locking, this have been brought up countless of time before...
