### ISSUE TITLE
Getting standard; Pls add flowsent.com to the site

### ISSUE THREAD

**Issue by Flowsent** [standard/standard#1259]
After speaking with @feross on Twitter, he said to open an issue saying we're using standard and to send our URL and logo to be added to the https://standardjs.com site under 'Who's Using StandardJS'. Thank you for making StandardJS and keeping code clean!

Our site adding it is **https://flowsent.com**. Logo attached.
![F-Bird Cursive Purple Kush](https://user-images.githubusercontent.com/48286231/54580637-50d50200-49c6-11e9-9c4a-09d85de02f73.jpg)

Kind Regards,
Rick Bakas

**Comment by LinusU** [comment]
Opened a PR for this here 👉 #1260
