### ISSUE TITLE
no-unneeded-ternary with arrow function results in parsing error

### ISSUE THREAD

**Issue by noisyscanner** [standard/standard#1266]
**What version of standard?**
12.0.1
**What operating system, Node.js, and npm version?**
⬢ 8.11.2 📦 5.6.0

Using the `no-unneeded-ternary` rule.
When formatting code that is using a ternary like below, the function is not wrapped, causing a parse error and fails.
```
const foo = true
const bar = foo ? foo : () => {}
```
Causes this error
```
  2:21  error  Parsing error: Unexpected token

  1 | const foo = true
> 2 | const bar = foo || () => {}
    |                     ^
  3 |

✖ 1 problem (1 error, 0 warnings)
```

*EXPECTED*
```
const bar = foo || (() => {})
```

**Comment by LinusU** [comment]
Could you report this upstream to eslint and link that issue here? Thanks

**Comment by noisyscanner** [comment]
https://github.com/eslint/eslint/issues/11579

**Comment by LinusU** [comment]
That's great, thanks!

**Comment by LinusU** [comment]
This is fixed upstream and is fixed in Standard 13, install with `npm install standard@next`
