### ISSUE TITLE
"error" event handlers require the error to be handled twice

### ISSUE THREAD

**Issue by Holger-Will** [standard/standard#1274]
**What version of standard?**

12.0.1

**What operating system, Node.js, and npm version?**

linux, node 8.4.0 (my min version), npm 6.9.0

**What did you expect to happen?**

when using an event bases error handler:

```
this.port.on('error', err => {
  node.warn('an error occurred')
})
```

i get `Expected error to be handled`
but when i use 

```
this.port.on('error', err => {
  if (err) {
    node.warn('an error occurred')
  }
})
```
everything is fine. 

this seems superfluous to me. The error handler is only called if there is an error, so `err` is always an error object. 

I think you should not be required to check for the error object in  this case.

**Comment by feross** [comment]
Hi @Holger-Will. If you name the variable `err` then you should use it. You don't need to include it in an `if` block, you can do this:

```js
this.port.on('error', err => {
  node.warn('an error occurred ' + err.message)
})
```

 If you don't want to use the error, then don't include an `err` argument. Do this:

```js
this.port.on('error', () => {
  node.warn('an error occurred')
})
```
