### ISSUE TITLE
Support .git/info/exclude

### ISSUE THREAD

**Issue by flying-sheep** [standard/standard#1277]
In a project using standard, I wanted to have my personal ignored directory for some debugging task. I added it to `.git/info/exclude` instread of `.gitignore` because nobody else should needs to have that in its `.gitignore`.

Standard should ignore all files that git ignores.

**Comment by flying-sheep** [comment]
no

**Comment by feross** [comment]
This seems like a reasonable feature to support.

**Comment by flying-sheep** [comment]
Merging standard/deglob#15 will be sufficient :smile:

**Comment by feross** [comment]
Reminder to self: Need to bump the version of `deglob` and add a note to the changelog.
