### ISSUE TITLE
-bash: standard: command not found

### ISSUE THREAD

**Issue by aaronhong** [standard/standard#1280]
The alias to use `standard` on the command line doesn't work. I did an `npm install standard --save-dev`. Not exactly sure how `npm` does command aliasing or adding stuff to `PATH`.

**What version of standard?**
12.0.1

**What operating system, Node.js, and npm version?**
- macOS 10.14.4
- Node.js v8.11.3
- npm 6.8.0

**What did you expect to happen?**
```
$ standard --help
standard - Use JavaScript Standard Style (https://standardjs.com)

Usage:
# etc
```

**What actually happened?**
```
$ standard --help
-bash: standard: command not found
```

**What works for me**
```
$ node_modules/standard/bin/cmd.js --help
standard - Use JavaScript Standard Style (https://standardjs.com)

Usage:
# etc
```

**Comment by kevinrambaud** [comment]
You need to run it by using `npx` and do `npx standard --help` or install it globally by doing `npm install -g standard` and then run `standard --help`.

**Comment by aaronhong** [comment]
@kevinrambaud makes complete sense. Thanks so much. Should this be added to the documentation?

**Comment by kevinrambaud** [comment]
Feel free to open a pull request if you think it could help people to get started more easily. The `Usage` section seems to be the appropriate place to do so.

**Comment by aaronhong** [comment]
I opened a pulled request, but it hasn't been reviewed and merged yet

**Comment by feross** [comment]
@aaronhong Thanks for the PR. It is reviewed and merged now :)
