### ISSUE TITLE
Add import.meta support 

### ISSUE THREAD

**Issue by Lcfvs** [standard/standard#1281]
**What version of standard?**
12.0.1

**What operating system, Node.js, and npm version?**
OS: Windows
Node: 12.1.0
NPM: 6.9.0

**What did you expect to happen?**
I use my own tool [@lcf.vs/mjs-path](https://www.npmjs.com/package/@lcf.vs/mjs-path), to resolve my paths, using the `import.meta`
```
import meta from '@lcf.vs/mjs-path'
 
const __filename = meta.filename(import.meta)
```
**What actually happened?**
Got this error "Parsing Error: Unexpected token import"

**Comment by feross** [comment]
`import.meta` is a stage 3 proposal currently. ESLint only supports stage 4 proposals. For everything else, you can use `babel-eslint`. See https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features
