### ISSUE TITLE
Any one explain the ouput of following JavaScript Code?

### ISSUE THREAD

**Issue by Soorajgit** [standard/standard#1284]
var count = function ()
{ 
    this.c = 0 ; 
var add = function () { 
    return ++this.c; 
};
                       
this.addNum = function (n)
{
    for(i= 0; i<n ; i++) { 
} 
     return this.c ;
}; 
}

**Output of this and explanation since i am new JS.
console.log(new count().addNum(10));
or 
console.log(new count.add());**

**Comment by LinusU** [comment]
This is the issue tracker for a particular linting style for JavaScript, and it's not for general JS questions ☺️
