### ISSUE TITLE
Standard property clarification in package.json

### ISSUE THREAD

**Issue by maggot99999** [standard/standard#1290]
Add the following explanation:

> **To do that, add a standard.ignore property to package.json**

, to all other explanations involving add **standard** property options. This one very well explains what it asks to do, where other explanations say just:

> add this to package.json

, which quietly loses clarity

**Comment by feross** [comment]
Hi, thanks for the suggestion! But it's not clear to me what you're proposing. Can you send a PR with your suggestions so we can have something concrete to look at? Thanks!
