### ISSUE TITLE
Get "No unused variables" Error when import type definitions in TypeScript

### ISSUE THREAD

**Issue by kiochan** [standard/standard#1291]
**What version of standard?**
12.0.1

**What operating system, Node.js, and npm version?**
OS: Mac OS X 10.14.5 18F132
Node.js version: v12.0.0
Yarn version: 1.16.0

**What did you expect to happen?**
I want format my typescript code use `standard **/*.ts --fix` and I run standard with `@typescript-eslint/parser` and `@typescript-eslint/eslint-plugin` .
It should be error free.

package.json
``` json
{
  "standard": {
      "parser": "@typescript-eslint/parser",
      "plugins": [
        "@typescript-eslint/eslint-plugin"
      ]
    }
}
```

types.ts
```typescript
export type TypedObject<T> = {
    [key: string]: T
}
```

test.ts
```typescript
import { TypedObject } from './types'
export const myObject: TypedObject<Date> = {}
```

**What actually happened?**
It caused an error below:
```
standard: Use JavaScript Standard Style (https://standardjs.com)
  ******/test.ts:1:10: 'TypedObject' is defined but never used.
```

**Comment by despian** [comment]
You can fix this per file by adding:
```js
/* eslint no-unused-vars: "off" */
/* eslint @typescript-eslint/no-unused-vars: "error" */
```

Obviously, this isn't a great solution for projects with many .ts files.

I think #1283 address this and some other issues better.

**Comment by feross** [comment]
I'd like to have solve this in a future version of `standard`. In the meantime, you can use [`standardx`](https://www.npmjs.com/package/standardx):

1. `npm install standardx`
2. Rename the `"standard"` field in your `package.json` to `"standardx"`
3. Add a new `"rules": []` section with the following rules:

```json
"rules": {
  "no-unused-vars": "off",
  "@typescript-eslint/no-unused-vars": "error"
}
```

Let's close this issue in favor of: https://github.com/standard/standard/issues/1283#issuecomment-520266170
