### ISSUE TITLE
Cannot find module '/lib/cli.js'

### ISSUE THREAD

**Issue by zhuanqizhirou** [standard/standard#1294]
In webstorm, after enable eslint,error occur.

![image](https://user-images.githubusercontent.com/4990547/59340819-5332c800-8d39-11e9-9472-18bb7dedd89c.png)

![image](https://user-images.githubusercontent.com/4990547/59340858-62197a80-8d39-11e9-9aa9-e4e1f9e07537.png)

**Comment by feross** [comment]
I'm sorry that you're experiencing this issue with Webstorm. I would contact the Webstorm support  team since they'll have a better idea of what could be going on here: https://intellij-support.jetbrains.com/hc/en-us/?webstorm

Good luck figuring it out :)
