### ISSUE TITLE
function con't chang itself, i don't kone why?

### ISSUE THREAD

**Issue by Suntgr** [standard/standard#1298]
```javascript
function toBeRunOnce(args)  {
      // some stuff to do
      console.log('toBeRunOnce has completed');
      toBeRunOnce = function() {};
    }
```

standard: Use JavaScript Standard Style (https://standardjs.com)
  D:\code\...\...: 'toBeRunOnce' is a function.

**Comment by dtudury** [comment]
if you run standard with a -v you'll get a more informative:
`D:\code......: 'toBeRunOnce' is a function. (no-func-assign)`

googling "no-func-assign" returns the eslint description of the rule and the standardjs list of rules

**Comment by feross** [comment]
If you want to ignore the rule for this particular case, you can follow the instructions here: https://standardjs.com/#how-do-i-hide-a-certain-warning
