### ISSUE TITLE
Standard don't using .gitignore on folder 

### ISSUE THREAD

**Issue by IoannRove** [standard/standard#1301]
**What version of standard?**
 standard@12.0.1
  ├─┬ eslint@5.4.0

**What operating system, Node.js, and npm version?**
Ubuntu 18.04.2 LTS, Node.js: v8.10.0, NPM: 3.5.2-0ubuntu4

**What actually happened?**
I have project
test
|-- lib
|   |-- script.js
|-- other
|   |-- script1.js
|-- .git
|-- .gitignore

I have lib/ in my .gitignore but standard scans it anyway. I'd like to use .gitignore. Am I doing something wrong here?

**Comment by feross** [comment]
I cannot reproduce this. Can you share a link to a repo with a minimal project that demonstrates the issue?

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
