### ISSUE TITLE
Question: Is this project being maintained anymore?

### ISSUE THREAD

**Issue by limelights** [standard/standard#1302]
It might very well be that it's stable and doesn't need immediate fixing, which would be great but any clarity into why the latest release was almost a year ago would be appreciated!

All the best!

**Comment by feross** [comment]
The package is stable and doesn't need immediate fixing. I and many others actively use it with no issues. :)

Another reason for no updates in a while: I went back to Stanford to get my masters degree so I haven't had much free time in the last 8 months. This summer, I'm hoping to work out a way to get funding for this and my other OSS work. I'd like to be able to pay one or two others to help with maintaining this and other repos / offer bounties for certain issues.

If you (or anyone reading this) would like your company to be a sponsor of `standard` and get your link and logo on the website homepage and readme, please get in touch (my email is [my first name]@[my first name].org). I'm also happy to do consulting/support services.

**Comment by limelights** [comment]
Awesome, thank you for clarifying, I really appreciate your hard work and that you took the time to respond! :) 🥇
