### ISSUE TITLE
New rule: Disallow characters which are made with multiple code points in character class syntax (no-misleading-character-class)

### ISSUE THREAD

**Issue by feross** [standard/standard#1311]
https://eslint.org/docs/rules/no-misleading-character-class

This prevents a really tricky Unicode regex edge case that always results in a bug. Let's include it in `standard` 13. Part of the eslint recommended set.

0% ecosystem impact, so it's a no brainer.

**Comment by joshgoebel** [comment]
Is there anyone name I could google to read up more on this I'm really failing to understand this rule.

```
> /[\u0300–\u036F]/u.exec("\u0302")
null
> /[\u2020–\u2027]/u.exec("\u2026")
null
```

It will flag the former, but not the latter, yet neither seem to work as I'd hope.  So I'm wondering if there are some cases this rule doesn't catch but are also problematic?
