### ISSUE TITLE
Vulnerability issue: Memory Leak in inquirer@5.2.0 as dependency through eslint 5.​4.​0

### ISSUE THREAD

**Issue by VlkaFenryka** [standard/standard#1319]
**What version of standard?**
12.0.1

**What operating system, Node.js, and npm version?**
OS: Win 10 x64 build 1809
Node: 10.16.0
NPM: 6.9.0

**The Problem**
https://www.sourceclear.com/vulnerability-database/security/memory-leak/javascript/sid-20567

**Solution**
update to eslint >= 6.0.0 and therefore update to inquirer@6.4.0
https://github.com/eslint/eslint/releases
https://github.com/SBoudrias/Inquirer.js/releases/tag/inquirer%406.4.0

**Comment by feross** [comment]
Thanks for the issue. This is not an actually security risk since `standard` is used during development time and not accessible to attackers.

Nonetheless, `standard` 13 will be released shortly (https://github.com/standard/standard/issues/1318) which will update to eslint 6 and fix this issue.
