### ISSUE TITLE
require-atomic-updates: document.title (false positive)

### ISSUE THREAD

**Issue by Lonniebiz** [standard/standard#1320]
I'm using eslint 6.0.1 and believe I'm getting a false positive for the require-atomic-updates rule. Here's a code sample which reproduces the false-positive:
```
async function test()
{
	document.createElement("div");
	await Promise.resolve();
	document.title = "Test";
}
test();
```
The line `document.title = "Test";` (above) produces this error:
```
Possible race condition: `document.title` might be reassigned based 
on an outdated value of `document.title`. (require-atomic-updates)
```

However, I noticed that if I change `document.title` to `window.document.title` the error goes away:
```
async function test()
{
	document.createElement("div");
	await Promise.resolve();
	window.document.title = "Test";
}
test();
```

**Comment by Lonniebiz** [comment]
This issue was moved here:
https://github.com/eslint/eslint/issues/11967

**Comment by feross** [comment]
Thanks for moving the issue to the correct repo!
