### ISSUE TITLE
@standard npm organization

### ISSUE THREAD

**Issue by feross** [standard/standard#1324]
Currently, our npm package permissions across all the various packages is inconsistent. What do folks think of making an npm organization? Not so that we can namespace modules, but just for managing permissions, i.e. every package in the standard ecosystem would be publishable by everyone in the @standard npm org?

I know that @bcomnes has the npm org [`standardjs`](https://www.npmjs.com/org/standardjs) that we could use. Does anyone know who has [`standard`](https://www.npmjs.com/org/standard), which I think would be even nicer?

**Comment by brodybits** [comment]
My understanding of <https://www.npmjs.com/policies/disputes> is that they don’t like squatting on org names. I think it should be reasonable to contact <support@npmjs.com> since I see 0 packages published in the [standard org](https://www.npmjs.com/org/standard). The one possible exception I can see is if it is a paid org.

Good luck!

**Comment by feross** [comment]
@brodybits Thanks for the tip. I just sent npm support an email.

**Comment by Flet** [comment]
I'm on board for this!

**Comment by nexdrew** [comment]
Unfortunately, I don't think that's the way npm package access works. AFAIK you can't manage permissions for an unscoped package using an org/team.

Read about this here: https://docs.npmjs.com/package-scope-access-level-and-visibility

Here's an important note on that page:

<img width="692" alt="Screen Shot 2019-07-12 at 8 23 33 AM" src="https://user-images.githubusercontent.com/1929625/61128042-f54fe800-a47e-11e9-9336-fb92277c1d58.png">

I also tried myself to grant an org read-write access to one of my unscoped packages via the `npm access grant read-write org:team package` command, and it fails with this message:

```
Usage: This command is only available for scoped packages.
```

So, unfortunately, the only way you could use an org on npm to manage access to `standard` packages is if you change the name of the packages to use the org's scope, e.g. `@standard/standard`.

**Comment by bcomnes** [comment]
Standardjs is available whenever you want.  But agreed, standard/standard would be better.  

While it is entirely an awkward experience, you can move unscoped packages over to orgs, I've done this many times.

**Comment by vweevers** [comment]
How about automating the ownership management? Write a tool that, given a list of npm usernames and packages, does `npm owner add <user> <pkg>`.

**Comment by substack** [comment]
learned this tip from @goto-bus-stop. I don't know when they'll turn off this work-around but for now you can use an old version of npm:

```
npx npm@6.5 access grant read-write standard:developers $PKGNAME
```

**Comment by feross** [comment]
@bcomnes I'd like to give this another try. Can you add me as an admin to the `standardjs` organization?

**Comment by bcomnes** [comment]
sure thing

**Comment by bcomnes** [comment]
I can make you admin when you accept @feross please ping me. I have no idea how good or bad npm notifications are.

**Comment by feross** [comment]
@bcomnes Thanks for the incredibly fast reply. Just accepted.

**Comment by bcomnes** [comment]
Ok you are owner! feel free to keep me around or demote me.

**Comment by feross** [comment]
Alright! Everyone with publish permissions on the `standard` package should have received an invite to the @standardjs npm organization.

**Comment by feross** [comment]
Some folks may have been left out. If you part of the @standard GitHub organization and also have npm publish rights on one of the other standard packages, please comment here and I will add you to the `standardjs` npm organization.

**Comment by feross** [comment]
Last thing – I just removed publishers from the npm package who lack 2FA. Please enable 2FA before accepting your new npm organization invite.

**Comment by feross** [comment]
cc @standard/folks Please see my last few comments!

**Comment by Raynos** [comment]
@feross I've enabled 2FA but i cannot see the npm organization invite.

**Comment by feross** [comment]
@Raynos I just sent you a fresh npm org invite.

If this happened for anyone else, please let me know and I can re-send it.

**Comment by toddbluhm** [comment]
@feross can I get an invite so I can publish `ts-standard` under the org?

**Comment by Raynos** [comment]
Thanks you.

**Comment by feross** [comment]
@toddbluhm Just sent you an invite. Please ensure you have 2FA enabled on your npm account before accepting the invite – thanks!

**Comment by feross** [comment]
@toddbluhm Can you add `ts-standard` to the `standardjs` organization by using the "Add package" button on the page here: https://www.npmjs.com/settings/standardjs/packages

**Comment by toddbluhm** [comment]
@feross I accepted the org invite, but I do not have an "Add package"/"Add existing package" button. Can I add you as a maintainer to `ts-standard` and maybe you can transfer it that way? Or you can try making me a temporary admin and I can see if the button shows up then. However, you want to handle this 😄 

If others have a suggestion I am certainly open to that as well.

**Comment by feross** [comment]
@toddbluhm You're now an admin. Can you give it another try on that page and see if the "add package" button shows up.

**Comment by toddbluhm** [comment]
@feross it worked! `ts-standard` is moved over and is now owned by the org/team. I now only have access to it through the standardjs team. Feel free to put me back to `member` permissions.

**Comment by feross** [comment]
@toddbluhm Thanks for completing the transfer!
