### ISSUE TITLE
Update version of standard on "Try It Out" page

### ISSUE THREAD

**Issue by feross** [standard/standard#1332]
Hey @Flet! The demo page hits a remote service to make code `standard`, is that right?

How do we update it? It's currently running `standard` v10 it seems:

```
standardizer@2.0.0, standard@10.0.3, eslint@3.19.0, eslint-config-standard@10.2.1, eslint-config-standard-jsx@4.0.2, eslint-plugin-import@2.2.0, eslint-plugin-node@4.2.3, eslint-plugin-promise@3.5.0, eslint-plugin-react@6.10.3, eslint-plugin-standard@3.0.1, standard-engine@7.0.0
```

**Comment by Flet** [comment]
Oh! Yeah that is on Glitch.I'll updated it

**Comment by Flet** [comment]
Fixed! Can you verify?
- Moved the repo to https://github.com/standard/standardizer
- updated deps and `standard` version.
- imported latest to Glitch project.

I'll pass along a Glitch project invite in a private channel @feross. Totally fine if we want to move away from this external service as well. 

I recall having problems `browserify`ing the eslint project way back, so this was a path of less resistance. Perhaps we would have more luck with eslint today. A version of `standard` that runs 100% client side would be pretty neat! :)

**Comment by feross** [comment]
> Fixed! Can you verify?

Looks like it's working now! Thanks for the quick fix.

> I'll pass along a Glitch project invite in a private channel @feross. Totally fine if we want to move away from this external service as well.

I didn't realize this was deployed on Glitch. Nor that Glitch could do server-side stuff. Really neat!

> A version of `standard` that runs 100% client side would be pretty neat! :)

Agreed!
