### ISSUE TITLE
Not working with Next 9 Dynamic Route Segments via File System

### ISSUE THREAD

**Issue by pex** [standard/standard#1333]
**What version of standard?**

13.0.2

**What operating system, Node.js, and npm version?**

MacOS 10.14.5, Node.js v12.4.0, npm 6.9.0

**What did you expect to happen?**

Next.js 9 introduced [Dynamic Route Segments via File System](https://nextjs.org/blog/next-9#dynamic-route-segments). Query parameters are defined using square brackets in file names (`[` and `]`).
I'd expect standard to support these file names.

**What actually happened?**

An error occurs:

```
Error: No files matching '/.../pages/de/blog/[slug].js' were found.
    at FileEnumerator.iterateFiles (/.../node_modules/eslint/lib/cli-engine/file-enumerator.js:274:23)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (/.../node_modules/eslint/lib/cli-engine/cli-engine.js:744:48)
    at /.../node_modules/standard-engine/index.js:124:61
    at /.../node_modules/deglob/index.js:51:12
    at end (/.../node_modules/run-parallel/index.js:18:15)
    at done (/.../node_modules/run-parallel/index.js:22:10)
    at each (/.../node_modules/run-parallel/index.js:28:7)
    at /.../node_modules/run-parallel/index.js:43:37
    at f (/.../node_modules/once/once.js:25:25)
```

**Comment by LinusU** [comment]
Would you mind checking if this is a bug in upstream eslint (seems like it) and report it there? Thanks!

**Comment by feross** [comment]
Based on the stack trace, there's a chance this is a bug in`deglob`.

**Comment by pklepacki** [comment]
For now it seems that with current version 14.3.4 files with names in brackets `[example].js` are simply skipped. The output is just: `c:\dev\some-project\pages\[example].js ignored.` Is there any way to force linting these? I wasn't able to find any to work on file save.

**Comment by feross** [comment]
This will be fixed in `standard` 16
