### ISSUE TITLE
Inconsistent spacing between objects and arrays

### ISSUE THREAD

**Issue by mafintosh** [standard/standard#1335]
On the latest version of standard when writing objects I have to write them like this:

```
const foo = { foo: 'bar } // with the space
```

But when I make arrays I now have to do it like this

```
const foo = ['foo', 'bar']
```

Whilst `[ 'foo', 'bar' ]` is now disallowed.

I personally find this confusing so I was wondering if there was any motivation behind this change? :)

**Comment by LinusU** [comment]
I think the motivation was mostly that that is how the majority of the eco-system does it. Enforcing arrays with spacing broke a ton of repositories, and enforcing objects without spacing also broke a ton of repositories.

For what it's worth, prettier also defaults to this. XO seems to enforce no spacing in both array and object.

I agree that it's a bit weird that it's not the same, but this has been the style that I've personally always used, and it's the one I've seen most used in the wild as well...

**Comment by feross** [comment]
What @LinusU said :) We tried both ways and no spaces felt more natural and would cause the least ecosystem breakage when updating to the latest version of `standard`.

Also, anecdotally speaking, It's actually a great style once you get used to it. :)
