### ISSUE TITLE
"Use default import syntax to import"

### ISSUE THREAD

**Issue by lemoustachiste** [standard/standard#1338]
**What version of standard?**
13.0.1

**What operating system, Node.js, and npm version?**
Any

**What's happening**
I am using some imports of the sort: 
```
import { default as MyComponent } from './MyComponentContainer';
```

which I think make sense in the context of what I am doing. Upgrade from 12.0.1 to 13.0.1 throws an error:

```
2:21  error  Use default import syntax to import 'MyComponent'
```

I don't really want to because then it would not abstract the layer on top of my component.
I am trying to disable eslint from crying here, but I can't seem to find the rule behind that (tried `no-named-as-default` and `no-useless-rename`), and it does not seem listed in the changelog for the new version. 

Could you point me to the right rule? 

Thanks

**Comment by dtudury** [comment]
if you run standard with -v it gives you
```
Use default import syntax to import 'MyComponent'. (import/no-named-default)
```
so I guess `import/no-named-default` is the rule? sorry, I don't understand your motivation for disabling it but maybe searching that term will move you towards where you want to be 😄

**Comment by feross** [comment]
I believe your code equivalent to this:

```js
import MyComponent from './MyComponentContainer'
```

which seems much nicer than what you've got there now.
