### ISSUE TITLE
Standard + Legacy Decorators

### ISSUE THREAD

**Issue by mattdesl** [standard/standard#1340]
**What version of standard?**

12.0.1

**What operating system, Node.js, and npm version?**

node 8.10.0, npm 6.1.0

**What did you expect to happen?**

I would expect there to be a way to use legacy decorators with standard and `babel-eslint` parser. I already have this in my package.json:

```js
  "semistandard": {
    "parser": "babel-eslint"
  }
```

**What actually happened?**

I cannot find a way to configure the `babel-eslint` parser to accept legacy decorator syntax. Is such a thing possible with standard?

**Comment by mattdesl** [comment]
For now I've published this plugin:

https://github.com/mattdesl/eslint-plugin-legacy-decorators

Usage after installing it + babel-eslint:

```js
  // ... in package.json ...
  "semistandard": {
    "parser": "babel-eslint",
    "plugins": ["legacy-decorators"]
  }
```

**Comment by feross** [comment]
Perhaps you can use `standardx` for this? Or use `eslint` directly?
