### ISSUE TITLE
one time donation

### ISSUE THREAD

**Issue by dtudury** [standard/standard#1341]
All your support options are subscriptions. I'd love to support your cause but financially I'm more in a "let me buy you a beer to say thanks" place than a "let me buy you a lifetime subscription to a beer of the month club" place :)

...could you please add a way to make a one time donation? and thanks for a great project

**Comment by feross** [comment]
@dtudury Thanks!! You're awesome ❤️

If you scroll to the bottom of [feross.org/thanks](https://feross.org/thanks/) I list my Paypal and cryptocurrency addresses.

**Comment by dtudury** [comment]
thank you! I guess I could have found that on my own with a little more stalking; speaking of which... paypal says you're from el dorado hills? I grew up a town over in fair oaks :)

**Comment by feross** [comment]
> paypal says you're from el dorado hills? I grew up a town over in fair oaks :)

Hah, that's awesome!

**Comment by dtudury** [comment]
well, when we eventually move to Folsom because we can't afford bay area schools for our kids maybe I'll buy you that literal beer too
