### ISSUE TITLE
Forbid import of modules using absolute paths (import/no-absolute-path)

### ISSUE THREAD

**Issue by jseminck** [standard/standard#1343]
The issue you previously reported about this rule should be fixed now, see: https://github.com/benmosher/eslint-plugin-import/issues/803#issuecomment-303754437

So if you'd like to re-add this rule and try it out again, now would be a good time. If you need help with PR let me know, should be trivial change: 

* bump `eslint-plugin-import` 
* add the rule again to the config file

**Comment by feross** [comment]
This rule will be re-enabled in `standard` v14.
