### ISSUE TITLE
Make shareable config easier to use

### ISSUE THREAD

**Issue by feross** [standard/standard#1345]
It would be great if there's some way to avoid having folks need to install 5-6 packages when they're using [`eslint-config-standard`](https://www.npmjs.com/package/eslint-config-standard) directly.

See:
- https://github.com/standard/eslint-config-standard-react/pull/56#issuecomment-510695694
- https://eslint.org/docs/developer-guide/shareable-configs#publishing-a-shareable-config

**Comment by feross** [comment]
It doesn't seem possible to make things simpler. The instructions say:

> If your shareable config depends on a plugin, you should also specify it as a peerDependency (plugins will be loaded relative to the end user’s project, so the end user is required to install the plugins they need). However, if your shareable config depends on a third-party parser or another shareable config, you can specify these packages as dependencies.

We only depend on plugins in `eslint-config-standard` and `eslint-config-standard-jsx`, so these must be peer dependencies. We don't depend on other configs or a custom parser (yet).

**Comment by mightyiam** [comment]
That's right. Here's the upstream issue to track:
https://github.com/eslint/eslint/issues/3458
