### ISSUE TITLE
Consider removing `no-callback-literal` rule

### ISSUE THREAD

**Issue by feross** [standard/standard#1352]
See discussion at: https://github.com/standard/eslint-plugin-standard/issues/12#issuecomment-298227852

**Comment by feross** [comment]
> @bookercodes It's a tall order, and something I am sure has been suggested before, but a directory of rules/errors similar to https://eslint.org/docs/rules/ explaining each rules' behaviour and reasoning would be a delight ✨

We have that! See: https://standardjs.com/rules.html

**Comment by feross** [comment]
There are a few outstanding problems with this rule:

1. It can't handle the spread operator. Here's a minimal example:

```js
module.exports = a

function a (cb) {
  cb(...[new Error(''), 1, 2]) // Unexpected literal in error position of callback.
}
```

I wonder if anyone has the interest to get it fixed up? Or perhaps we can see if the [`eslint-plugin-node`](https://github.com/mysticatea/eslint-plugin-node) folks want to adopt it.

2. It's the only rule from `eslint-plugin-standard` that we're currently using. See https://github.com/standard/eslint-config-standard/blob/05f6c64da7da67efe6638265e441cf43cb2d66fe/eslintrc.json#L209 If we remove it, we can get out of the eslint plugin maintenance business. It was something I was hoping to do (see https://github.com/standard/standard/issues/1316) just to eliminate a dependency, but it's not super important to do so.

**Comment by mightyiam** [comment]
Back in July 2016, @feross [wrote](https://github.com/standard/eslint-plugin-standard/issues/12#issuecomment-234711211):

> Yeah, I think this is a good idea. I like your list of callback, cb, and next. However, there's definitely a chance that there might be lots of false positives, but let's give it a try!

I would not mind if this rule is removed.

**Comment by feross** [comment]
I opened an issue asking if ESLint wants to adopt `no-callback-literal` so we can deprecate `eslint-plugin-standard`: https://github.com/mysticatea/eslint-plugin-node/issues/178

If they adopt it, then we can just keep the rule enabled. It's been around for a long time and as folks continue to switch to async-await, I see this becoming more of a non-issue.

Although, maybe as folks migrate Node.js-style callbacks to async-await, more of the remaining callback cases will be false positives like what we've seen in this thread?

@LinusU do you have thoughts?

**Comment by LinusU** [comment]
> If they adopt it, then we can just keep the rule enabled.

I think this is a good approach.

> It's been around for a long time and as folks continue to switch to async-await, I see this becoming more of a non-issue.

Yeah

I've personally never been bit by a false positive here, but I have seen many example of bad code that this rule would have prevented.

All in all, I would prefer to have it enabled but don't feel super strongly about it ☺️

**Comment by feross** [comment]
`eslint-plugin-node` seems supportive of the idea, so I sent a PR: https://github.com/mysticatea/eslint-plugin-node/pull/179

**Comment by feross** [comment]
Okay, let's keep the rule for now. Still open to potentially removing it in a few years once async-await has near 100% usage over callbacks.

Feel free to continue discussion, but closing this issue for now.

**Comment by ExtAnimal** [comment]
Does this rule exclude `myObj.callback('opaqueParameter')` ?

My `callback` method legitimately accepts a string.

**Comment by feross** [comment]
`myObj.callback('opaqueParameter')` is allowed. You can test it for yourself here: https://standardjs.com/demo.html

**Comment by nikugogoi** [comment]
> There are a few outstanding problems with this rule:
> 
> 1. It can't handle the spread operator. Here's a minimal example:
> 
> ```js
> module.exports = a
> 
> function a (cb) {
>   cb(...[new Error(''), 1, 2]) // Unexpected literal in error position of callback.
> }
> ```
> 
> I wonder if anyone has the interest to get it fixed up? Or perhaps we can see if the [`eslint-plugin-node`](https://github.com/mysticatea/eslint-plugin-node) folks want to adopt it.
> 

Hi, is this fixed? or is there a separate issue for this? @feross

**Comment by LinusU** [comment]
@nikugogoi doesn't seem like it's been fixed, and I cannot find an open issue. Would you be able to open an issue here?

https://github.com/mysticatea/eslint-plugin-node/issues

**Comment by ajgrover** [comment]
Another case where this rule returns a false positive:

I'm writing an [`async-validator` rule](https://github.com/yiminghe/async-validator#rules) for the browser for use with an `antd` form, and the validator interface expects an array of Error instances. However, the following causes a violation:

```js
function validate(_, value, callback) {
  if (!value) return callback([new Error('Required')])
  callback()
}
```

As mentioned in some of the prior comments, it's possible to get around this rule by renaming the `callback` parameter to `done` or assigning the array to a variable rather than passing it directly. These don't seem like ideal solutions, and given the lack of configuration with this tool and the number of cases where callbacks don't fit the expectation I think it would make sense to remove it.
