### ISSUE TITLE
How to use Standard with TypeScript in Sublime Text 3?

### ISSUE THREAD

**Issue by gaborluk** [standard/standard#1357]
Now that TSLint is deprecated, is there a way to use Standard _and_ TypeScript _and_ SublimeLinter together? Using the docs, I have managed to make [Standard and TypeScript](https://standardjs.com/index.html#typescript), as well as [Standard and SublimeLinter](https://standardjs.com/index.html#sublime-text) play together respectively, but I don't know how to go about integrating all three. Has anyone managed to do it? Your help would be much appreciated.

**Comment by feross** [comment]
This is related to #1283, but I'll leave this issue open in case other users have tips about specifica workaround to get Standard, TypeScript, and Sublime working nicely together.

Eventually, I'd like to improve this experience substantially, but that discussion is happening in #1283.

**Comment by gaborluk** [comment]
Thank you, @feross. I think you may have (partially) misinterpreted my question, which may be my bad, I apologize if I phrased it confusingly. I was looking for a recommended way of making these three work nicely together, in other words, I wasn't (yet) experiencing a particular problem that the participants on #1283 seem to be having.

In any case, I have since figured out a way. So for all of those in my same shoes as I was yesterday, you will need to use ESLint directy, as opposed to Standard which uses it internally. The components you'll need are:

- [eslint-config-standard-with-typescript](https://github.com/standard/eslint-config-standard-with-typescript)
- [SublimeLinter](https://packagecontrol.io/packages/SublimeLinter)
- [SublimeLinter-eslint](https://packagecontrol.io/packages/SublimeLinter-eslint)

The **`eslint-config-standard-with-typescript`** [usage instructions](https://github.com/standard/eslint-config-standard-with-typescript#usage) will give you all the npm dependencies you need. (**Please note:** Since [`@typescript-eslint/eslint-plugin`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin), a dependency of `eslint-config-standard-with-typescript`, has just been updated to version 2.0.0 introducing breaking changes, if you follow the install instructions verbatim from the usage instructions above, you will be experiencing issues. To temporarily circumvent those while support for the new dependency version is added, install `@typescript-eslint/eslint-plugin` at version `1.13.0` instead. All other dependencies are fine at the moment.)

Other than these, you will need an `.eslintrc.json` (as shown in the usage instructions above), and may need a [`tsconfig.json`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html).

SublimeLinter and SublimeLinter-eslint should be straightforward.

**Comment by gaborluk** [comment]
Thank you, @feross. I think you may have (partially) misinterpreted my question, which may be my bad, I apologize if I phrased it confusingly. I was looking for a recommended way of making these three work nicely together, in other words, I wasn't (yet) experiencing a particular problem that the participants on #1283 seem to be having.

In any case, I have since figured out a way. So for all of those in the same shoes as I was in yesterday, you will need to use ESLint directy, as opposed to Standard which uses it internally. The components you'll need are:

- [eslint-config-standard-with-typescript](https://github.com/standard/eslint-config-standard-with-typescript)
- [SublimeLinter](https://packagecontrol.io/packages/SublimeLinter)
- [SublimeLinter-eslint](https://packagecontrol.io/packages/SublimeLinter-eslint)

The **`eslint-config-standard-with-typescript`** [usage instructions](https://github.com/standard/eslint-config-standard-with-typescript#usage) will give you all the npm dependencies you need. (**Please note:** Since [`@typescript-eslint/eslint-plugin`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin), a dependency of `eslint-config-standard-with-typescript`, has just been updated to version 2.0.0 introducing breaking changes, if you follow the install instructions verbatim from the usage instructions above, you will be experiencing issues. To temporarily circumvent those while support for the new dependency version is added, install `@typescript-eslint/eslint-plugin` at version `1.13.0` instead. All other dependencies are fine at the moment.)

Other than these, you will need an `.eslintrc.json` (as shown in the usage instructions above), and may need a [`tsconfig.json`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html).

SublimeLinter and SublimeLinter-eslint should be straightforward.

**Comment by mightyiam** [comment]
@gaborluk, I've just opened https://github.com/standard/eslint-config-standard-with-typescript/issues/123.

**Comment by gaborluk** [comment]
Good idea, @mightyiam.

**Comment by feross** [comment]
@mightyiam Can this issue be closed now?
