### ISSUE TITLE
Require JSX closing tag to be aligned with the opening tag (react/jsx-closing-tag-location)

### ISSUE THREAD

**Issue by feross** [standard/standard#1358]
This rule checks all JSX multiline elements with children (non-self-closing) and verifies the location of the closing tag. The expectation is that the closing tag is aligned with the opening tag on its own line.

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-tag-location.md

The following patterns are considered warnings:

```
<Hello>
  marklar
  </Hello>
```

```
<Hello>
  marklar</Hello>
```

The following are not considered warnings:

```
<Hello>
  marklar
</Hello>
```

```
<Hello>marklar</Hello>
```

**Comment by feross** [comment]
I know this is not controversial so I am going to ship it in `standard` 14.

**Comment by MatanBobi** [comment]
@feross Doesn't this collide with indent/jsx-indent rule?

**Comment by feross** [comment]
@MatanBobi I don't believe so. Can you explain how?

**Comment by joke2k** [comment]
@feross I think that @MatanBobi means using non-self-closing tag with return:
```
  render () {
    return <div>
      Closing tag below where should be?
    </div>
  }
```
With this rule, this style raises an error (not aligned to open tag) and if I try to `--fix` it:

```
  render () {
    return <div>
      Closing tag below where should be?
           </div>
  }
```
which raises `react/jsx-indent-problem` and is ugly.

The only way to fix it is putting all in one line:
```
  render () {
    return <div>Closing tag below where should be?</div>
  }
```
but is not really sustainable.

**Comment by feross** [comment]
@joke2k The intended style is to add parens anytime you have a multiline JSX statement.

```js
  render () {
    return (
      <div>
        Closing tag below where should be?
      </div>
    )
  }
```

I'm not sure why the autofixer isn't doing that for you. Looks like we need to play with the JSX rules some more to get what we want.

**Comment by feross** [comment]
Re-opening so we can investigate fixing this for `standard` 15. Help wanted!

**Comment by MatanBobi** [comment]
@joke2k You got exactly what I meant, thanks for the wide explanation.

**Comment by davidystephenson** [comment]
> @joke2k The intended style is to add parens anytime you have a multiline JSX statement.

This doesn't seem to match the `jsx-closing-tag-location` documentation. As you acknowledge in your first post, it says: 

> The following are not considered warnings:
> 
>     <Hello>
>       marklar
>     </Hello>

No parentheses are shown.

**Comment by feross** [comment]
I believe this is fixed in `standard` 16.
