### ISSUE TITLE
Standard cannot parse React JSX files

### ISSUE THREAD

**Issue by evantahler** [standard/standard#1359]
**What version of this package are you using?**
13.1.0

**What operating system, Node.js, and npm version?**
Node v12
OSX (latest)

**What happened?**
Take a simple react JSX file (from: https://reactjs.org/docs/hooks-intro.html)

```jsx
import React, { useState } from 'react'

function IndexPage () {
  const [count, setCount] = useState(0);

  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>
        Click me
      </button>
    </div>
  )
}

export default IndexPage
```

However, Standard cannot parse the file and thinks the `{` is not valid JSX:

```
> standard

standard: Use JavaScript Standard Style (https://standardjs.com)
  /Users/evan/workspace/evantahler.com/pages/index.js:8:22: Parsing error: Unexpected token {
```

This seems to be a new type of bug.

**What did you expect to happen?**
Valid JS and Standard not to crash

**Are you willing to submit a pull request to fix this bug?**
Sure!

**Comment by feross** [comment]
I cannot reproduce this issue. Indeed, the demo site shows it works just fine: https://standardjs.com/demo.html?gist=ff5832e447327defb72164f9e245bd4a

My guess is that you're pulling in an old version of standard (perhaps install globally?)

Can you share the output of: 

- `standard --version`
- `npm ls standard`

Thanks!

**Comment by evantahler** [comment]
First off, that demo site using a Gist is awesome!

I created a small demo project that uses Next.JS, Jest and Standard... and it works fine.  There must be something else in my main project getting in the way... sorry to bother you! 

Example Project: https://github.com/evantahler/react-next-standard-test

**Comment by feross** [comment]
Weirdly, I just ran into this issue on one my sites. Here's the build failure: https://travis-ci.org/feross/play.cash/builds/572130278?utm_source=github_status&utm_medium=notification

@evantahler Did you ever figure out the cause? Downgrading to standard@12 fixes the issue for me.

**Comment by feross** [comment]
Oh sheesh, it's a bug in `npm`. Life is too short for this...

> npm doesn't seem to install dependencies correctly if a package which has a name before eslint in the alphabet order and has old acorn in their dependencies list....

It looks like this is a workaround: `rm -rf node_modules && npm install --legacy-bundling`

Related issues:

- https://github.com/eslint/espree/issues/393
- https://github.com/eslint/eslint/issues/11018

**Comment by mightyiam** [comment]
I'll take your word for it :rofl:

**Comment by evantahler** [comment]
@feross Yes! That's great detective work.  

I *had* an old version of Acorn in some projects, and I started re-installing deps 1-by-1 until it worked... and the working build lacks a top-level acorn requirement.

**Comment by evantahler** [comment]
It looks like for some projects, this is still a problem (see this upgrade and test suite) https://github.com/actionhero/www.actionherojs.com/pull/63

**Comment by feross** [comment]
@evantahler The newest version of `babel-eslint` attempted to resolve this issue. Can you try updating `standard` and `babel-eslint` and try this again?

**Comment by evantahler** [comment]
no luck... similar problems... running `npm install --legacy-bundling` gets standard to install and run properly, but then some of the babel plugins don't get installed.

**Comment by feross** [comment]
I think with the `babel-eslint` changes, it shouldn't be necessary to use `--legacy-bundling` anymore since they're using the exact dependencies installed by `eslint`.

Can you confirm you're using `babel-eslint` 10.0.3 and `standard` 14.1.0? You can check with `npm ls babel-eslint` and `npm ls standard`.

**Comment by evantahler** [comment]
Huh! now that's curious... `babel-eslint` isn't in the manifest at all.  I'm still getting those JSX parsing errors (`Parsing error: Unexpected token /`)
```
❯ npm ls standard
www.actionherojs.com@0.0.2 /Users/evan/workspace/actionhero/www.actionherojs.com
└── standard@14.1.0

❯ npm ls babel-eslint
www.actionherojs.com@0.0.2 /Users/evan/workspace/actionhero/www.actionherojs.com
└── (empty)
```

I've pushed everything to a branch here https://github.com/actionhero/www.actionherojs.com/tree/standard-v14.

Just on a whim, I tried using yarn... and I'm getting the same parsing errors. 
I added `babel-eslint` explicitly as a dev-dependancy, and that didn't fix it either

**Comment by feross** [comment]
You need to `npm install babel-eslint` and also add `"parser": "babel-eslint"` to the "standard" field in your `package.json`. That fixed it for me in the repo you linked.

**Comment by evantahler** [comment]
Thanks for all the help!

I see some docs about this here (https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features), but I don't *think* I'm using any of the special new language features (and it worked pre standard v14)... but this is a path forward for now!  Thank you again!

**Comment by feross** [comment]
I believe that you are using class field declarations, which are still a stage 3 feature: https://github.com/tc39/proposal-class-fields Weird that it worked before though.
