### ISSUE TITLE
Require JSX closing bracket to be aligned with the opening tag (react/jsx-closing-bracket-location)

### ISSUE THREAD

**Issue by feross** [standard/standard#1361]
This rule checks all JSX multiline elements and verifies the location of the closing bracket. By default this one must be aligned with the opening tag.

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md

```js
// ok
<Hello
  firstName="John"
  lastName="Smith"
/>;

// ok
<Say
  firstName="John"
  lastName="Smith"
>
  Hello
</Say>;

// ok
var x = (
  <Hello
    firstName="John"
    lastName="Smith"
  />
)

// ok
var x = function() {
  return (
    <Say
      firstName="John"
      lastName="Smith"
    >
      Hello
    </Say>
  )
}

// not ok
<Hello
  firstName="John"
  lastName="Smith"
  />;

// not ok
<Say
  firstName="John"
  lastName="Smith">
  Hello
</Say>;
```

**Comment by feross** [comment]
This codifies my personal style preference. I prefer the parallelism and how the alignment makes it really clear where the tag ends. Using this style already on bitmidi.com and webtorrent-deskop.

Shipping in `standard` 14.

**Comment by Zmeu213** [comment]
This rule is awful, I presonally hate it. This is the only reason i prefer not to use standard anymore. its doesnt make code cleaner but annoys you and force to make extra linebreaks
coz this is better
```js
<div style={{
  someMultiLineStyleConfig: 'exists'
}}>
```
than this 
```js
<div style={{
  someMultiLineStyleConfig: 'exists'
}}
>
```

**Comment by LinusU** [comment]
> This rule is awful

I agree that it's wrong in the one specific case that you outlined, but to say that the entire rules is awful is a bit much 😂 

My personal preference is that the following should be disallowed:

```
<div style={{
  someMultiLineStyleConfig: 'exists'
}}
>
```

@Zmeu213 could you check how that could be configured, and submit a pull request?

**Comment by Zmeu213** [comment]
oh yea, looks like i forgot that this is open-source and I can help make it better myself instead of writing angry comments :)

Sure, i'll take a look
