### ISSUE TITLE
Require shorthand form for JSX fragments (react/jsx-fragments)

### ISSUE THREAD

**Issue by feross** [standard/standard#1364]
In JSX, a React fragment is created either with <React.Fragment>...</React.Fragment>, or, using the shorthand syntax, <>...</>. This rule allows you to enforce one way or the other.

It will enforce the shorthand syntax for React fragments, with one exception. [Keys or attributes are not supported by the shorthand syntax][short_syntax], so the rule will not warn on standard-form fragments that use those.

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md

The following pattern is considered a warning:

```jsx
<React.Fragment><Foo /></React.Fragment>
```

The following patterns are **not** considered warnings:

```jsx
<><Foo /></>
```

```jsx
<React.Fragment key="key"><Foo /></React.Fragment>
```

**Comment by feross** [comment]
Shipping this in `standard` 14.

**Comment by AlvMF1** [comment]
Any option (at least to use with --fix) to ignore this one? It breaks babel's official syntax highlighting on Sublime Text 3... 😢

**Comment by feross** [comment]
@AlvMF1 I'm sorry to hear that it breaks the syntax highlighting in Sublime (I'm a Sublime user too). But it's definitely cleaner code and hopefully the syntax highlighter will be updated. Have you filed an issue with the right folks to get it fixed?

**Comment by AlvMF1** [comment]
@feross, there's already an issue there, but looks like the project is abandoned... Thanks, anyways.
