### ISSUE TITLE
Require PascalCase for user-defined JSX components (react/jsx-pascal-case)

### ISSUE THREAD

**Issue by feross** [standard/standard#1365]
Enforces coding style that user-defined JSX components are defined and referenced in PascalCase.

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-pascal-case.md

The following patterns are considered warnings:

```jsx
<Test_component />
```

```jsx
<TEST_COMPONENT />
```

The following patterns are **not** considered warnings:

```jsx
<div />
```

```jsx
<TestComponent />
```

```jsx
<TestComponent>
  <div />
</TestComponent>
```

```jsx
<CSSTransitionGroup />
```

**Comment by feross** [comment]
Shipping in `standard` 14.

**Comment by Johnny-Brendow** [comment]
if you got here, because you saw a warning like this "the imported jsx component must be in pascalcase"
you should know that some things don't accept accents , you may try to write 
InPascalCase instead InPáscalCâsé

**Comment by BlaineBradbury** [comment]
Ditto for underscores... can't have those either.  Thanks to the prior comment for giving me a clue.

**Comment by RomanRiezanov** [comment]
> So here underscore('_') in the component name is the culprit for the warning................

Thanks)
