### ISSUE TITLE
ESLint bug workaround for Indentation on template literal children is not working as expected

### ISSUE THREAD

**Issue by auggod** [standard/standard#1385]
Related issue:  #1176

The work around did not fix the issue for me. Linter was still reporting indent errors
Below, I removed `>` before `*`
`"ignoredNodes": ["TemplateLiteral *"]`
This now works as expected.
I also found some explanation here: https://stackoverflow.com/a/54958527

**Comment by feross** [comment]
Thanks for the bug report. This is fixed in `standard` 14.0.2.
