### ISSUE TITLE
standard does not respect .gitignore

### ISSUE THREAD

**Issue by edosrecki** [standard/standard#1386]
**What version of this package are you using?**
14.0.2

**What operating system, Node.js, and npm version?**
macOS v10.13.6
Node.js v10.16.3
npm v6.9.0

**What happened?**
standard processes files and directories which are specified in `.gitignore`.

After upgrading from `v13.1.0` to `v14.0.x`, standard command starts failing since it processes the `dist/` directory which is listed in `.gitignore`. Behaviour is same not only for directories, but also for files specified in `.gitignore`.

Ignoring the files/directories in `package.json` fixes the issue.

**What did you expect to happen?**
standard should ignore files and directories specified in `.gitignore`.

**Are you willing to submit a pull request to fix this bug?**
Perhaps. :)

**Comment by feross** [comment]
You're right. I just confirmed this is a bug.

**Comment by feross** [comment]
This is fixed in `deglob` 4.0.1. If you reinstall `standard` (and potentially your `package-lock.json` file), this should be fixed!
