### ISSUE TITLE
Fix on save from ale syntax checker is not working since 13.1.0

### ISSUE THREAD

**Issue by auggod** [standard/standard#1390]
**What version of this package are you using?**

I've experienced this issue on 13.1.2 and it's still there on 14.x.
12.x is working fine.

**What operating system, Node.js, and npm version?**

- Macos
- Node v12.8.0
- NPM 6.10.2

**What happened?**

While lint errors are displayed correctly, fix on save is not working. I've checked that both settings are enabled.

Vim and ALE are up to date. From cli, `standard --fix` is working.
I'm using the exact same config as shown in readme: https://github.com/standard/standard#vim

**What did you expect to happen?**

Fix on save and `:ALEFix` should be working.

**Are you willing to submit a pull request to fix this bug?**

I have yet to find where the issue comes from. Maybe it's not a standard issue.
Maybe this issue is related: https://github.com/dense-analysis/ale/issues/897

**Comment by theimpostor** [comment]
This is likely the same issue as #1384.

**Comment by feross** [comment]
The issue @theimpostor linked #1384 has been fixed in `standard` 16.

@auggod @theimpostor Can you confirm if this issue is fixed for you?
