### ISSUE TITLE
No prototype builtins rule

### ISSUE THREAD

**Issue by JShep89** [standard/standard#1403]
**What version of this package are you using?**
6.3.0
**What operating system, Node.js, and npm version?**
Windows, node v9, NPM v5.5.1
**What happened?**
Issue with no-prototype-builtins rule, can't find an explanation on how to convert this: (status && statusMap.hasOwnProperty(status) && writable)

*What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by feross** [comment]
> **What version of this package are you using?**
> 6.3.0

I think this might be a mistake. `standard` 6 is ancient! We're on `standard` 14 at the moment and the `no-prototype-builtins` rule was added in 13.

Incorrect:

```js
statusMap.hasOwnProperty(status)
```

Correct:

```js
Object.prototype.hasOwnProperty.call(statusMap, status)
```

You can read more about the justification for this rule here: https://eslint.org/docs/rules/no-prototype-builtins

**Comment by JShep89** [comment]
I may have opened the issues in the wrong branch. So the correct way to
convert this:
(status && statusMap.hasOwnProperty(status) && writable),
would be this:
(Object.prototype.hasOwnProperty.call(statusMap, status))?

But what about the first status and the writable?

**Comment by feross** [comment]
You need to include those too.

```js
(status && Object.prototype.hasOwnProperty.call(statusMap, status) && writable)
```

**Comment by feross** [comment]
Ahh, I think you're using ESLint 6.3.0. You opened this issue on the repo of a different project, called StandardJS or `standard`, which uses ESLint under the hood. Anyway, hope this advice was helpful, nonetheless.
