### ISSUE TITLE
Declaring a function inside a try/catch prohibited by "no-inner-declaration"

### ISSUE THREAD

**Issue by davidystephenson** [standard/standard#1406]
I find myself wanting to create a function inside a `try`/`catch` block. For example:

```
async function uploadImages () {
  const profileUrl = buildProfileUrl()

  const picturesUrl = buildPicturesUrl()

  try {
    const profile = await getProfile(profileUrl)

    const pictures = await getPictures(picturesUrl)

    async function upload (picture) {
      return uploadImage({ profile, picture })
    }

    const promises = pictures.map(upload)
    
    return Promise.all(promises)
  } catch (error) {
    throw error
  }
}
```

I want to declare `upload` inside the `try` so I can take advantage of `profile` being in scope. However, this apparently violates the `no-inner-declarations` rule.

Can someone explain why this rule is important here? Should `no-inner-declaration` perhaps not apply to `try`/`catch`?

**Comment by feross** [comment]
You can fix this by making your `upload` function into an expression instead.

```js
const upload = async function (picture) {
  return uploadImage({ profile, picture })
}
```

However, this raises a good point. Now that ES6 has shipped everywhere, [block-scoped functions](https://bugzilla.mozilla.org/show_bug.cgi?id=585536) are supported widely. Perhaps we can disable this rule now? Anyone have thoughts?

**Comment by mightyiam** [comment]
It seems that indeed functions should be allowed. [From the rule docs](https://eslint.org/docs/rules/no-inner-declarations#when-not-to-use-it):

> The function declaration portion rule will be rendered obsolete when block-scoped functions land in ES6, but until then, it should be left on to enforce valid constructions.

Regarding variables, perhaps we should allow them as well and so disable this rule and enable [`block-scoped-var`](https://eslint.org/docs/rules/block-scoped-var), instead?

> Disable checking variable declarations when using block-scoped-var or if declaring variables in nested blocks is acceptable despite hoisting.

**Comment by feross** [comment]
> Regarding variables, perhaps we should allow them as well 

Variables are allowed. This rule is set to only prevents function declarations.

> re: block-scoped-var

I'd like to move to `const`/`let` only so that eliminated the need for such a rule. #633

**Comment by mightyiam** [comment]
Thank you for the clarifications, @feross.

Then, it seems to be clear that we just drop this rule and enable `no-var`, right?

**Comment by feross** [comment]
Yep.

**Comment by ZhangQian-Cheryl** [comment]
![Uploading 心经.jpg…]()

**Comment by feross** [comment]
This will ship in standard v15.
