### ISSUE TITLE
Report on no errors

### ISSUE THREAD

**Issue by PaulBags** [standard/standard#1410]
Hi, I'd like to see _something_ on a successful test with no errors. A a list of files would be great, but even just "yip you ran a test and it was successful" would do. I need to show _something_.

Only related issue I could see was this: https://github.com/standard/standard/issues/120 , and, I have no idea if it's related.

**Comment by mightyiam** [comment]
Hey, @PaulBags. If standard exits with 0 after encountering errors, that's a super critical bug. Could you please provide a screenshot that demonstrates that?

**Comment by PaulBags** [comment]
On closer inspection that seems to be a windows problem, tacking on '& echo %errorlevel%' is showing the _previous_ error level and not the error level of the command just run. Running it again with clean code gave me an error code of 1! Then 0s thereafter.

This is why I'd rather get my proof from standard itself. I solved my problem with npm run lint and chucking a timestamp in after, which I added to my test while I was at it. I'd still rather hear it from the horses mouth.

**Comment by PaulBags** [comment]
Hmm. It does seem that standard && echo success will echo success every time, despite && being conditional on exit 0. %errorlevel% is being reported as 1 afterwards, but it seems it can't be caught inline.

This might be a node.js issue?

![image](https://user-images.githubusercontent.com/19583196/64852336-4c379080-d66d-11e9-9f15-a322d7776ec1.png)

This is reproducible every time for me.

**Comment by mightyiam** [comment]
@PaulBags how about in [PowerShell](https://docs.microsoft.com/en-us/powershell/)?
