### ISSUE TITLE
Disallow assigning to imported bindings (no-import-assign)

### ISSUE THREAD

**Issue by feross** [standard/standard#1412]
https://eslint.org/docs/rules/no-import-assign

The updates of imported bindings by ES Modules cause runtime errors.

## Rule Details

This rule warns the assignments, increments, and decrements of imported bindings.

Examples of **incorrect** code for this rule:

```js
/*eslint no-import-assign: "error"*/

import mod, { named } from "./mod.mjs"
import * as mod_ns from "./mod.mjs"

mod = 1          // ERROR: 'mod' is readonly.
named = 2        // ERROR: 'named' is readonly.
mod_ns.named = 3 // ERROR: the members of 'mod_ns' is readonly.
mod_ns = {}      // ERROR: 'mod_ns' is readonly.
```

Examples of **correct** code for this rule:

```js
/*eslint no-import-assign: "error"*/

import mod, { named } from "./mod.mjs"
import * as mod_ns from "./mod.mjs"

mod.prop = 1
named.prop = 2
mod_ns.named.prop = 3

// Known Limitation
function test(obj) {
    obj.named = 4 // Not errored because 'obj' is not namespace objects.
}
test(mod_ns) // Not errored because it doesn't know that 'test' updates the member of the argument.
```

**Comment by mightyiam** [comment]
I'm pro this rule. Disallows code that should probably never be written.

Regarding the limitation: it seems like with TypeScript that would be possible to prevent as well.

**Comment by feross** [comment]
Only 1 failing ecosystem repo. This is the code:

```js
import '../../../polyfill'

import fetch, * as ponyfill from '../../..'
import addModuleSuite from '../../module.spec'

ponyfill.defaultExport = fetch

addModuleSuite('Browser: import on Webpack bundle', ponyfill)
```

Seems easy enough for them to add an `// eslint-ignore` comment when doing something hacky like this. Otherwise, this is a good rule.

This will ship in standard 16!
