### ISSUE TITLE
Disallow spaces inside of computed keys of class methods, getters and setters (computed-property-spacing)

### ISSUE THREAD

**Issue by feross** [standard/standard#1416]
https://eslint.org/docs/rules/computed-property-spacing

Current rule:

```
"computed-property-spacing": ["error", "never"],
```

Proposed rule:

```
"computed-property-spacing": ["error", "never", { "enforceForClassMembers": true }],
```

By default, this rule does not check class declarations and class expressions,
as the default value for `enforceForClassMembers` is `false`.

When `enforceForClassMembers` is set to `true`, the rule will also disallow/enforce spaces inside of computed keys of class methods, getters and setters.

Examples of **incorrect** code for this rule with `"never"` and `{ "enforceForClassMembers": true }`:

```js
/*eslint computed-property-spacing: ["error", "never", { "enforceForClassMembers": true }]*/

class Foo {
  [a ]() {}
  get [b ]() {}
  set [b ](value) {}
}

const Bar = class {
  [ a](){}
  static [ b]() {}
  static get [ c ]() {}
  static set [ c ](value) {}
}
```

Examples of **correct** code for this rule with `"never"` and `{ "enforceForClassMembers": true }`:

```js
/*eslint computed-property-spacing: ["error", "never", { "enforceForClassMembers": true }]*/
/*eslint-env es6*/

class Foo {
  [a]() {}
  get [b]() {}
  set [b](value) {}
}

const Bar = class {
  [a](){}
  static [b]() {}
  static get [c]() {}
  static set [c](value) {}
}
```

**Comment by mightyiam** [comment]
All in, of course. BTW, this is another example where ESLint is getting closer to the level of prettier. I know it's quite far and has a long way to go in that regard, but still... personally, for me, it's close enough. And since it keeps getting better (if the available rules are used) then I'm happy with it.

**Comment by feross** [comment]
No ecosystem failures!

This will ship in standard 16.
