### ISSUE TITLE
Enforce conditional expression styles

### ISSUE THREAD

**Issue by mightyiam** [standard/standard#1424]
The conditional expression can use some decisions regarding where lines are broken and where indentation is placed, I feel. For example, the following different styles are currently possible:

```js
/* global env */
const prefix =
      env === 'prod' ? ''
        : env === 'local' ? 'local-'
          : 'dev-'

console.log(prefix)
```

This, as well:
```js
/* global env */
const prefix =
      env === 'prod'
        ? ''
        : env === 'local'
          ? 'local-'
          : 'dev-'

console.log(prefix)
```

The way I see it, we already allow too many different styles. Ideally, according to the mission of StandardJS, we'd decide on a certain style and enforce it.

Ternary expressions seem a bit complicated in terms of possibilities of where to place the line breaks and how much to indent in which case. And I don't know whether we have the theory of that figured out. I assume @feross has his own habits.

I think a good first task would be to break down the various options into a list and post it here, with examples.

The Conditional Expression has the following syntax:
![Screenshot from 2019-09-26 09-29-04](https://user-images.githubusercontent.com/635591/65653612-254f6600-e040-11e9-91c5-2fd16186590b.png)

Simplified: `condition ? then : else`
These 5 parts:
1. `condition`
2. `?`
3. `then`
4. `:`
5. `else`

If we are to solve the styling of the ternary, perhaps we should first limit the ternary in some ways, using the #1422 plugin. That way, we have less things to think about in the scope of line breaks and indentation. So, I'm going to mark this as blocked by #1422.

**Comment by Alexsey** [comment]
Both provided examples looks good depends on parts length: use first when `condition` and `then` are short and use second if `condition` and `then` are long so you want to split them in to separate lines, so it would be easier to read. The same logic as for any other binary operator e.g. `||`:
```
const a = foo || getA()
```
```
const b = await (Promise.all(bar.map(fetch).find(v => v % 15)) ||
  generateBValueFunctionWithVeryLongName())
```

**Comment by feross** [comment]
I shipped a rule in `standard` 16 which enforces ternary formatting. See: https://github.com/standard/standard/issues/1558

The two accepted styles are:

```js
cond
  ? a
  : b

cond ? a : b
```
