### ISSUE TITLE
Unnecessary escape character false possitive

### ISSUE THREAD

**Issue by dbolton** [standard/standard#1426]
**What version of this package are you using?**
npx standard
also the linter-js-standard plugin for Atom

**What operating system, Node.js, and npm version?** 
Windows 10
Node 10.16.3
npm 6.9.0

**What happened?** 
The code `var test = /[\]\[]/` produces two errors:
Unnecessary escape character: \\[.
Unnecessary escape character: \\].

**What did you expect to happen?**
There should be no error messages. This is not a matter of style. Taking out the escape character produces a very different result in JavaScript.

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by mightyiam** [comment]
@dbolton thank you for your report. Under the hood, Standard uses ESLint. And this seems like the following rule:
https://eslint.org/docs/rules/no-useless-escape

Could you please [report this upstream](https://eslint.org/docs/developer-guide/contributing/reporting-bugs)? By the way, I don't know regular expressions well, so I did not confirm that this is a bug indeed.

**Comment by mightyiam** [comment]
Thank you for following through, @dbolton.
