### ISSUE TITLE
async and get always end up as asyncget during onSave lint using StandardJS

### ISSUE THREAD

**Issue by gjovanov** [standard/standard#1428]
**What version of this package are you using?**
"standard": "^14.3.1",

**What operating system, Node.js, and npm version?**
Win10, Node v12.2.0, npm v6.9.0

**What happened?**

Within VSCode, which has configured onSave to lint using StandardJS based on package.json (non-global), for the code below it always concatenates `async` and `get` as `asyncget`

```javascript
export const actions = {
   async get({
    commit,
    state
  }, id) {
    const response = {}
    try {
      response.result = await this.$axios.$get(`/api/room/get?id=${id}`)
    } catch (err) {
      handleError(err, commit)
      response.hasError = true
    }
    return response
  },
}
```
turns into:
```javascript
export const actions = {
   asyncget({
    commit,
    state
  }, id) {
    const response = {}
    try {
      response.result = await this.$axios.$get(`/api/room/get?id=${id}`)
    } catch (err) {
      handleError(err, commit)
      response.hasError = true
    }
    return response
  },
}
```

This only happens for combination `async` and `get`. If the method is called `Get` or any other name, this weird concatenation doesn't happen

**What did you expect to happen?**

It should not concatenate thos two keywords.

**Are you willing to submit a pull request to fix this bug?**

Not sure how to fix this

**Comment by mightyiam** [comment]
@gjovanov thank you for the report.

Could you please check something for me?

I'd like to ask you to try and see whether `standard --fix` results in the same malformed code.

**Comment by feross** [comment]
Another thing for us to test: does updating to the latest eslint (within `standard`) fix the issue?

**Comment by gjovanov** [comment]
Hi @mightyiam and @feross ,
`standard --fix` doesn't produce this issue.

eslint was already to it latest version.

Here is the .eslintrc.js file:
```javascript
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  parserOptions: {
    parser: 'babel-eslint'
  },
  plugins: ['import', 'standard'],
  extends: ['@nuxtjs', 'plugin:nuxt/recommended', 'standard'],
  // add your custom rules here
  rules: {
    'nuxt/no-cjs-in-config': 'off',
    'no-console': 'off'
  }
}
```

Here is the VS workspace config I'm using (wspace.conde-workspace):
```javascript
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
    "files.eol": "\n",
    "editor.formatOnPaste": false,
    "javascript.validate.enable": false,
    "eslint.validate": [{
        "language": "vue",
        "autoFix": true
      },
      {
        "language": "html",
        "autoFix": true
      },
      {
        "language": "javascript",
        "autoFix": true
      }
    ],
    "files.autoSave": "off",
    "standard.autoFixOnSave": true,
    "terminal.integrated.windowsEnableConpty": false,
    "standard.usePackageJson": true,
    "standard.run": "onSave"
  }
}
```

And here are the package.json versions:
```javascript
{
  ...
  "standard": {
    "env": [
      "browser",
      "node"
    ],
    "ignore": [
      "ui/lib/**/*.js"
    ]
  },
  "devDependencies": {
    ...
    "@babel/core": "^7.6.0",
    "@babel/preset-env": "^7.6.0",
    "@babel/register": "^7.6.0",
    "@nuxtjs/eslint-config": "^1.1.2",
    "@nuxtjs/eslint-module": "^1.0.0",
    "babel-eslint": "^10.0.3",
    "babel-plugin-istanbul": "^5.2.0",
    "eslint": "^6.5.1",
    "eslint-config-standard": "^14.1.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-node": ">=10.0.0",
    "eslint-plugin-nuxt": ">=0.4.3",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": ">=4.0.1",
    "eslint-plugin-vue": "^5.2.3",
    "standard": "^14.3.1"
    ...
  }
}
```

Maybe you see something that I'm doing wrong?

Thanks.

**Comment by mightyiam** [comment]
@gjovanov thank you for the input. Could you please try to run `npx eslint --fix that-file.js` on a file that has that `async get` that gets wrongly autofixed in VSCode? I'd like to know whether the wrong auto-fix would be applied. If it did get applied, could you try again after having removed `'standard'` from the `extends` of the ESLint config?

**Comment by gjovanov** [comment]
Hey everyone, I tried that but it didn't produce reported issue. This made me suspect that the issue is not related to StandardJS/ESLint.

Basically, I had many VSCode extensions installed (with formatting options) and started to clean them up one by one. And disabled default JS/TS formatter

At the end, it seems that when I removed ESList extension, the issue wasn't happening, but neither formatting was happening. After enabling ESLint extension (with default JS/TS formatter being disabled), the issue has disappeared.

So a lot of smoke for nothing.
Sorry about that. And thanks for your responsiveness!

Closing...

**Comment by mightyiam** [comment]
Thank you for following through, @gjovanov.

**Comment by ymc-stewart-ridgway** [comment]
For me, this exact same issue was caused by another plugin called Prettier. Disabling the plugin removed the issue.

**Comment by ymc-stewart-ridgway** [comment]
For me, the plugin responsible was "JS-CSS-HTML Formatter".

**Comment by EdgarAlonsoPerez** [comment]
i had the same problem, and as @ymc-stewart-ridgway said the responsible was "JS-CSS-HTML Formatter"
