### ISSUE TITLE
'BigInt' is not defined.

### ISSUE THREAD

**Issue by LinusU** [standard/standard#1436]
**What version of this package are you using?**

`14.3.1`

**What operating system, Node.js, and npm version?**

macOS 10.14.6
Node.js 12.10.0
npm 6.11.3

**What happened?**

I had the following code:

```js
buffer.writeBigUInt64LE(BigInt(createdAt.getTime()), 0)
```

Got the following error:

```text
'BigInt' is not defined.
```

This was mentioned as fixed in 14.1.0 here: https://github.com/standard/standard/issues/1378#issuecomment-526394449

**What did you expect to happen?**

No error

**Are you willing to submit a pull request to fix this bug?**

Yes

**Comment by feross** [comment]
This will be fixed in standard v15.
