### ISSUE TITLE
standard will timeout and stack trace when node_modules have too many files

### ISSUE THREAD

**Issue by zhangyuang** [standard/standard#1438]
**What version of this package are you using?**
12.0.1
**What operating system, Node.js, and npm version?**
node v10.6.0
**What happened?**
my folder have many child folders, and have many node_modules, when i run standard,after a while, it timeout and track trace although it not test node_modules。 when i delete all node_modules, it can be normal
**What did you expect to happen?**
don't timeout
**Are you willing to submit a pull request to fix this bug?**
![image](https://user-images.githubusercontent.com/17424434/66394194-091bd380-ea07-11e9-8f0b-b8b77c88858a.png)

**Comment by feross** [comment]
This is fixed in `standard` 16 because we removed the `deglob` package.

**Comment by feross** [comment]
See: https://github.com/standard/standard-engine/pull/228
