### ISSUE TITLE
Error: Failed to load plugin 'react' declared in '--config » eslint-config-standard-jsx': Cannot find module 'eslint-plugin-react' when trying to use standard with PhpStorm

### ISSUE THREAD

**Issue by oneserv-heuser** [standard/standard#1443]
**What version of this package are you using?**
14.3.1 (global installation)

**What operating system, Node.js, and npm version?**
Windows 10 Pro Build 18362.19h1
PhpStorm 2019.2.3
Node.js 12.6.0
Npm 6.9.0

**What happened?**
When trying to use Standard as Code Quality Tool in PhpStorm according [to this manual](https://www.jetbrains.com/help/webstorm/eslint.html#ws_js_linters_eslint_using_JavaScript_Standard_Style) the following error occurs:

```
Error: Failed to load plugin 'react' declared in '--config » eslint-config-standard-jsx': Cannot find module 'eslint-plugin-react'
```

The error occurs after finishing the setup and opening a .js file. There is no examination of the code.

Standard is globally installed via npm as the project i'm trying to use it in as Code Quality Tool is not a node project (and theres no react or sth. like this installed). I just want to check normal .js-files with Standard.

**What did you expect to happen?**
I did except Standard to examinate my code.

Other bug tickets or googling was not helpful.
Installing the desired modules also doesn't help.

**Below is the entire console output:**

```
Error: Failed to load plugin 'react' declared in '--config » eslint-config-standard-jsx': Cannot find module 'eslint-plugin-react'
Require stack:
C:\Users\heuser\PhpstormProjects\DASHBOARD_bueromoebel_experte\__placeholder__.js

Error: Failed to load plugin 'react' declared in '--config » eslint-config-standard-jsx': Cannot find module 'eslint-plugin-react'
Require stack:
C:\Users\heuser\PhpstormProjects\DASHBOARD_bueromoebel_experte\__placeholder__.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.resolve (internal/modules/cjs/helpers.js:21:19)
    at Object.resolve (C:\Users\heuser\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\shared\relative-module-resolver.js:44:50)
    at ConfigArrayFactory._loadPlugin (C:\Users\heuser\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\cli-engine\config-array-factory.js:845:39)
    at C:\Users\heuser\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\cli-engine\config-array-factory.js:734:33
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (C:\Users\heuser\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\cli-engine\config-array-factory.js:730:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (C:\Users\heuser\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\cli-engine\config-array-factory.js:554:32)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (C:\Users\heuser\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\cli-engine\config-array-factory.js:491:20)
Process finished with exit code -1
```

**Comment by mightyiam** [comment]
Thank you @oneserv-heuser, for using Standard.

Could you please run `npm -g ls eslint-plugin-react` and paste the output here? When pasting, could you please use a [code block](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)?

**Comment by oneserv-heuser** [comment]
Output from `npm -g ls eslint-plugin-react`:
```
C:\Users\heuser\AppData\Roaming\npm
`-- standard@14.3.1
  `-- eslint-plugin-react@7.14.3
```

**Comment by mightyiam** [comment]
Thank you. Could you please try `npm -g install eslint-plugin-react@7.14.3` and see if that works around the problem? Also, after that, please provide the output of `npm -g ls eslint-plugin-react` again.

**Comment by oneserv-heuser** [comment]
Output after `npm -g install eslint-plugin-react@7.14.3`:
```
npm WARN eslint-plugin-react@7.14.3 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

+ eslint-plugin-react@7.14.3
added 30 packages from 16 contributors in 2.741s
```

Doesn't solve the problem.

Output from `npm -g ls eslint-plugin-react`:
```
C:\Users\heuser\AppData\Roaming\npm
+-- eslint-plugin-react@7.14.3
`-- standard@14.3.1
  `-- eslint-plugin-react@7.14.3
```

**Comment by mightyiam** [comment]
Thank you, @oneserv-heuser. I wonder whether this occurs with a local installation. Could you please try to use a locally installed `standard`, instead of the globally installed one?

**Comment by oneserv-heuser** [comment]
When installing standard locally for the project it works.

So this error only occurs when using the global installation.
I'd really like to use the global installation as I want it to use for my entire organization to inspect code in PhpStorm. Installing standard in every single project is not a good option then.

**Comment by mightyiam** [comment]
@oneserv-heuser how about re-installing your globally installed packages? Perhaps it's a messed up install? Re-installing the globally installed packages could also solve the problem in the case that it would result in an installation of a more up-to-date package somewhere in the tree, where this particular issue is possibly already fixed.

Also, it seems that you're not using a Node.js version manager. In general, I recommend uninstalling the Node.js from the official Windows installer and then using one of:

- https://github.com/jasongin/nvs
- https://github.com/nvm-sh/nvm
- https://github.com/tj/n

To install Node.js and possibly switch between versions.

To see which globally installed packages you have, try `npm -g ls --depth 0`.

**Comment by oneserv-heuser** [comment]
I already tried reinstalling all global packages several times, the last try was just a few hours ago, so everything should be up-tp-date.

I'll give a Node.js version manager a try, but I don't think that this will solve my issue.

**Comment by mightyiam** [comment]
Thank you for responding. Regarding the version manager — it was just a tip for your convenience.

How about via the command line — could you please run `standard` in the project directory?

**Comment by oneserv-heuser** [comment]
Well, then thanks for the tip :D

Running `standard `in command line works, even after removing the project version and using the global one. So we maybe have a PhpStorm error here which has nothing to do with standard?

**Comment by mightyiam** [comment]
Mmm... How are you running Standard in PhpStorm, please?

**Comment by oneserv-heuser** [comment]
Standard is setup as Code Quality Tool in PhpStorm. That means it is setup as a linter via ESLint. This functionality is directly integrated into PhpStorm. More information can be found [here](https://www.jetbrains.com/help/phpstorm/eslint.html#ws_js_linters_eslint_using_JavaScript_Standard_Style).

So I never execute standard by hand, PhpStorm does all this. Does this answer your question or did I understood it wrong?

**Comment by mightyiam** [comment]
@oneserv-heuser thank you for the information. It answers my question. Since this seems to be a PhpStorm related issue, it seems appropriate to close it here and ask you to please investigate in PhpStorm public issues/forums and potentially contact their support. I would search for something like "globally installed standard eslint".

I'd love to know what you've learned, in this issue. Good luck.

**Comment by oneserv-heuser** [comment]
I already contacted their support yesterday and they opened an issue ticket, it can be found [here.](https://youtrack.jetbrains.com/issue/WEB-42095)
@mightyiam Thanks a lot for your help!
