### ISSUE TITLE
highly recommend adding require-await by default

### ISSUE THREAD

**Issue by dave-dm** [standard/standard#1444]
The most common bug in my work flow are forgetting some function has the async keyword and is returning a promise instead of some object. Which doesn't throw any error, it just returns unexpected results somewhere. Happens to me around once a day and always takes several minutes to debug. I added it to my .eslintrc and recommend it be added by default.

**Comment by mightyiam** [comment]
Thank you for voicing your feelings, @dave-dm. Please continue conversation in #738.
