### ISSUE TITLE
Error "is defined but never used" in for of

### ISSUE THREAD

**Issue by promo360** [standard/standard#1452]
**What version of this package are you using?**
14.3.1

**What operating system, Node.js, and npm version?**
Mac, node v10.17.0, npm v6.11.3

**What happened?**
```
  const items = [1, 2, 3]
  for (const item of items) {
    console.log(item)
  }
```

> 'item' is defined but never used.

**Comment by mightyiam** [comment]
Hi @promo360 and thank you for filing an issue.

It seems that this is likely https://github.com/babel/babel-eslint/issues/791. So I'm closing. But if you upgrade your babel-eslint and still experience this, please let use know here.
