### ISSUE TITLE
eslint-config-standard's peerDeps support newer major versions with `>=`

### ISSUE THREAD

**Issue by mightyiam** [standard/standard#1457]
https://github.com/standard/eslint-config-standard/blob/eb187deec36e72bfea4034db1a81b0d7414f814a/package.json#L51-L55

Shouldn't they use the caret (`^`) operator? How could we claim to support a newer major version that might rename/remove a rule, change some rule's options, etc.?

@LinusU 

https://semver.npmjs.com/

**Comment by feross** [comment]
You're technically right, and maybe we should change it. But I chose this because I'd rather not block people in case the new version of ESLint somehow works. Let's leave it up to the user. They'll get an error from ESLint if there's a breaking change.

**Comment by feross** [comment]
Actually, reconsidering this, I think you're right.

**Comment by feross** [comment]
Shipped this in `standard` 16. Thanks for the suggestion, @mightyiam!
