### ISSUE TITLE
Support public and private static properties

### ISSUE THREAD

**Issue by ZeroJsus** [standard/standard#1478]
I have a question.
My code failed with Unexpected token =
![image](https://user-images.githubusercontent.com/19191127/73918618-e8a04f00-48fc-11ea-9135-e305562220db.png)
![image](https://user-images.githubusercontent.com/19191127/73918665-fe157900-48fc-11ea-992b-3979712a622b.png)
![image](https://user-images.githubusercontent.com/19191127/73918677-066db400-48fd-11ea-9755-9252ca0c166b.png)
And I've configured these properties to still not solve the problem

**Comment by mightyiam** [comment]
Thank you for using standard, @ZeroJsus. And for reporting this issue.

@ZeroJsus I don't usually use classes but from [what I can tell](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static) the `=` is really unexpected there. I can't seem to find the definition that describes the proposed usage of `static` in class fields that are not methods.

It seems like it should be [right here](https://tc39.es/proposal-class-fields/#prod-ClassElement), but there is not such `static` keyword.

In any case, it seems like you should make sure that babel includes [this plugin](https://babeljs.io/docs/en/next/babel-plugin-proposal-class-properties.html).

Closing as not related to standard.

**Comment by emilbayes** [comment]
@mightyiam I don't know that this has been standardised yet, but V8 supports it: https://v8.dev/features/class-fields#public-and-private-static-properties

Example:

```js
class Foo {
  static Bar = 'baz'
}

console.log(Foo.Bar) // 'baz'
```

**Comment by mikeal** [comment]
Ya, this should be in the default supported syntax now that V8 supports it, I was pretty surprised to see this error pop up.

**Comment by LinusU** [comment]
I'm guessing we just need to bump some dependency, probably the eslint one? PR welcome ☺️

**Comment by feross** [comment]
This feature is still [Stage 3](https://github.com/tc39/proposal-static-class-features) and it's ESLint policy to only support Stage 4 proposals.

In the meantime, you can enable support with `babel-eslint` by following the instructions here: https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features

**Comment by feross** [comment]
Closing this as there's nothing to fix in `standard`.
