### ISSUE TITLE
 process is not defined

### ISSUE THREAD

**Issue by freekingg** [standard/standard#1479]
**What version of this package are you using?**

**What operating system, Node.js, and npm version?**

**What happened?**

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by mightyiam** [comment]
Hi, @RocWangPeng and thank you for using Standard. Could you please send a screen shot of the issue that you are experiencing?

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
