### ISSUE TITLE
Rule conflict between `react/jsx-closing-{tag,bracket}-location` rules and the built-in `indent` rule

### ISSUE THREAD

**Issue by isiahmeadows** [standard/standard#1480]
**What version of this package are you using?** 14.3.1

**What operating system, Node.js, and npm version?** macOS 10.14.6, Node 12.16.1, npm 6.13.4

**What happened?**
With the following config:

```js
{
  "plugins": ["react"],
  "rules": {
    "indent": ["error", 2],
    "react/jsx-closing-bracket-location": ["error", "tag-aligned"],
    "react/jsx-closing-tag-location": "error"
  }
}
```

Lint this file:

```jsx
const eslint1 = <Message
/>
const eslint2 = <Message
  someProp='some value'
/>

const eslint3 = <>
  some text
</>

const eslint4 = <Foo>
  some text
</Foo>

const eslint5 = <Foo
  someProp='some value'
>
  some text
</Foo>

const react1 = <Message
               />
const react2 = <Message
                 someProp='some value'
               />

const react3 = <>
                        some text
               </>

const react4 = <Foo>
                        some text
               </Foo>

const react5 = <Foo
                 someProp='some value'
               >
                        some text
               </Foo>
```

**What did you expect to happen?**
I would expect either all the `eslintN` ones (this plugin's rules taking precedence) or all the `reactN` ones (ESLint's built-in `indent` taking precedence) to have errors, but not both groups to have errors.

FYI, `react/jsx-indent-props` will move the props on the `reactN` variants down to match the `eslintN` variants if applied with `["error", 2]`, so it might be better to have the built-in `indent` take precedence to match this behavior.

**Are you willing to submit a pull request to fix this bug?**
Nope, but https://github.com/yannickcr/eslint-plugin-react/issues/2576 has a pointer that may help resolve the conflict.

-----

In some situations, I've had the corresponding fixes for the warnings also execute in conflicts like the one above, indicating a possible ESLint bug in the mix. I've not been able to isolate that to a 100% repro, however, and it doesn't even reproduce all the time for the times I've had it happen.

**Comment by feross** [comment]
Fixed in `standard` 15.0.1.
