### ISSUE TITLE
v14.3.2 broke support with Node.js versions <8.10.0

### ISSUE THREAD

**Issue by watson** [standard/standard#1494]
**What version of this package are you using?**

14.3.2

**What operating system, Node.js, and npm version?**

Node.js 8.9.4

**What happened?**

```
standard: Unexpected linter output:

./node_modules/eslint/lib/rules/no-octal-escape.js:41
                    /^(?:[^\\]|\\.)*?\\([0-3][0-7]{1,2}|[4-7][0-7]|0(?=[89])|[1-7])/su
                    ^

SyntaxError: Invalid regular expression flags
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at no-octal-escape (./node_modules/eslint/lib/rules/index.js:171:30)

If you think this is a bug in `standard`, open an issue: https://github.com/standard/standard/issues
```

It's complaining about the use of [the `s` regular expression operator](https://tc39.es/ecma262/#sec-get-regexp.prototype.dotAll) which wasn't introduced until Node.js 8.10.0.

**What did you expect to happen?**

That the linting completed successfully.

**Are you willing to submit a pull request to fix this bug?**

If it can help. That would involve rolling back eslint however to the previous version.

**Comment by LinusU** [comment]
Sorry about this, rushed this one out since there was security alerts involved...

I think that we should merge #1496 and cut a new patch release asap to avoid breaking peoples builds...

**Comment by LinusU** [comment]
For reference, this is the commit that introduced the breaking change: https://github.com/eslint/eslint/commit/448ff1e53734c503fb9e7e6802c1c7e441d4c019

All of the ESLint 6.x releases have always only had `^8.10.0` in their engines though, so officially it never supported `<8.10.0` at all

**Comment by LinusU** [comment]
ESLint 6.6.0 is the last to be compatible with Node.js 8.3.0 - 8.10.0, but that version still depends on the vulnerable `minimist` version...

I think that the best approach is the one in #1496, to just not run on Node.js 8.7.x, 8.8.x, and 8.9.x.
