### ISSUE TITLE
Fix JSX - Conditional expression

### ISSUE THREAD

**Issue by danielspk** [standard/standard#1499]
**What version of this package are you using?**
14.3.3

**What operating system, Node.js, and npm version?**
Node 12.15.0 - NPM 6.13.4

**What happened?**
`standard --fix` not fix some problem:

**Root.js:46:7: Expected indentation of 4 space characters but found 6**

```js
const PrivateRoute = ({ component: Component, ...rest }) => (
  <Route
    {...rest}
    render={props =>
      !isAuth() ? (
        <Redirect to={{ pathname: '/', state: { from: props.location } }} />
      ) : (
        <Component {...props} />
      )} {/* line 46 */}
  />
)
```

If I change the indentation to 4 spaces, I get the following error:

**Root.js:46:1: Expected indentation of 6 spaces but found 4**

The error is cyclical.

**Comment by feross** [comment]
Thanks for the issue. This is fixed in `standard` 15.0.1

**Comment by feross** [comment]
Scratch that – this is yet another case that we missed. Will fix it in `standard` v16!

**Comment by feross** [comment]
This will be in the standard 16 release
