### ISSUE TITLE
Yet another customization use-case

### ISSUE THREAD

**Issue by cyrilchapon** [standard/standard#1500]
Hey,

I'm looking for a way to add a custom rule to standard.

Pre-scriptum: Yes, I know : There are 200 issues with this topic. And yes, I understand the philosophy behind standardjs that is to actually "not customize it". I've been using standard for like 4 years as a CTO, and I'm even spreading the word and philosophy to every single developer I meet and go like "Just use standard.js"

THAT BEING SAID, in here we're just starting to use Flow types; and I've tried the [eslint flow type plugin](https://github.com/gajus/eslint-plugin-flowtype). I'm trying to make something clever : enforce flow usage in every single .js file with [`require-valid-file-annotation`](https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-require-valid-file-annotation) rule. From what I read, that precise use-case seems pretty common.

Here it is, rephrased : 
_I'd like to be able to customize an **eslint plugin** rule without ejecting standard_

Again, this is not about some stupid idea about "what would like to be changed in the standard ruleset". I'm pretty OK with the idea to have a standardized "basic Javascript syntax". Disabling the power of "tweaking standard ruleset" is a bad idea; I agree.

BUT, having standardjs enforce "default plugins ruleset" is not a good idea too ! Thinking of it, it's pretty weird... because as a consequence, standardjs philosophy is **not only** :

> "let's use a default, non-customizable, common ruleset"

but **also**

> "let's use every single default, potentially weird, ruleset included in any installed plugin"

... and this is pretty annoying, IMHO. What do you think ?

**Comment by LinusU** [comment]
First of all, sorry for saying this but I just can't stop myself: are you starting to use Flow now? why? have you considered TypeScript? It seems like everyone I'm talking to is choosing TS over Flow so I would love to hear your reasoning ☺️ 

With that out of the way, I think that the cleanest solution would be to have a `eslint-config-standard-with-flow` (that works in the same way that `eslint-config-standard-with-typescript` does) and `flow-standard` (that works in the same way as `ts-standard`) under the Standard organisation. But I don't think that anyone in the team is currently using Flow.

If you would like to join the team and maintain a flow flavour of Standard I think that it could be nice! 👍 I think that the setup should just be exactly as the already existing TypeScript packages, I would be happy to help you set things up.

If you don't want to maintain anything (which I would be understandable 😁) I would recommend to use [`standardx`](https://github.com/standard/standardx). It allows you to extend the config, either via `package.json` or `.eslintrc`. You should be able to add both rules and plugins there.

**Comment by Fr33maan** [comment]
What about a buggy plugin ? Standard is complaining on exported enum no being used and google lead me to https://github.com/typescript-eslint/typescript-eslint/issues/396, which suggest to swap the rule being use. Unless opening an issue here, waiting for it to be reproduced, fixed, merged and publish, I would be happy to hack the config by myself.

**Comment by LinusU** [comment]
@Fr33maan you could use `standardx` for that, but if you are using TypeScript I would recommend using `ts-standard` instead, which is optimised for working with TypeScript...

**Comment by Fr33maan** [comment]
Finally used prettier-standard, thanks for input

**Comment by feross** [comment]
@cyrilchapon Thanks for your issue! I sympathize with your situation and providing a way to customize *just the plugin rules* seems like a reasonable compromise. However, given that we have `standardx` I don't think that an option like this belongs in `standard` itself.
