### ISSUE TITLE
Respect XDG basedir spec for cache

### ISSUE THREAD

**Issue by jasonkarns** [standard/standard#1501]
**What version of this package are you using?**
- standard@14.3.3

**What problem do you want to solve?**
Standard should respect user's preferences about where to write on disk.
The [XDG basedir spec](https://specifications.freedesktop.org/basedir-spec/latest/index.html) is designed specifically for this.

**What do you think is the correct solution to this problem?**
Standard should write its cache to `${XDG_CACHE_HOME:-$HOME/.cache}/standard` so as to respect user's system configurations.

https://www.npmjs.com/package/xdg-basedir is a useful package for handling this logic.

**Are you willing to submit a pull request to implement this change?**
Yes, if I could receive some direction regarding where this directory path is determined. (I didn't find anything in a cursory search so I'm assuming this directory is actually determined via some dep.)

**Comment by mightyiam** [comment]
@jasonkarns thank you for your interest. Sounds good to me. I am assuming that spec is either cross-platform or you have some idea what to do cross platform?

https://github.com/standard/standard-engine/blob/f2f766e64a6f4b18c2d07e150ba0fbccc56bc0ca/index.js#L41-L42

**Comment by jasonkarns** [comment]
Yep. The default values for XDG_CACHE_HOME use $HOME, so the spec can be respected cross-platform. Thanks for the code location. I'll open a PR to standard-engine.
