### ISSUE TITLE
Example on /rules.html page for constructor-super would break no-useless-constructor rule

### ISSUE THREAD

**Issue by joshuagoran** [standard/standard#1505]
**What version of this package are you using?**
primarily using `"eslint-plugin-standard": "3.1.0"` with ESLint in VSCode but I don't think it matters as this seems to be strictly a documentation oversight. The same behavior happens when running `npx standard`

**What problem do you want to solve?**
the `Dog extends Mammal` example for the `constructor-super` rule itself breaks the `no-useless-constructor` rule, which is confusing.

my example from a current project is functionally equivalent to the example provided for `constructor-super` at https://standardjs.com/rules.html, but it causes the `no-useless-constructor` lint error:
```js
class MyRequestHook extends RequestHook {
  constructor () {
    super()
  }
}
```
![Screen Shot 2020-03-25 at 5 24 05 PM](https://user-images.githubusercontent.com/35858093/77587003-7a6c1780-6ebd-11ea-9805-670591912cf7.png)

![Screen Shot 2020-03-25 at 5 02 11 PM](https://user-images.githubusercontent.com/35858093/77586116-fe250480-6ebb-11ea-9b3a-5849229af72e.png)
**What do you think is the correct solution to this problem?**
use a clearer example for `constructor-super` that doesn't break other Standard rules

**Are you willing to submit a pull request to implement this change?**
possibly, but probably would defer to someone already involved in documentation if they're available 😄

**Comment by LinusU** [comment]
Nice catch! Pull requests welcome 🚀

**Comment by feross** [comment]
Fixed by https://github.com/standard/standard/pull/1506
