### ISSUE TITLE
Operators in the beginning of line instead of end?

### ISSUE THREAD

**Issue by davidc360** [standard/standard#1507]
Currently,

```
if (
  condition_1
  && condition_2
  && condition_3
) {
  doSomething()
}
```

gets formatted to 
```
if (
  condition_1 && 
  condition_2 && 
  condition_3
) {
  doSomething()
}
```

This looks good if the conditions are short and of the same length, but quickly becomes messy:
```
if (
  condition_1 && 
  condition_2_that_is_longer && 
  condition_3_shorter
) {
  doSomething()
}
```
vs
```
if (
  condition_1 
  && condition_2_that_is_longer 
  && condition_3_shorter
) {
  doSomething()
}
```
[Airbnb agrees](https://github.com/airbnb/javascript#control-statements)
Opinions?

**Comment by LinusU** [comment]
Interesting, to me personally it looks a bit off, but that's probably because I'm not used to it.

~~The larger problem here is that it probably breaks a~~ Actually, it seems like Standard accept both styles. What are you using to format the code? I think that the change isn't actually coming from Standard...

**Comment by davidc360** [comment]
> Interesting, to me personally it looks a bit off, but that's probably because I'm not used to it.
> 
> ~The larger problem here is that it probably breaks a~ Actually, it seems like Standard accept both styles. What are you using to format the code? I think that the change isn't actually coming from Standard...

In my opinion the second style is cleaner because the && will always be aligned in the beginning, and linguistically it reads more natural (this, AND this, AND this vs this AND, this AND, this). 

I'm using Standard in VSCode and this is the message I get: 
```'&&' should be placed at the end of the line. (operator-linebreak)standard(operator-linebreak)```

**Comment by LinusU** [comment]
Changing `"operator-linebreak"` from `"after"` to `"before"` breaks 39 out of 219 repositories using Standard style. That's quite a high number, which I why we probably won't make this change unless we have a very good justification....

**Comment by mightyiam** [comment]
Feeling into it a little bit, "before" seems nicer. And more diff-friendly, as well. Which is a win in my book.

**Comment by feross** [comment]
We chose the "operator goes before the linebreak" style because when you look at a line we want there to be an indication that the statement is "unfinished" and you need to read the next line.

I don't think we want to change this at this time.
