### ISSUE TITLE
Support optional chaining operator

### ISSUE THREAD

**Issue by ghost** [standard/standard#1509]
From the main page:
> standard supports the latest ECMAScript features, ES8 (ES2017), **including language feature proposals that are in "Stage 4"** of the proposal process.
> https://standardjs.com/

Currently optional chaining operator is already at Stage 4 and is supported by Chrome (from v80), Firefox (from v74) and Edge (from v80), but it's not included in the StandardJS. Could you please add support for Optional Chaining Operator in the StandardJS?
Thank you.

Related links:
- https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining
- https://caniuse.com/#feat=mdn-javascript_operators_optional_chaining
- https://github.com/tc39/proposal-optional-chaining
- https://v8.dev/features/optional-chaining

Related issues:
#1151

**Comment by LinusU** [comment]
This would indeed be nice 👍 does the latest version of ESLint support this?

**Comment by fullstackzach** [comment]
Good to know standard doesn't officially support this.

if I use a chaining operator with a function and it is not returned, example:

example:
`someObj.anotherObj.myFunc?.(arg1, arg2)`

I see the linting rule `Expected an assignment or function call and instead saw an expression. (no-unused-expressions)standard(no-unused-expressions)`

**Comment by johanleroux** [comment]
Any news on this? Will this be implemented?

**Comment by AndrewJakubowicz** [comment]
I was able to get around this issue by using the babel parser through standard js. Followed [How do I use experimental JS features](https://github.com/standard/standard#how-do-i-use-experimental-javascript-es-next-features) guide, but replaced `babel-eslint` with `"parser": "@babel"`.

My steps:

`npm install @babel/eslint-plugin --save-dev`

Then add to the package.json standard config:

```
  "standard": {
    "parser": "@babel",
  }
```

**Comment by feross** [comment]
Yes! This will be implemented in `standard` v15, which will be released later today. 🌟
