### ISSUE TITLE
"Use default import syntax to import" when importing multiple exports

### ISSUE THREAD

**Issue by lukasoppermann** [standard/standard#1513]
**What version of this package are you using?**
Standardx@5.0.0

**What happened?**
I get the error/warning:
> Use default import syntax to import 'transformer'

My code is:
```js
import { default as transformer, getField } from './transformer'
```

**What did you expect to happen?**
In this case the default import:
```js
import transformer from './transformer'
```
does not work, because I am importing multiple files, so this should not create an error.

If I am missing something, please let me know. Thank you.

**Comment by LinusU** [comment]
I believe it wants you to import as such:

```javascript
import transformer, { getField } from './transformer'
```

Maybe not the best error message 😅

**Comment by lukasoppermann** [comment]
Hey @LinusU, 

awesome, that worked! 👍
