### ISSUE TITLE
eslint-plugin-simple-import-sort

### ISSUE THREAD

**Issue by mightyiam** [standard/standard#1517]
**What problem do you want to solve?**

I would like standard to make decisions regarding styling of imports, much more than it currently does.

**What do you think is the correct solution to this problem?**

Including [eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort/).

**Are you willing to submit a pull request to implement this change?**

Sure.

**Comment by timdp** [comment]
This would be great. I spend way too much time thinking about how imports should be organized.

You can already try this out today by installing `simple-import-sort` and extending your ESLint config in `package.json`:

```json
{
  "eslintConfig": {
    "plugins": [
      "simple-import-sort"
    ],
    "rules": {
      "simple-import-sort/sort": "error"
    }
  }
}
```

With `standardx --fix`, I got perfect results for my TypeScript code.

**Comment by feross** [comment]
Sorting imports is an interesting suggestion which is already being discussed here: https://github.com/standard/standard/issues/1490

I think the suggested plugin has one big shortcoming:

> Can I use this without autofix?

> Not really. The error message for this rule is literally “Run autofix to sort these imports!” Why? To actively encourage you to use autofix, and not waste time on manually doing something that the computer does a lot better. I’ve seen people painstakingly fixing cryptic (and annoying!) sorting errors from other rules one by one, not realizing they could have been autofixed. Finally, not trying to make more detailed messages makes the code of this plugin much easier to work with.

Part of the `standard` philosophy is that you should be able to write code that passes `standard` without using the tooling -- so a rule that is literally "run autofix to fix this" is not going to fly.

Let's move discussion to https://github.com/standard/standard/issues/1490

**Comment by grsharp6** [comment]
Thank you for the update and for the help with all of this it's really
getting to be a good thing to be able to make sense of but I don't know
exactly how much I can honestly say I am going to be able to use.and feel
free to use what ever and readjust if needed

grsharp6@gmail.com
