### ISSUE TITLE
Upgrade to ESLint 7.x

### ISSUE THREAD

**Issue by LinusU** [standard/standard#1518]
- [x] Update minimum Node [here](https://github.com/standard/standard/blob/5b2af9cef9031ac0e50af50876f5a126664e9180/bin/cmd.js#L7)
- [x] Semi-blocked on https://github.com/yannickcr/eslint-plugin-react/pull/2635
- [ ] https://github.com/standard/eslint-config-standard/pull/169
- [ ] https://github.com/standard/eslint-config-standard/pull/170

We should also consider adding these new rules:

- [x] https://eslint.org/docs/rules/default-case-last
- [x] https://eslint.org/docs/rules/no-useless-backreference

ref: https://eslint.org/blog/2020/05/eslint-v7.0.0-released

**Comment by Raynos** [comment]
All of these changes are reasonable. I'm excited about bumping to eslint @ 7.

**Comment by evanplaice** [comment]
Is there anything specifically blocking progress on this?

The reason I ask is. ESLint isn't equipped to backport security fixes to the prior SemVer Major and another vulnerability was found in Lodash (ie which ESLint uses).

It'll probably be an easy fix (ie bump sub deps) but sometimes it isn't (ie the offending sub dep isn't maintained).

 Keeping StandardJS in lockstep with ESLint's SemVer major can help this by ensuring any recent patches to ESLint are immediately available.

-----

Sorry in advance if this is annoying. I woleheartedly agree.

**Comment by mcdado** [comment]
When upgrading to 7.x, if you jump to 7.4 directly, could you consider adding this option? https://github.com/standard/standard/issues/1474

**Comment by NemoStein** [comment]
In #1539 (referenced by @shadowspawn) I asked for ESLint 7.5 because of the Optional Chaining operator (and the Nullish Coalescing operator by extension).
And I think that the rules `no-promise-executor-return` and `no-unreachable-loop` (ESLint 7.3) are good rules to be added.
Also, `no-loss-of-precision` (ESLint 7.1.0) and `sort-imports` (ESLint 7.5), although probable breakers, should be parte of the ruleset.

**Comment by NemoStein** [comment]
Hey, guys, please... This issue must move on...
Using latest spec syntax is essencial to push JS applications to next level and Standard is a huge part of the community.
Please, don't let this update die. =D

**Comment by feross** [comment]
I'm working on this today.

**Comment by feross** [comment]
This will be released in standard v15.
