### ISSUE TITLE
(react/jsx-indent) conflict with standard(indent)

### ISSUE THREAD

**Issue by josegutierro** [standard/standard#1521]
![Alt Text](https://media.giphy.com/media/dW0bdf1KSsMDUeigIC/giphy.gif)

**What version of this package are you using?**
14.3.4

**What operating system, Node.js, and npm version?**
MacOS Catalina 10.15.4
Node v10.15.3
NPM 6.14.3

**What happened?**
Indent conflict with standard rule and react/jsx-indent rule

**What did you expect to happen?**
Autofix on save toggle between standard indent and react/jsx-indent

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by josegutierro** [comment]
no one?

**Comment by mightyiam** [comment]
Is this #1480?

**Comment by kevinashworth** [comment]
I see a problem here, too. `indent` wants '8 spaces but found 10' while `react/jsx-indent` wants '10 space characters but found 8.'

**Comment by GxDesign** [comment]
Any luck with this? Same boat as @kevinashworth

**Comment by smsteel** [comment]
Can confirm the same problem, using `standard 14.3.4`

**Comment by pal** [comment]
My case looks like this: 
![standard-1521](https://user-images.githubusercontent.com/26654/95120605-1d93c880-074e-11eb-813c-de3f6c85a9b4.gif)

**Comment by feross** [comment]
Fixed in `standard` 15.0.1.
