### ISSUE TITLE
Convert truthy to boolean using ternary operator

### ISSUE THREAD

**Issue by jfoclpf** [standard/standard#1522]
**What version of this package are you using?**
14.3.4

**What operating system, Node.js, and npm version?**
Node: v12.16.3
npm: 6.14.5 

**What happened?**

I used this code as example
```js
var x = 'string'
var myVar = x ? true : false
```

And this error appeared:

disallow ternary operators when simpler alternatives exist (no-unneeded-ternary)
https://eslint.org/docs/rules/no-unneeded-ternary

**What did you expect to happen?**

I find this a bit awkward. Can't we detect truthy variables using ternary operators?

Should I use `var myVar = !!x` instead? Please clarify then that on the documentation: https://eslint.org/docs/rules/no-unneeded-ternary

Thanks a lot for the great project

**Comment by jfoclpf** [comment]
I realised now that we can use also `myVar = Boolean(x)`. Perfect, but the documentation should be more clear on that. Thanks anyway

**Comment by LinusU** [comment]
Would be happy to accept a PR to update the docs!

**Comment by jfoclpf** [comment]
@LinusU where is the github directory for the rules' documentation? I can do it

**Comment by LinusU** [comment]
https://github.com/eslint/eslint/edit/master/docs/rules/no-unneeded-ternary.md

**Comment by jfoclpf** [comment]
@LinusU am I suppose to write the article from scratch when this exists already?
https://eslint.org/docs/rules/no-unneeded-ternary
May I copy-paste from it?

**Comment by feross** [comment]
@jfoclpf yep, feel free to copy from the eslint docs where it's helpful
