### ISSUE TITLE
support async iterables (for await...of)

### ISSUE THREAD

**Issue by ungoldman** [standard/standard#1526]
**What version of this package are you using?**

14.3.4

**What problem do you want to solve?**

Example code from core `fs` docs does not pass `standard` lint:

```js
const fs = require('fs')

async function print (path) {
  const dir = await fs.promises.opendir(path)
  for await (const dirent of dir) {
    console.log(dirent.name)
  }
}
print('./').catch(console.error)

```

```
Parsing error: Unexpected token await
```

https://nodejs.org/api/fs.html#fs_class_fs_dir

**What do you think is the correct solution to this problem?**

Async iterables (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of) have made it to the spec and are part of the core docs as of at least node v12.12.0.

`standard` should be able to recognize them and let them pass 🧙 

**Are you willing to submit a pull request to implement this change?**

Maybe

**Comment by LinusU** [comment]
Is this supported in the latest version of ESLint?

**Comment by ungoldman** [comment]
Seems like it should: https://github.com/eslint/eslint/pull/9957

**Comment by LinusU** [comment]
Nice, should be fixed by #1518

**Comment by ungoldman** [comment]
thank you!

**Comment by feross** [comment]
Fixed in `standard` 16
