### ISSUE TITLE
no-unused-vars within typescript enum

### ISSUE THREAD

**Issue by Fr33maan** [standard/standard#1531]
**What version of this package are you using?**
13.1.0

**What operating system, Node.js, and npm version?**
node 12.10  
npm 6.10.3

**Standard config in package.json**
```json
  "standard": {
    "parser": "@typescript-eslint/parser",
    "plugins": [
      "@typescript-eslint/eslint-plugin"
    ]
  }
```

**What happened?**
```ts
export enum EWeightUnits {
    MG = 1,
    G = 1000,
    KG = 1000 * 1000,
    T = 1000 * 1000 * 1000
}
```
Every entry of the enum has the error `'KG' is assigned a value but never used. (no-unused-vars)standard(no-unused-vars)`

**What did you expect to happen?**
No error

**Are you willing to submit a pull request to fix this bug?**
If I understand correctly, issue is referenced [here](https://github.com/typescript-eslint/typescript-eslint/issues/396), we need to change a rule in standard so we use a different version of the plugin.
Not sure where to make the code change.

**Comment by mightyiam** [comment]
I don't think Standard actually really supports TypeScript, yet. Consider using our TypeScript project config with ESLint:
https://github.com/standard/eslint-config-standard-with-typescript

**Comment by mightyiam** [comment]
#1283
