### ISSUE TITLE
Rule suggestion: no-var

### ISSUE THREAD

**Issue by NemoStein** [standard/standard#1532]
Standard 12 added `prefer-const` rule which handles `let` variable not reassigned, but this rules doesn't handle `var` variables.   
`var` is considerably more prone to causing trouble, not only because of not reassigned vars, but also because of scope bleeding.

Adding the `no-var` not only solves that problem, but it also encourage the use of `const`, which have a objectively clearer intent.

**Comment by feross** [comment]
Duplicate: https://github.com/standard/standard/issues/633
