### ISSUE TITLE
standard --fix does not recognize plugin 'classPrivateMethods'

### ISSUE THREAD

**Issue by kibebr** [standard/standard#1533]
**What version of this package are you using?**

**What operating system, Node.js, and npm version?**
OS: Debian GNU/Linux 10 (buster) x86_64
Node: 14.3.0
NPM: 6.14.5

**What happened?**
Sublime Text's linter for standard recognizes the plugin `classPrivateMethods` and everything works great. However, calling `standard --fix` gives this error:

```
standard: Unexpected linter output:

Error: Failed to load plugin 'classPrivateMethods' declared in 'CLIOptions': Cannot find module 'eslint-plugin-classPrivateMethods'
```

Here is my `package.json`:
```
  "standard": {
    "ignore": [
      "/.cache/",
      "/dist/"
    ],
    "env": [
      "jest"
    ],
    "plugins": "classPrivateMethods",
    "parser": "babel-eslint"
  },
  "author": "kibe",
  "license": "ISC",
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.10.1",
    "@babel/plugin-proposal-private-methods": "^7.10.1",
    "@babel/preset-env": "^7.10.2",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.0.1",
    "babel-plugin-rewire": "^1.2.0",
    "eslint": "^7.2.0",
    "eslint-plugin-babel": "^5.3.0",
    "husky": "^4.2.5",
    "jest": "^26.0.1",
    "standard": "^14.3.4"
  },
```
and the `babel.config.cjs`:
```
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current'
        }
      }
    ]
  ],
  plugins: [
    'babel-plugin-rewire',
    "@babel/plugin-proposal-private-methods",
    '@babel/plugin-proposal-class-properties'
  ]
}
```
**What did you expect to happen?**
I am not sure how related the Sublime Text's standard linter plugin are ([StandardLinter-contrib-standard](https://github.com/Flet/SublimeLinter-contrib-standard#:~:text=SublimeLinter%2Dcontrib%2Dstandard,have%20the%20%E2%80%9Cjavascript%E2%80%9D%20syntax.)) but it works great when enabling the `classPrivateMethods` plugin. However, `standard --fix` does not.

**Are you willing to submit a pull request to fix this bug?**
Yes

**Comment by mightyiam** [comment]
Plugins should be an array, perhaps.

**Comment by feross** [comment]
You may be running two different versions of `standard`, one local and one global. What do you get when you run:

```
npx standard --version
standard --version
```

**Comment by feross** [comment]
I'm closing this issue since I doubt there's a bug to fix here, but feel free to continue discussion! ✨
