### ISSUE TITLE
Update ESLint to 7.5.0

### ISSUE THREAD

**Issue by NemoStein** [standard/standard#1539]
The recently released [ESLint 7.5.0](https://github.com/eslint/eslint/releases/tag/v7.5.0) introduces support for the Optional Chaining operator, while [ESLint 7.2.0](https://github.com/eslint/eslint/releases/tag/v7.2.0) already introduced support for the Nullish Coalescing operator.

Integrating this changes would allow us, developer, to use those new operators without been bombarded by Standard syntax parser errors.

**Comment by NemoStein** [comment]
Additionally, enable rules `no-promise-executor-return` and `no-unreachable-loop`, added in [ESLint 7.3.0](https://github.com/eslint/eslint/releases/tag/v7.3.0), might be a good idea.

Also, `no-loss-of-precision` ([ESLint 7.1.0](https://github.com/eslint/eslint/releases/tag/v7.1.0)) and `sort-imports` (--fix rule, [ESLint 7.5.0](https://github.com/eslint/eslint/releases/tag/v7.5.0)) can be a good QoL addition.

**Comment by shadowspawn** [comment]
Existing issue is: #1518

**Comment by feross** [comment]
We're upgrading to ESLint 7.11.0 in `standard` v15, which will be released later today!
