### ISSUE TITLE
standard --fix is not fixing autofixable rules 

### ISSUE THREAD

**Issue by alex-mironov** [standard/standard#1540]
`standard --fix` is not fixing indentation/bracket issues

The version I'm using
``` 
    "standard": "14.3.4"
    "babel-eslint": "10.1.0",

```

Standard config
```
  "standard": {
    "parser": "babel-eslint",
    "globals": [
      "describe",
      "it",
      "expect"
    ]
  },
```

It's throwing a lot of errors like 
```
  36:11  error  Expected closing tag to match indentation of opening
  46:11  error  Expected closing tag to match indentation of opening
  148:1  error  Expected indentation of 10 spaces but found 45
```
despite the fact those rules are autofixable

npm: `v6.12.0`
nodejs: `v12.13.0`

**Comment by feross** [comment]
It's not possible to debug this issue without additional information, like a code sample. Please try again with the latest version of `standard`. I think that the errors you posted may be JSX related, and auto-fixing has gotten better for those rules.

If this is still an issue, please leave a comment or open a new issue.
