### ISSUE TITLE
Parsing error: Unexpected character '#'

### ISSUE THREAD

**Issue by limpid-kzonix** [standard/standard#1542]
**What version of this package are you using?**

>     standard -> `14.3.4`
>     eslint-config-prettier-standard -> `3.0.1`
>     eslint-config-standard -> `14.1.1`

**What problem do you want to solve?**
` Parsing error: Unexpected character '#'`

```js
export class Example {
  #privateVar;
  // ...
}
```

**Are you willing to submit a pull request to implement this change?**
No

**Comment by NemoStein** [comment]
Standard only supports features in Stage 4 and up.
Class field declarations (https://github.com/tc39/proposal-class-fields) are still in stage 3.
TC39 Process: https://tc39.es/process-document/

**Comment by feross** [comment]
Yep! You'll need to use `babel-eslint`. Instructions are here: https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features

**Comment by SamuelEbert** [comment]
Is there any way to stop Standard from notifying me about the error? I have tried writing `// eslint-disable-next-line` on the line before the line in error. I have also tried writing `// eslint-disable-line` at the end of the erroring line. Neither worked.

**Comment by NemoStein** [comment]
Class Fields moved to Stage 4 in April and ESLint is already tracking the change (https://github.com/eslint/eslint/issues/14343).
The feature is expected to land in ESLint in a near future.
Standard (usually) follows shortly after.
