### ISSUE TITLE
standard --fix always exits with code 0

### ISSUE THREAD

**Issue by Milo123459** [standard/standard#1543]
**What version of this package are you using?**
latest
**What operating system, Node.js, and npm version?**
node.js lts 12.3.6 npm 6.1
**What happened?**
running it an npm scripts always exits with code 1
**What did you expect to happen?**
should have some sort of check to see if it is an npm script and if it is then it should always exit code 0
**Are you willing to submit a pull request to fix this bug?**
no sorry

**Comment by JiboStore** [comment]
+1 on this issue.. it gives false negative which causes CI integration to fail

**Comment by feross** [comment]
I can't reproduce this.

It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
