### ISSUE TITLE
Enforce a maximum line length

### ISSUE THREAD

**Issue by ankurnarkhede** [standard/standard#1559]
**What version of this package are you using?** : 14.1.1

**What problem do you want to solve?**
I want standard to enforce max-len.
I use `eslint-config-standard` in my project rather than [standard](https://github.com/standard/standard) as I wanted to add a few plugins like `eslint-plugin-mocha` and `eslint-plugin-security`.

I have gone through the issue: https://github.com/standard/standard/issues/28 and understand that the idea is for standard to be "[done](https://github.com/standard/standard/issues/28#issuecomment-73341320)" at some point in time. In my opinion, standard can be just **"done"** only when it addresses all the bikeshedding topics and just enforces something.

As the best way to be consistent in the code is to enforce a style, `eslint-config-standard` doesn't have max-len specified, which can cause the contributing developers to exceed 80 or 120 characters while writing code, regex, comments, etc.
As per your comment [here](https://github.com/standard/standard/issues/28#issuecomment-73341320), ideally, the developer should try not to make lines longer, but this mistake is bound to happen with anyone. And that's why we use linter, to enforce a style to avoid such glitch.
The code reviewer might request rework on the changes in case they do not like the exceeded characters. To avoid this friction, I suppose the best way is just to enforce a max-len.

**What do you think is the correct solution to this problem?**
Enforce [max-len](https://eslint.org/docs/rules/max-len)

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by feross** [comment]
In general, we're hesitant to add rules which involve "magic numbers" since we want it to be possible for someone to write code that complies with `standard` without needing to memorize numbers or count how many statements are on a line, etc.

In the future, I'd like to add more aggressive prettier-style code formatting and we can enforce a max line length when the user asks for their code to be formatted.

**Comment by LinusU** [comment]
I'm personally very much against line length limits. My preferred line length limit at any time depends entirely on what size my code editor happens to be at that time.

I think it's better to let the editor show lines in the best possible way instead, e.g. how Xcode works by default (I think)
