### ISSUE TITLE
internal/validators.js:107 throw new ERR_INVALID_ARG_TYPE(name, 'string', value);

### ISSUE THREAD

**Issue by dziku86** [standard/standard#1584]
**What version of this package are you using?**
16.0.0
**What operating system, Node.js, and npm version?**
Win7x86, Node.js v12.5.0, npm@6.9.0
**What happened?** running `standard` in local folder and getting this error:
`internal/validators.js:107
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Rceived type object
←[90m    at validateString (internal/validators.js:107:11)←[39m
←[90m    at Object.dirname (path.js:580:5)←[39m at Linter.parseOpts (C:\Users\Administrator\AppData\Roaming\npm\node_module\
←[4mstandard←[24m\node_modules\←[4mstandard-engine←[24m\index.js:156:21)
    at Linter.lintFiles (C:\Users\Administrator\AppData\Roaming\npm\node_module\
←[4mstandard←[24m\node_modules\←[4mstandard-engine←[24m\index.js:110:15)
    at Object.Cli [as cli] (C:\Users\Administrator\AppData\Roaming\npm\node_modles\
←[4mstandard←[24m\node_modules\←[4mstandard-engine←[24m\bin\cmd.js:103:14)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modues\
←[4mstandard←[24m\bin\cmd.js:9:30)
←[90m    at Module._compile (internal/modules/cjs/loader.js:776:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:1)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:643:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:556:12)←[39m`

**What did you expect to happen?**
Default behavior: checking the style of all JavaScript files in the current working directory
**Are you willing to submit a pull request to fix this bug?**
No. I don't have sufficient knowledge for this task.

**Comment by feross** [comment]
Thanks for sharing this error report, @dziku86. I was able to reproduce this issue. It happens when there's no `package.json` file present in the current folder, or in any parent folder.

**Comment by feross** [comment]
Fixed in `standard-engine` 14.0.1. You can resolve this issue by reinstalling `standard`. To confirm you have the fixed version, you can run `npm ls standard-engine` and verify that you see only 14.0.1 or greater in the output.

**Comment by dziku86** [comment]
Thank you.

**Comment by santhoshrajmudulakar** [comment]
> npm ls standard-engine

I can see empty
