### ISSUE TITLE
Make `--verbose` the default

### ISSUE THREAD

**Issue by feross** [standard/standard#1585]
I'd like to consider making the `--verbose` flag the default, and then removing the flag.

So output will be:

```
/Users/feross/code/standard/t.js:1:1: Unexpected var, use let or const instead. (no-var)
```

Instead of:

```
/Users/feross/code/standard/t.js:1:1: Unexpected var, use let or const instead.
```

Benefits:
- Clearer which rule is being violated, so you can Google it / add a comment to disable it
- One less command line flag in the tool

Cons:
- More info in the error message, might be confusing for new users

Thoughts?

**Comment by feross** [comment]
Can I get feedback on this from @standard/folks @mcollina ?

**Comment by mcollina** [comment]
Go for it. I'd love to have the name of the rule in the error... so I could google it easier, or maybe skip it.

**Comment by Flet** [comment]
100% in favor here too.

**Comment by toddbluhm** [comment]
I made it by default print the eslint rule in `ts-standard`, so I am 100% for it as well.

**Comment by Raynos** [comment]
:+1: approved.

**Comment by bcomnes** [comment]
I'm never finding myself not wanting to know the rule. +1

**Comment by carloscuesta** [comment]
I would love this too. It's much more easier to see what rule you're breaking and the reasoning behind it

**Comment by LinusU** [comment]
💯% for this 👍

**Comment by feross** [comment]
Thanks for all the feedback. This is accepted for `standard` 17 now.

**Comment by Divlo** [comment]
I also agree, I opened a PR in `standard-engine` to implement that. :+1:
https://github.com/standard/standard-engine/pull/232

**Comment by feross** [comment]
Thanks for the PR, @Divlo. I merged it and this will be included in the next major version of `standard` and `standard-engine`.
