### ISSUE TITLE
Parsing: Numeric Separators

### ISSUE THREAD

**Issue by dl90** [standard/standard#1587]
**What version of this package are you using?**
standard@14.3.4

**What problem do you want to solve?**
Allow numeric separators (https://v8.dev/features/numeric-separators).

<img width="526" alt="Screen Shot 2020-11-02 at 8 56 08 PM" src="https://user-images.githubusercontent.com/48544754/97951094-e1a05300-1d4d-11eb-90e2-57f82b16d951.png">

**What do you think is the correct solution to this problem?**
Numbers using numeric separator should not throw parsing error.

**Are you willing to submit a pull request to implement this change?**
Unfortunately no, still a student and course load is killing me 😵.

**Comment by feross** [comment]
Please update to standard 16.
