### ISSUE TITLE
eslint-plugin-typescript is specifically required

### ISSUE THREAD

**Issue by CraigCottingham** [standard/standard#1588]
**What version of this package are you using?**
16.0.1

**What operating system, Node.js, and npm version?**
macOS 10.15.7, node 12.13.0, npm 6.14.8. yarn 1.19.1

**What happened?**

`yarn standard "**/*.ts"` errors out with `Error: Failed to load plugin 'typescript' declared in 'CLIOptions': Cannot find module 'eslint-plugin-typescript'`.

When I install `eslint-plugin-typescript` (with `yarn add eslint-plugin-typescript --dev`), a deprecation warning is presented: `warning eslint-plugin-typescript@0.14.0: Deprecated: Use @typescript-eslint/eslint-plugin instead`

If I install `@typescript-eslint/eslint-plugin` _instead of_ `eslint-plugin-typescript`, `yarn standard "**/*.ts"` still errors out.

**What did you expect to happen?**

Since the deprecation warning suggests that `@typescript-eslint/eslint-plugin` replaces `eslint-plugin-typescript`, I expected `yarn standard` to work. Instead, I have to install `eslint-plugin-typescript`, which is deprecated.

**Are you willing to submit a pull request to fix this bug?**

I don't know how to fix it, so not at this time.

**Comment by feross** [comment]
It seems like you've declared that you wish to use `eslint-plugin-typescript` in your `package.json`. Can you check for a "standard" key in `package.json` and see if you have a `plugins: ["eslint-plugin-typescript"]` option set?

If you change that to `@typescript-eslint/eslint-plugin` then it should work when you install `@typescript-eslint/eslint-plugin`. 

Also – you may wish to look at https://www.npmjs.com/package/ts-standard which makes it easier to use TypeScript with `standard`.
