### ISSUE TITLE
Absolute Path Bug?

### ISSUE THREAD

**Issue by audinue** [standard/standard#1599]
**What version of this package are you using?**
16.0.2 (Maybe. Taken from [https://standardjs.com/changelog.html](https://standardjs.com/changelog.html))

I use standard [demo](https://standardjs.com/demo.html).

**What operating system, Node.js, and npm version?**
Slax 9. Google Chrome 86.0.4240.75

**What happened?**
```js
import Litedom from '//unpkg.com/litedom'
```
Standard warned *1:21 - Do not import modules using an absolute path (import/no-absolute-path)*

Meanwhile
```js
import Litedom from 'https://unpkg.com/litedom'
```
It said *JavaScript Standard Style*

**What did you expect to happen?**
Standard doesn't warn anything because it was not a */*.

Say, it should be `/^\/(?!\/)/` not `/^\//` if you are using regex.

**Are you willing to submit a pull request to fix this bug?**
No, thank you.

**Comment by LinusU** [comment]
A bit off topic, but I think that using schema-less URLs is an anti pattern these, days. See the updated blog post here: https://www.paulirish.com/2010/the-protocol-relative-url/

> Now that SSL is encouraged for everyone and doesn’t have performance concerns, this technique is now an anti-pattern. If the asset you need is available on SSL, then always use the https:// asset.

**Comment by feross** [comment]
@audinue This is a bug in https://github.com/benmosher/eslint-plugin-import – would you mind re-filing this issue on that repo and then linking it here, so we can track it?

Also – this is another argument for possibly turning off this rule, as discussed in https://github.com/standard/standard/issues/1535.

**Comment by audinue** [comment]
Closing as this closely related to #1535.

Thank you.
