### ISSUE TITLE
Recommend @babel/eslint-parser instead of babel-eslint

### ISSUE THREAD

**Issue by feross** [standard/standard#1601]
Per https://github.com/eslint/eslint/issues/13542#issuecomment-667437352, it's now recommended to use `@babel/eslint-parser` instead of `babel-eslint`.

Can someone send a PR to update the docs in `README.md`? Also, don't forget to update the translations in `docs/`!

EDIT: More information here: https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint

**Comment by jankapunkt** [comment]
Did you get it running without errors? I tried to use `@babel/eslint-parser` and it threw the following error for every file in the project:

```
  0:0  error  Parsing error: No Babel config file detected for /path/to/file.js. Either disable config file checking with t@babel/eslint-parser: false, or configure Babel so that it can find the config files
```

**Comment by feross** [comment]
Yes, I just upgraded https://github.com/webtorrent/webtorrent-desktop to use `@babel/eslint-parser` and it worked flawlessly. See: https://github.com/webtorrent/webtorrent-desktop/commit/958814f2ead81277f92126f745d98c8952280335

**Comment by jankapunkt** [comment]
Okay I get it running now, I missed to install `@babel/core` and also had to add a `"babel": {}` entry in the `package.json`, however, I still don't get the [additional parser options for this parser](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser#additional-parser-configuration) being applied:

```json
{
  ...
  "standard": {
    "parser": "@babel/eslint-parser",
    "parserOptions": {
      "sourceType": "module",
      "allowImportExportEverywhere": true
    }
  }
  ...
}
```

When running `standard` it ignores the `parserOptions` and gives me `'import' and 'export' may only appear at the top level` Is this intended?

**Comment by feross** [comment]
We don't support `parserOptions` in `standard-engine`. I think you might want to just use `eslint-config-standard` directly since we don't plan to expose `parserOptions` from `standard`.

**Comment by jankapunkt** [comment]
Thank you, I got it running with `standardx`. I installed the following packages:

```bash
$ npm install --save-dev standardx @babel/eslint-parser @babel/core
```

and added the config in `package.json` like so:

```json
{
  ...
  "babel": {},
  "eslintConfig": {
    "parser": "@babel/eslint-parser",
    "parserOptions": {
      "sourceType": "module",
      "allowImportExportEverywhere": true
    }
  }
 ...
}
```

If `allowImportExportEverywhere` were set to `false` the parser would actually run into an error but this all may be rather an individual issue with my current setup.

Summarized: works great now. Should I add this information to the `standardx` documentation?

**Comment by feross** [comment]
> Should I add this information to the `standardx` documentation?

I don't think that the `standardx` docs mention anything about the babel eslint parser, so I don't think there's anything to update there.

**Comment by 4Z4T4R** [comment]
> Should I add this information to the `standardx` documentation?

However, after troubleshooting issues and errors while attempting to put `standardx` (and consequently `standard`) to good use, I ended up here... and @jankapunkt's config guided me through the goalpost of operational use... therefore, I suggest that perhaps this information _should_ be in the documentation.

Consider it, pls?
