### ISSUE TITLE
Rename the project. Calling it "Standard" is just pretentious...

### ISSUE THREAD

**Issue by Arcanorum** [standard/standard#1609]
Every lint rule project aims to be a "standard" of sorts. Going so far as to pass yourself off as something pseudo-official is just misleading.

That is all.

**Comment by feross** [comment]
![CAeRvd_UcAAXQ8u](https://user-images.githubusercontent.com/121766/100295687-0ea3e800-2f3f-11eb-98c6-6946954540d9.png)

This is a well-trodden topic on this repo. Please read: https://standardjs.com/#but-this-isnt-a-real-web-standard
