### ISSUE TITLE
Code coverage impacted after recent ESLINT update.

### ISSUE THREAD

**Issue by abhijitshete** [standard/standard#1686]
/* istanbul ignore else */  is not working.
![image](https://user-images.githubusercontent.com/16742515/126439008-ee31a374-dc7f-439d-a971-3d8d8b51ca2f.png)

**Comment by abhijitshete** [comment]
Fixed with adding this line in code
/* eslint line-comment-position: ["off", {"ignorePattern": "istanbul", "applyDefaultIgnorePatterns": false, "position": "above" }] */
Replace "istanbul" with yours.
Reference: https://eslint.org/docs/rules/line-comment-position#ignorepattern

**Comment by voxpelli** [comment]
ESLint should not be able to impact code coverages, if it did then its probably because some code coverage related dependency got updated at the same time

Thanks for asking though, and since it seems like you also found a solution, I'm going to close this one 🙂
