### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by jimmywarting** [standard/standard#1694]
**What version of this package are you using?**
16.0.3

**What operating system, Node.js, and npm version?**
Mac + Node v16.5.0

**What happened?**
DeprecationWarning

```
(node:97401) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./2020/" in the "exports" field module resolution of the package at /usr/local/lib/node_modules/standard/node_modules/es-abstract/package.json.
Update this package.json to use a subpath pattern like "./2020/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:97401) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./helpers/" in the "exports" field module resolution of the package at /usr/local/lib/node_modules/standard/node_modules/es-abstract/package.json.
Update this package.json to use a subpath pattern like "./helpers/*".
```
**What did you expect to happen?**
not to see any warning

**Are you willing to submit a pull request to fix this bug?**
Nope

**Comment by Divlo** [comment]
Indeed, just tested it, on my local machine with Node.js v16.6.0.
Good catch, thanks! :+1:

**Comment by Divlo** [comment]
Related issue: https://github.com/ljharb/es-abstract/issues/133

**Comment by Divlo** [comment]
Closing as the issue has been fixed.
To make sure you have the fix, please delete `package-lock.json` and `node_modules`, and run `npm install`, that way you'll get automatically the latest updates of `es-abstract`, so no DeprecationWarning.

**Comment by voxpelli** [comment]
> To make sure you have the fix, please delete `package-lock.json` and `node_modules`, and run `npm install`, that way you'll get automatically the latest updates of `es-abstract`, so no DeprecationWarning.

An `npm update` or `yarn upgrade` should also do. "Lockfile maintenance" :)
