### ISSUE TITLE
Custom extends for eslint config

### ISSUE THREAD

**Issue by zumm** [standard/standard#1695]
Standard allows to specify plugins in "package.json", but there is no way to specify extends. For example, i want to use "eslint-plugin-vue", it requires "plugin:vue/vue3-recommended" in extends. It will be great to being able write something like that in "package.json":

```json
  "standard": {
    "plugins": [
      "vue"
    ],
    "extends": [
      "plugin:vue/vue3-recommended"
    ]
  }
```

...and get it working.

**Comment by voxpelli** [comment]
I would say that the better approach then would be to use ESLint directly and install the config that this module wraps: [`eslint-config-standard`](https://github.com/standard/eslint-config-standard)

Then you get the full power of ESLint and can extend in whatever way you like.
