### ISSUE TITLE
New rule: require-await

### ISSUE THREAD

**Issue by bnb** [standard/standard#1712]
**What version of this package are you using?**
Latest

**What problem do you want to solve?**
Spending time debugging missing `await`s on async function calls

**What do you think is the correct solution to this problem?**
Enable the [require-await](https://eslint.org/docs/rules/require-await) rule.

**Are you willing to submit a pull request to implement this change?**
If it's needed, sure.

**Comment by voxpelli** [comment]
Agree, similar to #1322, would be good to do some house keeping / hardening / updating of the async / await / Promise rules

**Comment by NemoStein** [comment]
I'm not sure how I feel about the #1322, but I'm definitely against the `require-await` rule.

As I understand, the following would break because of the unimplemented abstract async method in the super class.
```js
class SuperClass {
  async doStuff () {
    await this.abstractMethod()
  }

  async abstractMethod() {
    throw new Error('Not implemented')
  }
}

class ExtendedClass extends SuperClass {
   async abstractMethod() {
     // await some async code here
   }
}
```

**Comment by watson** [comment]
@bnb so you mean forgetting to add `await` when calling a function that's `async`, or do you mean creating an `async` function that it self doesn't contain any async code?

As far as I understand the issue description, you want to lint for the first type, but the `require-await` rule does as far as I understand protect against the latter.

**Comment by watson** [comment]
The "warn if missing `await` on `async` function" rule have been discussed here on the ESLint issue tracker: https://github.com/eslint/eslint/issues/9787

**Comment by bnb** [comment]
> @bnb do you mean forgetting to add await when calling a function that's async, or do you mean creating an async function that it self doesn't contain any async code?

You're correct, I want the former. My bad if I misunderstood the `require-await` rule.

**Comment by bnb** [comment]
And yeah, seems that's impossible so closing 👍🏻
