### ISSUE TITLE
Support ESLint 8.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [standard/standard#1724]
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉

It would be awesome to have official ESLint 8 support. 👊
I'm happy to help where I can of course 🙂

**Comment by voxpelli** [comment]
Thanks! Work in progress for this can also be tracked here: https://github.com/standard/eslint-config-standard/pull/193
