### ISSUE TITLE
Standard Forcing Double Quotes Within Double Quotes

### ISSUE THREAD

**Issue by therealrodk** [standard/standard#1790]
**What version of this package are you using?**
standard 1.1.4

**What operating system, Node.js, and npm version?**
MacOS Catalina 10.15.7
Node v16.5.0
NPM 7.19.1

**What happened?**
When I run `bundle exec standardrb --fix`, it wants to change this:
`"#{@appointment.start_at.strftime('%b %e, %Y')}, All Day"`
to this:
`"#{@appointment.start_at.strftime("%b %e, %Y")}, All Day"`

Notice that it is nesting double quotes inside double quotes.

**What did you expect to happen?**
I expected that single quotes would be allowed inside double quotes, especially when string interpolation is necessary.

**Are you willing to submit a pull request to fix this bug?**
Perhaps. I am submitting this from work, so… we'll see.

**Comment by dougwilson** [comment]
This is the repo for the JavaScript standard formatter. It seems you are using the Ruby standard formatter: https://github.com/testdouble/standard

**Comment by therealrodk** [comment]
Sorry about that!
