### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by mcknasty** [standard/standard#1891]
**What version of this package are you using?**

```
xxxxx@xxxxx~/codez/c8$ grep 'standard": "' package.json
    "standard": "^16.0.4",
xxxxx@xxxxx:~/codez/c8$
```

The commit on C8 I am testing against is [8e56b23d007c30432ca9956aaee91a00cb8dd4c0](https://github.com/bcoe/c8/commit/8e56b23d007c30432ca9956aaee91a00cb8dd4c0)

**What operating system, Node.js, and npm version?**

```
xxxxx@xxxxx:~/codez/c8$ uname -r
5.15.79.1-microsoft-standard-WSL2
xxxxx@xxxxx:~/codez/c8$
```

Affected versions of node and npm

| Node Version    | NPM Version     | Error Collected                                                                        |
|:------------------:|:------------------:|:----------------------------------------------------------------|
| v10.21.1               | v7.24.2                 | TypeError: Cannot read property 'type' of undefined        |
| v12.22.12             | v8.19.3                 | TypeError: Cannot read property 'type' of undefined        |
| v14.21.2               | v9.5.0                    | TypeError: Cannot read property 'type' of undefined       |
| v16.19.0               | v9.5.0                    | TypeError: Cannot read property 'type' of undefined       |
| v18.14.0               | v9.5.0                    | TypeError: Cannot read property 'type' of undefined       |

**What happened?**

See errors above.

**What did you expect to happen?**

Expected linting to pass as it has in the past.

**Are you willing to submit a pull request to fix this bug?**

Possibly.  I think the problem is downstream in eslint.  Eslint just pushed a newer version a [few days ago](https://www.npmjs.com/package/eslint?activeTab=versions)

**Comment by exactlyaron** [comment]
Had the same issue to.


It is because of this issue - https://github.com/estools/esquery/issues/135

Which has been fixed here - https://github.com/estools/esquery/pull/138



eslint probably needs to be updated to the new version of esquery

**Comment by exactlyaron** [comment]
@mcknasty - [eslint](https://github.com/eslint/eslint/pull/16897) have pinned the version of esquery to an older version that doesn't have the bug so standard should be fine now.

**Comment by mcknasty** [comment]
Yes, this is looking fixed to me too.  Thank you for linking the issues @exactlyaron.
