### ISSUE TITLE
Add rule to catch floating Promises

### ISSUE THREAD

**Issue by falco467** [standard/standard#1895]
**What problem do you want to solve?**

In async function developers can often forget the ```await``` keyword before calls to other functions which return promises. This can lead to race conditions and missing errors, since errors are not catched by surrounding try/catch blocks.

```javascript
async function saveDetails() {
  // does stuff with a fetch call...
}

async function submitWork() {
  try {
    saveDetails() // Missing await before async call, will seem to work but errors are not catched
    showSuccess()
  } catch (err) {
    showError(err)
  }
}
```

**What do you think is the correct solution to this problem?**

There is a rule in typescript-eslint which catches these errors: [no-floating-promises](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md)

It would be great if we could include this rule in standard.

**Are you willing to submit a pull request to implement this change?**

If we are clear on how a solution should be implemented - yes.

**Comment by LinusU** [comment]
@falco467 the rule you linked are from typescript-eslint, which means it only works with TypeScript. I believe that that rule is already enabled in [`ts-standard`](https://github.com/standard/ts-standard).

**Comment by falco467** [comment]
Thank you for clarification!
I didn't realize could use ts-standard with my JavaScript projects.
But this solves several problems.
