### ISSUE TITLE
Request a syntax error correction in the "RULES-kokr"

### ISSUE THREAD

**Issue by naturalkei** [standard/standard#1906]
~~What version of this package are you using?~~

~~What operating system, Node.js, and npm version?~~

**What happened?**

Sorry, it's not a functional issue.
I would like to request a syntax error correction in the Korean version of the rule markdown document.

~~What did you expect to happen?~~

**Are you willing to submit a pull request to fix this bug?**

* <https://github.com/standard/standard/pull/1904>

**Comment by feross** [comment]
Fixed!
