### ISSUE TITLE
space-unary-ops errors on `new Class()` syntax

### ISSUE THREAD

**Issue by bcomnes** [standard/standard#1946]
I just noticed today that I started getting `space-unary-ops` warnings where I shouldn't be getting them like on `new Foo()` syntax:

<img width="466" alt="Screenshot 2023-10-26 at 1 12 31 PM" src="https://github.com/standard/standard/assets/166301/aa64951c-85ce-4f4b-92ae-684ba873faee">

I've been running `17.1.0` everywhere for a while now, but this is the first I'm seeing of it. Seems like maybe a transitive broke something.

To reproduce, clear your node_modules and reinstall 17.1.0 and lint a class instantiation.

**Comment by missinglink** [comment]
This is super broken, it's 'fixing' `new String()` to `newString()` 🤦‍♂️ 

```bash
echo "new String()" | npx standard@17.1.0 --stdin --fix
newString()
standard: Use JavaScript Standard Style (https://standardjs.com)
standard:   <text>:1:1: 'newString' is not defined. (no-undef)
```

**Comment by missinglink** [comment]
cc/ @voxpelli, this regression was introduced in the latest release.

```
echo "new String()" | npx standard@17.0.0 --stdin --fix
new String()
```

```
echo "new String()" | npx standard@17.1.0 --stdin --fix
newString()
```

**Comment by bcomnes** [comment]
@missinglink It seems to be a transitive somewhere in all of the 17 versions. Been running 17.1.0 for a while without issue.

**Comment by bcomnes** [comment]
Was an issue in acorn:

https://github.com/acornjs/acorn/commit/7cd08bfd978bb688361b9e425eb46693da5b624c

Re-installing everything and ensuring acorn 8.11.1 is in your tree fixes it.
