### ISSUE TITLE
Ctrl+Shift+E to open/close tag page isn't working

### ISSUE THREAD

**Issue by drhus** [standard/standard#1952]
## Here's what I did
on chromebook, chrome the Ctrl+Shift+E to open/close tag page isn't working i have tried with Incognito mode without extentions and still not working, both Ctrl+Shift+ L and F works

## What I expected to happen
Ctrl+Shift+E to open and close tagpage

**Comment by wesleytodd** [comment]
Hey @drhus, looks like you opened three issues and I am not sure how to help with any of them. Are you sure you are filing these on the right project?

**Comment by drhus** [comment]
Ohh i'm so sorry it's about standardnotes i accidentally put here
