### ISSUE TITLE
Unused variable in arrow functions

### ISSUE THREAD

**Issue by dcousens** [standard/standard#557]
Example

``` js
let xs = [1, 2, 3]
let ys = xs.map((x) => xs + 1)
```

Expected `unused variable "x"`,  instead got nothing.  Intentional?

**Comment by yoshuawuyts** [comment]
This doesn't happen for normal functions either - hasn't for a while now iirc

**Comment by LinusU** [comment]
I think it's because express forces you to have four arguments to be able to be an error handler, thus we cannot enforce unused variables when they are function parameters.

**Comment by yoshuawuyts** [comment]
> I think it's because express forces you to have four arguments to be able to be an error handler

Oh wow, that's not a good pattern hey

**Comment by dcousens** [comment]
Ah true... closing as duplicate of #419

**Comment by feross** [comment]
Yeah, happy to see about reintroducing this rule once there's a solution for all the express users out there (including myself!).

**Comment by LinusU** [comment]
Since we are now allowing `_` as an unused variable, I think that we should add this rule now since you can do the following:

```js
app.use(function (err, _, __, ___) {

})
```

**Comment by dcousens** [comment]
@feross thoughts?

**Comment by LinusU** [comment]
ping @feross 😀

**Comment by feross** [comment]
@dcousens @LinusU Hmm, honestly, I'm not so sure that we should discourage the inclusion of parameters even if they're unused, especially for anonymous functions used as callbacks. For example:

```js
test('no callback (array)', function (t) {
  t.plan(2)

  var tasks = [
    function (cb) {
      t.pass('cb 1')
    },
    function (cb) {
      t.pass('cb 2')
    }
  ]

  parallel(tasks)
})
```

Removing the `cb` parameter here just loses information.

On the other hand, if it's a named function, and not a callback, then I think it's useful. For example:

```js
function checkIEEE754 (buf, value, offset, ext, max, min) {
  if (offset + ext > buf.length) throw new RangeError('Index out of range')
  if (offset < 0) throw new RangeError('Index out of range')
}
```

It's confusing to have a `max` and `min` parameter that is not used.

So maybe we need an option for distinguishing between the cases?

Also, there's MASSIVE ecosystem breakage:

```
1..203
# tests 203
# pass  149
# fail  54
```

**Comment by feross** [comment]
Let's move discussion to https://github.com/standard/standard/issues/419
