### ISSUE TITLE
Enforce indentation in member expressions

### ISSUE THREAD

**Issue by feross** [standard/standard#628]
I propose adding `{ "MemberExpression": 1 }` to the `indent` option.

Example of incorrect code:

``` js
foo
.bar
.baz()

foo
    .bar
  .baz()
```

Examples of correct code:

``` js
foo
  .bar
  .baz()

// Any indentation is permitted in variable declarations and assignments.
var bip = aardvark.badger
                  .coyote
```

A small change, but adds more consistency.

Rule: http://eslint.org/docs/rules/indent#memberexpression

**Comment by feross** [comment]
Smallish ecosystem impact:

```
# tests 422
# pass  407
# fail  15
```

Also, automatically fixable.

**Comment by timoxley** [comment]
Overall 👍  but can feel a bit meh about forcing chaining to be indented:

```js
// I slightly prefer this
foo
.bar
.baz()

// vs

foo
  .bar
  .baz()
```

Can't justify this preference with anything but feelings though so… 👍 from me

**Comment by timoxley** [comment]
Ahh here's one:

```js
stream
  .pipe(through(() => {
     
  })) //  having this dangling out here looks weird IMO

```

**Comment by dcousens** [comment]
@timoxley that is a great point,  and is very disconcerting/confusing when reading code with that disjoined indentation due to this chaining indentation.

**Comment by glukki** [comment]
Please, set it to some value!

Different code editors have different default settings for chain indentation when you run code reformat. Lines jump left-right without any rule, and git history gets messed (like in my current project 😢 ).

**Comment by timoxley** [comment]
@feross I think it's time to bring this up again since the eslint default seems to have swung to requiring member expression indentation and it's not clear a consensus was reached for standard going either way regarding this.

**Comment by lordspecter13** [comment]
look useless, use the translator are hacking me since ase long time, and
you have authorized each click change, are in the TCPIP frequency: 5037
there send help there they will find but apparently, are part of this,
because my lawyer speaks English and Spanish and Chinese antler in order to
win the demand and google will stay with your page fraudalenta for illegal
use of my

**Comment by timoxley** [comment]
I stand by my [earlier argument](https://github.com/standard/standard/issues/628#issuecomment-247843940) that indenting members creates a weird closing paren/curly indentation unlike any other syntax and thus is undesirable.

i.e. changing whether something is chained or not shouldn't need to change the entire indentation of all arguments and where the closing paren is:

Consider wanting to break this chain onto multiple lines:
```js
a.pipe().pipe().then(() => {
  // function body
})
b()
```

Without member indentation, closing curly stays in the same position, as does the function body:
```js
a
.pipe()
.pipe()
.then(() => {
  // function body
})
b()
```

With member indentation, everything chained now needs to be indented for some reason:

```js
a
  .pipe()
  .pipe()
  .then(() => {
    // function body also needs indentation now?
  }) // closing paren suddenly indented?
b() // no other rule results in a closing curly/paren + newline changing -2 levels of indentation
```

**Comment by bcomnes** [comment]
No indentations does seem a tad more pragmatic

**Comment by feross** [comment]
I see the arguments for both ways of doing it. My thoughts are that whenever an expression goes onto multiple lines, you want some way of distinguishing that when looking at the later part of the expression. Indentation serves that purpose.

I do something similar for argument lists:

```js
function foo (
  argument1, argument2, argument3
) {
  // function body...
}
```

And for really long `console.log` lines:

```js
console.log(
  variable1,
variable1,
variable1,
)
```

**Comment by feross** [comment]
🗣 Standard 11 is released! Run `npm install standard@latest --save-dev` to update to the latest version. This will also update the version in `package.json` ✨

Changelog: https://github.com/standard/standard/blob/master/CHANGELOG.md#1100---2018-02-18
