### ISSUE TITLE
The first JSX property should always be placed on a new line if the JSX tag takes up multiple lines and there are multiple properties (react/jsx-first-prop-new-line)

### ISSUE THREAD

**Issue by feross** [standard/standard#696]
Ensure correct position of the first property.

`multiline-multiprop`: The first property should always be placed on a new line if the JSX tag takes up multiple lines and there are multiple properties.

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-first-prop-new-line.md

I've personally run into this while working on WebTorrent Desktop and Brave with @dcposch, where we've been very inconsistent with this.

**Comment by dcousens** [comment]
IMHO:

OK:
``` js
<Hello personal={true} />
<Hello foo={{
  x: 1,
  ...
}} />

<Hello
    personal={true}
    foo="bar"
/>
```

Bad:
```
<Hello
    personal />

<Hello personal
    prop />

<Hello personal={true}
    foo="bar"
/>
```

**Comment by feross** [comment]
Yeah, that looks right @dcousens!

**Comment by feross** [comment]
Just ran the test suite. No errors, except on `webtorrent-desktop`, and I agree that all the things it caught should be changed. So this LGTM

**Comment by feross** [comment]
This will ship in `standard` 14.
