### ISSUE TITLE
Require a newline after each call in a method chain (newline-per-chained-call)

### ISSUE THREAD

**Issue by HR** [standard/standard#720]
Hi @feross,
I would like to discuss adding a new rule: always break promise chains. Referring to the ES6 Promises (defined by the [ECMA spec](http://www.ecma-international.org/ecma-262/6.0/)), breaking up promise chains makes the code much more readable. Consider the following.

So instead of writing a promise chain like this
```javascript
getURL(URL).then((res) => {
    return processPromise(res)
  }).then((res) => {
    return processMorePromise(res)
  }).catch((err) => {
    console.error(err)
  })
```
It is far more cleaner, prettier and readable to break the promise chain like this with a new line and indentation.
```javascript
getURL(URL)
  .then((res) => {
    return processPromise(res)
  })
  .then((res) => {
    return processMorePromise(res)
  })
  .catch((err) => {
    console.error(err)
  })
```
I hope that you agree with me and it can become part of the standard rules.

Many thanks.

**Comment by dcousens** [comment]
@HR is there an eslint rule for this?

**Comment by HR** [comment]
@Dcousens I checked and couldn't find one. So, I guess not.

**Comment by dcousens** [comment]
Probably better off making your case at eslint first, then coming back here :+1:

**Comment by HR** [comment]
@dcousens I think that this rules goes perfectly well with the idea of writing "code that you find beautiful" which is what standard is about from what I understand (not that sure about eslint). I think you would agree with me that code with this rule is much more readable.

**Comment by dcousens** [comment]
@HR I don't use promises.

I do use chains though,  and I don't use the fancy syntax you promote.
Then again,  I don't have a strong opinion on it except that will break existing code.

**Comment by HR** [comment]
@dcousens Ok. I'll try making a case at eslint but I believe that this issue should get more exposure and the input of more devs before an informed decision can be made.

**Comment by grantcarthew** [comment]
I don't see that this should be a rule. It's more of a choice for the dev. I use the first example above. I don't see the proposed rule to be that much better.

**Comment by HR** [comment]
@grantcarthew the how is "Space after keywords" or "Space after function name" that much better? The proposed rule makes the code more readable than adding a space after keywords does. Wouldn't you agree?

**Comment by grantcarthew** [comment]
I just tried it out on my RethinkDB queries. It seems better. Still think it is a choice though.

**Comment by HR** [comment]
@grantcarthew so is adding a semicolon! It helps create "code that you find beautiful" because it is cleaner.

**Comment by grantcarthew** [comment]
I see your point @HR. I'm no expert though. If you read any tutorial online about Promises they are using the first example syntax above.

**Comment by dcousens** [comment]
@HR probably more importantly,  is that there is "less of a choice"... again, find an eslint rule, and if its too ambiguous either way (aka, 50/50 for standard users),  then I can't see it being enforced.

**Comment by MrZhangFengfeng** [comment]
I like yours @HR

**Comment by feross** [comment]
There's no eslint rule for this specific of a scenario, even in `eslint-plugin-promise`, however the [`newline-per-chained-call`](http://eslint.org/docs/rules/newline-per-chained-call) rule is closely related, and it's a pretty good idea:

```
newline-per-chained-call: ["error", { "ignoreChainWithDepth": 2 }]
```

Thoughts?

**Comment by dcousens** [comment]
@feross I'd see what the damage is first :laughing:

**Comment by HR** [comment]
@feross That looks good 👍 . @dcousens Just need to check for [conflicting rules](http://eslint.org/docs/rules/newline-per-chained-call#when-not-to-use-it).

**Comment by sonicdoe** [comment]
Since this rule is still being discussed, I’d like to question the indentation of promise chains. Especially for larger chains, it can lead you into thinking that you forgot to close a code block:

```js
function doSomething() {
  return getURL(URL)
    .then((res) => {
      return processPromise(res)
    })
    .then((res) => {
      return processMorePromise(res)
    })
    .catch((err) => {
      console.error(err)
    })
}
```

This has also been discussed in https://github.com/beautify-web/js-beautify/issues/482, where [@brandondrew put it quite well](https://github.com/beautify-web/js-beautify/issues/482#issuecomment-163038723):

> [the indented syntax] seems to reflect that the then() in some sense has a parent-child relationship with Promise.resolve(), but if that is true, then so does each subsequent then() have that relationship with the previous then(). Of course there really is no such parent-child relationship, and indenting as if there were all the way down would make a grand mess, so no one does it.

Anyway, this probably won’t pass for the majority of standard users, so I can understand why this might not be a good idea.

For what it’s worth, I’d really like to see such a rule – regardless of which syntax ends up being `standard`ized – because it would be one less thing to think about.

**Comment by dcousens** [comment]
Agreed with @sonicdoe that that indentation has thrown me off when reading others code.

**Comment by feross** [comment]
I usually indent anytime an expression extends onto multiple lines, e.g.

```js
if (condition1 && condition2 && condition3 &&
  condition4 && condition5) { // <-- indented here
  console.log('test')
}
```

The indention signals intent: the indented line can't be understood without looking at the previous line.

That said, I do appreciate the point you've made. Arguably the dots at the beginning of each method can signal the same thing. And yet, this looks like a bug to me:

```js
arr
.map()
.filter()
console.log('test') // is this part of the previous chain?
```

```js
arr
  .map()
  .filter()
console.log('test') // this is clearer
```

**Comment by dcousens** [comment]
@feross I don't mind either,  I think your logic:

> The indention signals intent: the indented line can't be understood without looking at the previous line.

Is sound,  and is readable.
The `dots` do work in the same way too,  but,  are inconsistent.

**Comment by glukki** [comment]
There's setting for that: http://eslint.org/docs/rules/indent#memberexpression
Please, set it to some value!

Different code editors have different default settings for chain indentation when you run code reformat. Lines jump left-right without any rule, and git history gets messed (like in my current project 😢 ).

**Comment by carmelocatalfamo** [comment]
Hi, indentation rules can be customizable?
I love this standard but i think that promises chained on same line (vertically) are more readable.
Actually I have disabled standard plugin on my code editor: there is a method to customize this rule?

From
```javascript
getURL(URL)
  .then((res) => {
    return processPromise(res)
  })
  .then((res) => {
    return processMorePromise(res)
  })
  .catch((err) => {
    console.error(err)
  })
```
To
```javascript
getURL(URL)
.then((res) => {
  return processPromise(res)
})
.then((res) => {
  return processMorePromise(res)
})
.catch((err) => {
  console.error(err)
})
```

**Comment by feross** [comment]
@carmelocatalfamo Sorry, there's no way to customize `standard`. You can try `standardx` if you want to break out and make tweaks, though it's probably not worth it IMO.

**Comment by feross** [comment]
After further consideration, I don't think the rule to require a newline after each call in a method chain (newline-per-chained-call) makes sense.

Some places where it fails:

Database migration files:

```js
exports.up = knex => {
  return knex.schema
    .table('midis', table => {
      table.integer('plays').defaultTo(0).notNullable().index()
    })
}
```

D3 visualizations where you want to place methods on the same line for clarity:

```js
    d3.select(info.selector)
      .datum(info.data)
      .transition().duration(500)
      .call(chart)
```

And sometimes it's just fine to put everything on one line:

```js
const first = crypto.createHash('sha1').update('first').digest()
```

Even by adding a "magic number" to the rule (which we usually don't do because it's confusing) in the form of `"newline-per-chained-call": ["error", { "ignoreChainWithDepth": 2 }]`, we end up with too many unpredictable failures.

```
1..162
# tests 162
# pass  139
# fail  23
```

**Comment by beenotung** [comment]
Another undesired behavior of `"newline-per-chained-call": ["error", { "ignoreChainWithDepth": 2 }]` is it break method chain into new line without indentation in some case.

Below is an example of running `eslint . --ext .ts --fix` after `prettier --write .`

```
   constructor(public concurrentSize = 1) {
     super()
-    this.ps = new Array(concurrentSize).fill('').map(() => new TaskQueue())
+    this.ps = new Array(concurrentSize).fill('')
+.map(() => new TaskQueue())
     this.i = 0
   }
```
