### ISSUE TITLE
bundle.js ignored

### ISSUE THREAD

**Issue by dcousens** [standard/standard#743]
I understand this is probably because most people use `bundle.js` for packaging... but oh god this took me 20 minutes of time wasting to figure out what was going wrong with my editor.

Do we need to special case this?
Doesn't everyone separate their source folders from distribution anyway?
In which case, if this is an issue, they can just do `standard src/`.

All the other defaults:

> node_modules/**, *.min.js, ~~bundle.js~~, coverage/**

I don't think would ever get in the way.

**Comment by gismodo** [comment]
发自我的小米手机http://m.browser.baidu.com/



发自我的小米手机http://m.browser.baidu.com/



发自我的小米手机http://m.browser.baidu.com/
On Daniel Cousens <notifications@github.com>, Jan 11, 2017 19:14 wrote:

I understand this is probably because most people use bundle.js for packaging... but oh god this took me 20 minutes of time wasting to figure out what was going wrong with my editor.

Why do we need to special case this?
Doesn't everyone separate their source folders from distribution anyway?

**Comment by feross** [comment]
Sorry you lost 20 minutes. That's always frustrating. 😢

I have lots of repos that generate `bundle.js` and I usually never have a `src/` folder for small projects. I personally appreciate having `bundle.js` as a default ignore. I've also never heard about anyone else running into this issue before.

That said, I agree that out of all the defaults `bundle.js` is the only one that could theoretically cause trouble if someone accidentally uses that name. The other ignores will almost never be a problem.

I think the usefulness outweighs the potential for confusion, given the prevalence of `bundle.js` but open to other people's thoughts.

**Comment by dcousens** [comment]
@feross I know it would be a bit special case like,  but maybe don't ignore if the file is deliberately specified on the command line?

```
standard bundle.js
```

Just being a no-op was *especially* confusing,  but alas.

**Comment by dcousens** [comment]
Or perhaps hint at what is ignored in a `verbose` mode?

**Comment by feross** [comment]
@dcousens Yeah, these are both reasonable suggestions. Right now there's no way to override the built-in ignores.

**Comment by gismodo** [comment]
发自我的小米手机http://m.browser.baidu.com/

**Comment by dcousens** [comment]
@feross ha,  bitten by this again since I started using the beta (had previously removed it from my ignore globally installed version).

**Comment by jsonmaur** [comment]
I agree `bundle.js` shouldn't be ignored by default. I was trying to lint source code for a node project and had a file with that name that was being overlooked without me even knowing about it. Naming a webpack/browserify output file `bundle.js` is just a weird front-end trend (similar to naming the output folder `dist`) that doesn't really have any reasoning behind it. I don't think it should be assumed as standard practice. If you are outputting to `bundle.js`, it should be in your gitignore anyway, which will make standardjs ignore it.

Maybe it would make more sense to ignore files _ending_ in `.bundle.js`?

**Comment by feross** [comment]
I'm re-opening this issue as @jsonmaur's argument that folks using `bundle.js` are likely to have it listed in their `.gitignore` makes sense to me. I'd like to run a test to see how many repos this change would break.

**Comment by feross** [comment]
No repos failed when I removed `bundle.js` from the default list of ignored files. Let's ship this in `standard` 14. 💪
