### ISSUE TITLE
Allow curly on line following multi-line conditional?

### ISSUE THREAD

**Issue by thejohnfreeman** [standard/standard#747]
Right now, long conditionals broken over multiple lines must be formatted like this:

```js
if (long_condition_1 ||
    long_condition_2 ||
    long_condition_3) {
  body();
}
```

In these circumstances, if I want the condition visually distinguished from the body, then I have to indent it differently (e.g. 4 spaces). I would prefer to put the curly on its own line:

```js
if (long_condition_1 ||
  long_condition_2 ||
  long_condition_3)
{
  body();
}
```

I searched and didn't find this issue discussed here, so wanted to bring it up (please point me to the original if this is a duplicate). I also don't see a customization of the [eslint curly rule](http://eslint.org/docs/rules/curly) that would permit this. Is there a popular alternative, e.g. do people really break long conditionals into separate variables? Or can we get this format in standard?

**Comment by LinusU** [comment]
I personally prefer writing it like so:

```js
if (
  long_condition_1 ||
  long_condition_2 ||
  long_condition_3
) {
  body()
}
```

Whatever the preferred way, I would love it if standard would enforce it :)

**Comment by feross** [comment]
@LinusU Yes, that is my preferred form for multiline if-statements as well.

**Comment by feross** [comment]
Writing this as @LinusU demonstrated in his comment is the recommended style so I will close this issue now.
