### ISSUE TITLE
Easy Config Mod for alternative JSX libraries like InfernoJS

### ISSUE THREAD

**Issue by aaronclong** [standard/standard#785]
Currently you must include `/** @jsx Inferno */` at the beginning  of every file with [InfernoJs](https://github.com/infernojs/inferno), a ReactJS like alternative. 

It isn't very practical for developers because I already know that Inferno is being used simply by the imports alone. Most likely, future libraries will adopt the JSX model and standard shouldn't just assume React as the base. 

A config in the package.json should be available to notify standard that an alternative library is being used.

**Comment by feross** [comment]
Agree, we should look at a way to allow this to be configured.

**Comment by feross** [comment]
There's a much more thorough discussion in this issue: https://github.com/standard/standard/issues/351

Closing in favor of that one.
