### ISSUE TITLE
Disallow empty block statements (no-empty)

### ISSUE THREAD

**Issue by tunnckoCore** [standard/standard#796]
Digging more and more in ESLint rules, i found some good ones which enforces good style and more readable code. This issue is for [no-empty](http://eslint.org/docs/rules/no-empty) rule - **not fixable**.

Suggested configuration.

```json
{
  "no-empty": ["error", { "allowEmptyCatch": true }]
}
```

Never seen a point for doing such things. It is just waste of code and is messy, adding needless branches.

For what god reason this make sense

```js
var foo = true // or false, no matter
if (foo) {}
```

I've seen such code here and there over the years, but mostly if i remember correctly it was because `if-elseif` combo like

```js
let foo = true
if (foo) {
} else if (foo === 123) {
  // ok
}
```

But again, it not make any sense.

**Comment by feross** [comment]
Thanks for the request. We need to evaluate the ecosystem impact of this.

**Comment by tunnckoCore** [comment]
Yea, i'm curious too. But don't think it will be big, huh.. i hope, it would be bad signal for the js community.

**Comment by jhabdas** [comment]
I don't feel the value this adds outweighs the complexity it adds in coding standard. Let's please KISS this library and let ESLint serve the persnickety.

**Comment by feross** [comment]
I really wanted to like this rule, and the ecosystem impact is only 3 repos! But all 3 repos are mine, and they're pretty low-level modules. It's not clear to me, how I would rewrite the code to remove the empty block.

`webtorrent`:

```js
while (self._request(wire, piece, self._critical[piece] || hotswap)) {}
```

`bittorrent-protocol`:

```js
while (this.read()) {} // consume and discard the rest of the stream data
```

`ieee754`:

```js
for (; nBits > 0; e = (e * 256) + buffer[offset + i], i += d, nBits -= 8) {}
```

For that reason, I'm -1 on this. Unless other collaborators have thoughts they'd like to chime in...

**Comment by dcousens** [comment]
If we could limit it to that idiom,  that'd be fine.

Your `for` loop could easily be re-written though:
```
while (nBits > 0) {
  e = (e * 256) + buffer[offset + i]
  i += d
  nBits -= 8
}
```

**Comment by dcousens** [comment]
Perhaps ask the eslint team for a special case to allow empty `while` blocks?

**Comment by feross** [comment]
@dcousens Fair point about the for-loop!

Does someone want to volunteer to request this option from the ESLint team? If you do it, please post the link here so I can subscribe to it :)

**Comment by dcousens** [comment]
@tunnckoCore ? :P

**Comment by tunnckoCore** [comment]
I don't have the time currently.

As we seen, from whole community, only @feross is using such things hehe. As seen, there's always better approach instead of some tricky bytes - that's javascript: tons of available ways, one best! haha

**Comment by feross** [comment]
I think we can merge this now with this config:

```js
no-empty: ["error", { "allowEmptyCatch": true }]
```

The examples I pointed out before can be worked around by including a comment inside the empty body, which explains the reason that it's empty. I think this might have been an addition later to the rule?

And the other example can be rewritten as @dcousens pointed out.

Let's include in standard 16.
