### ISSUE TITLE
Disable backtick quotes if it is not a template

### ISSUE THREAD

**Issue by a-rodin** [standard/standard#838]
Now you could write either

```js
let a = 'hello'
```

or

```js
let a = `hello`
```

And it would pass `standard` linter for both cases, even if in the second case the template doesn't have any interpolated variables and in fact is just a different form of a string. So you could mix both forms, something conceptually similar to mixing `"` and `'` quotes.

ESLint allows us to prevent this behavior by adding a rule

    "quotes": [2, "single"]

This rule makes ESLint to throw an error for this
```js
let a = `hello`
```

but don't throw any errors for this
```js
let subject = 'world'
let a = `hello, ${world}`
```

Also see [this issue in ESLint](https://github.com/eslint/eslint/issues/5234).

**Comment by dcousens** [comment]
NACK,  only because it means if I am using templates,  I have more rules to remember or otherwise have `standard` bark at me.

**Comment by yoshuawuyts** [comment]
I don't mind this, it'd warn for weird mixing stuff like:
```js
var a = `hello` + '  my ' + `brethren`
```
Standard would tell you that you probably meant to either use single quotes or interpolate, but definitely not the weird thing right there above. I feel that this would indeed be in the spirit of https://github.com/feross/standard/issues/791 where there's a default way to do things, and we warn if people are deviating from it without there being a need to.

_note: I don't really mind whatever way it goes, just like - feel it's consistent with the ruleset we've been applying so far._

**Comment by dcousens** [comment]
it'd be simpler to just disable non-backtick quotes entirely

**Comment by a-rodin** [comment]
@dcousens In this case it would be necessary to rewrite README.md and the front page of https://standardjs.com , as they state that

> Single quotes for strings – except to avoid escaping

**Comment by skbolton** [comment]
Yeah personally I use back ticks all the time that way I am always ready to interpolate

**Comment by feross** [comment]
> it'd be simpler to just disable non-backtick quotes entirely

I like having two types of quotes to indicate intent. Interpolating is rare enough that I appreciating having it explicitly called out by the `` ` `` character.

**Comment by skbolton** [comment]
Well really there is no harm leaving a template string as an interpolated string. Yeah normally it means that you are going to interpolate but I think it would be weird to have that as a rule

**Comment by a-rodin** [comment]
There also a couple of arguments against making backtick quotes default for all strings instead of single quotes:

1. Using backticks for strings without interpolated variables adds need of additional care about escaping because if you are not planning to interpolate, but for some reason want to have in your string literally `${console}` then it should be properly escaped in order to avoid runtime errors or perhaps even vulnerabilities. It also not always possible to automatically determine the cases when an expression should be escaped and when it is not, like in this example with `${console}`.
2. Making backticked strings default instead of single quoted ones would break all the codebases in pure ES5 that can't use string template syntax but use `standard` to enforce style rules.

**Comment by blgm** [comment]
I can see how disabling backticks would fit with Standard's existing philosophy
- In ES5, the the rule is that you *must* use single quotes, except when you need the extra functionality of double quotes (e.g. to quote a single quote)
- In ES6, a rule saying that you *must* use single quotes, except when you need the extra functionality of double quotes or backticks would make sense.  Extra functionality would include:
  - quoting other types of quote
  - templates
  - literal new lines

**Comment by romanzoller** [comment]
I also think this would make sense, such that

> Single quotes for strings – except to avoid escaping

is enforced. Note that the implementation is very simple: Remove the `"allowTemplateLiterals": true` option from the `quotes` rule. Despite the naming of the option, `"allowTemplateLiterals": false` actually still allows template literals when their extra functionality is used, see examples in the [doc for the quotes rule](https://eslint.org/docs/rules/quotes).

**Comment by mightyiam** [comment]
https://github.com/standard/eslint-config-standard/pull/151

**Comment by feross** [comment]
Thanks for the input everyone!

I think that we should disallow template literals when placeholders or tagged template features are not used.

  ```js
  console.log('hello there')    // ✓ ok
  console.log("hello there")    // ✗ avoid
  console.log(`hello there`)    // ✗ avoid

  $("<div class='box'>")        // ✓ ok
  console.log(`hello ${name}`)  // ✓ ok
  ```

Only 1 ecosystem package (`webtorrent-desktop`) needed to be updated, and it was just one line that needed the update: https://github.com/webtorrent/webtorrent-desktop/commit/c8f1e23b1a3908e3b616b457736fdc2a31af9502

I'm going to ship this in v14.

**Comment by mightyiam** [comment]
Lovely!

**Comment by ArmorDarks** [comment]
And what about this case?

```js
console.log(`I'd like to quote someone: "That will force manual escaping on me"`)
```

It seems to be legit, but it's forbidden by the rule.

**Comment by mightyiam** [comment]
@ArmorDarks as you know, Standard's preferred quotes are single quotes. Allowing double quotes when the string contains single quotes is one thing. Because single and double quotes are equal in all ways, as far as I know. Since backticks are a different language feature (inline expression and tags), allowing them in order to avoid escape characters is a different consideration.

**Comment by langri-sha** [comment]
I\'m not sure how I\'m supposed to feel about maintaining sentences like these and being forced to escape manually myself.

This rule is quite problematic, because using backticks without any tags or expressions clearly conveys the intent: this is language being displayed to humans.

**Comment by mightyiam** [comment]
@langsri-sha, could you please expand on "this is language being displayed to humans"? I don't quite understand what "language" means here. The string?

**Comment by langri-sha** [comment]
@mightyiam here are a few instances where I use backticks because the string is something that's communicated directly to humans:

```
debug(`Use the Force, Luke!`)
new Error(`Whoops, something went terribly wrong!`)
test(`foo does something`, () => {})
```

So was able to keep things neat and tidy with just single quotes and backticks. Now there's mixed use of single quotes, double quotes, escape sequences and backticks :grimacing:!

**Comment by mightyiam** [comment]
@langri-sha what do you mean by "communicated directly to humans", please? You mean, while those humans are reading the code? Or by test failure messages, error messages and debug logs?

**Comment by langri-sha** [comment]
By this I mean strings that are used to express written language. The case the OP makes with:

> let a = 'hello'
> let a = `hello`

:point_up: I see this more as "I have a problem that I can express strings in two different ways", but I don't think this sufficiently accounts for written language, like this paragraph that I just writing. As I said, we've moved from a consistent use of single quotes and backticks to mixed use of single quotes, double quotes, escape sequences and backticks.

**Comment by mightyiam** [comment]
@langri-sha thank you for the explanation. I understand what you mean now.

Personally, it's a non-issue for me. If you have a suggestion, could you please open a new issue with that?
