### ISSUE TITLE
Proposal: standard GitHub organization

### ISSUE THREAD

**Issue by rstacruz** [standard/standard#846]
It may be time to consider moving all `standard` GitHub projects into its own organization.

## Why?

Standard spans across many packages at the moment:

- standard
- eslint-config-standard
- eslint-config-standard-jsx
- eslint-config-standard-react
- eslint-plugin-standard
- standard-www
- standard-packages
- standard-engine
- standard-json

And there are some "somewhat officially sanctioned" standard derivatives, maintained by standard maintainers themselves:

- semistandard
- ~~standard-react~~

## Benefits

- __Simplified collaboration:__ This will drastically simplify adding collaborators into the project. By adding them into the org team, they'll get access to all related standard repos.

- __Adopting forks:__ there are some standard derivatives that are stagnating. If there's enough community interest in them, they can be adopted into the standardjs organization and co-maintained by standard maintainers.

## Naming

As for name candidates, the name @standardjs has been stagnating for a while, and @standard-js is not taken.

**Comment by feross** [comment]
I think moving to an organization is a great idea! Unifying all the `standard` packages in one place seems like a huge win

I managed to get my hands on the name @standard thanks to a kind anonymous soul who is totally amazing! 🎉 

Can't wait to hear what the haterzzz are gonna say when this repo goes from `feross/standard` to `standard/standard`. Hah, music to my ears  🎶👂 "HOW DARE YOU USE THAT USERNAME -- ARE YOU EVEN A REAL STANDARDS ORGANIZATION" 🤣

Maybe we should change to `standard/js` and eventually branch out into `standard/python`, `standard/ruby`... I KID, I KID!

**Comment by feross** [comment]
All the repos that were owned by @feross are now owned by @standard – wohoo! 🤘

Anyone who had commit on a `standard` related repo should have gotten an invite to the organization. **Note: If you don't have Two-Factor Authentication set up, you may have lost commit rights. Set that up and let me know if you need to be re-added.**

Remaining repos to transfer:

- https://github.com/Flet/standard-engine (cc @Flet)
- https://github.com/Flet/standard-json (cc @Flet)
- https://github.com/xjamundx/eslint-plugin-standard (cc @xjamundx)

It's debatable whether these should be added, but I'm okay if that's what @Flet wants.

- https://github.com/Flet/semistandard
- https://github.com/Flet/SublimeLinter-contrib-standard

If other maintainers of editor plugins want to move their plugins into the organization, I'm fine as long as we add the maintainers to the organization so those plugins actually get maintained. 💪

**Comment by feross** [comment]
CC'ing owners of other plugins. Just FYI, StandardJS is now in a GitHub organization (@standard):

- https://github.com/gustavnikolaj/linter-js-standard-engine (cc @gustavnikolaj)
- https://github.com/chenxsan/vscode-standardjs (cc @chenxsan)
- https://github.com/ishamf/brackets-standard/ (cc @ishamf)
- https://github.com/capaj/vscode-standardjs-snippets (cc @capaj)
- https://github.com/TimonVS/vscode-react-standard (cc @TimonVS)
- https://github.com/gaboesquivel/atom-standardjs-snippets (cc @gaboesquivel)
- https://github.com/stephenkubovic/atom-standard-formatter (cc @stephenkubovic)

I'm wondering if it's desirable to put editor plugins into the organization. I don't feel strongly either way -- curious to hear what people think.

**Comment by gustavnikolaj** [comment]
This consolidation seems like the right thing to do, yay! :tada: 

As for editor-plugins, I am in line with @feross - I really don't know if they fit better in- or outside the organization. Either way, [linter-js-standard-engine](https://github.com/gustavnikolaj/linter-js-standard-engine) is small enough that I don't feel I qualify to vote. :smile: 

As I see it, the main benefit of adopting editor plugins is (as mentioned under benefits in this issue) that the community can step in and take over if a maintainer disappears. This will help make a more coherent ecosystem and avoid stagnation. But it comes at a price of course - it's will be a much bigger pile of code with a much wider scope, which means a larger demand for contributors.

I'm not sure how that trade-off will balance out, but I guess the conservative approach would be to postpone it for now, and see how the first step of the transition to the org goes. If it's massively successful, then it might not be a problem to on-board all the editor integrations too... 

I'll be happy to handover the project to the new org, should that be the direction that you all choose to go with.

**Comment by jprichardson** [comment]
Great move @feross! I was hoping this would happen at some point! 🎉

**Comment by capaj** [comment]
@feross I think it's desirable. Anyone who is new to standard and is browsing the organisation on github will be able to see standard is supported well in all major editors.

One thing though-it would probably make sense to try to align the snippets as best as we can across all three editors in the future. There will always be some differences because snippets work differently in every editor, but there is certainly some common set of snippets we could make work in all editors.

**Comment by chenxsan** [comment]
> Can't wait to hear what the haterzzz are gonna say when this repo goes from feross/standard to standard/standard

hahaha, I did receive some complains for vscode-standardjs because of `standard`.

Mostly i agree with @gustavnikolaj. The only problem to me would be my code quality - it's not tested, although it works :)

**Comment by stephenkubovic** [comment]
I'd be open to having the plugins live in the org. For someone viewing the org, it may make it easier to distinguish how all the pieces fit together and what the responsibilities are of each.

**Comment by gaboesquivel** [comment]
@standard!  that's awesome!  I think this change will consolidate the tooling and community around standard.  We move atom snippets repo, makes sense to me.

**Comment by gaboesquivel** [comment]
https://github.com/mattdesl/standardize  @mattdesl

**Comment by bcomnes** [comment]
For what its worth, I own https://www.npmjs.com/org/standardjs but I'm not sure we should start name-spacing our modules.

**Comment by tunnckoCore** [comment]
Standard and all ecosystem around it is welcome to the @Standards org. I got it in the beginning, in first months after StandardJS was release and a bit before Standard-Engine was born. The idea was to move everything there, even the Standard Readme and such standards.

Long time after that @leog came and reached me with some interesting idea. Which now is seen in the org and is described in its website. And the old content of the org was moved to the @gh-standards (which was @leog's org) as backup place for the idea that i had with few forks and opened issues.

So, long story short, i'm okey with that most of the StandardJS ecosystem to come to the org. All maintainers and devs who want can have separate team and we won't mess with the repos if you want. I'm totally okey, even more, i don't have any time for anything, recently. If @leog is okey too, i believe we can allow one exception from our rule, for StandardJS ecosystem. 

Later in time StandardJS as standard can be first validated (more about the process read on the site and on the so called ["meta" standard](https://github.com/standards/meta)).

If anything need more clarification or need to chat, reach us at our gitter [Lobby](https://gitter.im/standards/Lobby).

**Comment by tunnckoCore** [comment]
Would you accept [tunnckoCore/modern-javascript-snippets](https://github.com/tunnckoCore/modern-javascript-snippets)? It have VSCode (on the Marketplace) and Atom (atom's registry) snippets, most complete StandardJS-driven snippets.

**Comment by gaboesquivel** [comment]
https://github.com/timoxley/standard-loader  @timoxley

**Comment by timoxley** [comment]
`timoxley/standard-loader` is now `standard/standard-loader`

https://github.com/standard/standard-loader

**Comment by ishamf** [comment]
I switched editors from Brackets years ago... I think the plugin no longer works, sorry.

I'll transfer the repo, at least for the name and links.

https://github.com/ishamf/brackets-standard/

**Comment by leog** [comment]
Hi @tunnckoCore. I already reached @feross about using @standards org. AFAIU there was no interest in using it as it defines a different process to produce valid and scalable standards than he first thought of for standardjs. 

FYI, I already changed a little bit the process to not rely on moving the defined standards to the org, they can live in any place and still show up on the standards initiative. 

Anyway, I'm completely open to change it in any way to promote a healthy environment to produce standards. As a learning experience I've been also using the same @standards org process on Autodesk (http://standards.autodesk.com) to produce standards inside Autodesk on its enterprise GitHub instance and it's working really good, getting traction while people gets used to collaborate using GH.

**Comment by gaboesquivel** [comment]
@feross Trying to move the atom snippets package I'm getting this message 
`You don’t have the permission to create repositories on standard`

**Comment by feross** [comment]
@gaboesquivel Just added you

**Comment by Flet** [comment]
This is a thing now! 🎉 🎉 🎉

**Comment by chenxsan** [comment]
@feross Recently I don't find any time maintaining vscode-standardjs, is it still valid that I can transfer it into `standard` organization so someone might be interested in maintaining it?

**Comment by bcomnes** [comment]
Funny enough, I've not been using the sublime plugin I wrote as much these days, and have been using @chenxsan's vscode plugin.  Moving both to the org would increase the number of people with commit access and help get fixes out if needed.

**Comment by Flet** [comment]
@chenxsan I'm in favor of this and volunteer as tribute to help maintain it :)

**Comment by LinusU** [comment]
Using that plugin every day, would love to help maintain it 👍

**Comment by Flet** [comment]
Invited @chenxsan to the org :)

**Comment by chenxsan** [comment]
@Flet @LinusU @bcomnes Transfered :)

**Comment by feross** [comment]
@chenxsan @Flet Thanks!

**Comment by feross** [comment]
Re-opening this as a note to self: I want to take a look through the list of plugins and see if there are any left that still need to be transferred into the @standard org, so we can ping the authors.

**Comment by stephenkubovic** [comment]
I'd be interested in transferring my Atom plugin into the org. https://github.com/stephenkubovic/atom-standard-formatter

**Comment by feross** [comment]
@stephenkubovic Nice. You can transfer it to @standard and we'll accept the request. I'll add you to the organization right now.

Are you interested in continuing to lead the maintenance/development on it? Or looking to find a new maintainer?

**Comment by stephenkubovic** [comment]
@feross transfer request sent!

Regarding ongoing development - admittedly I haven't found the time recently to spend on it. If someone is interested in maintaining it, that would definitely help move things forward.
