### ISSUE TITLE
Enforces return statements in callbacks of array's methods (array-callback-return)

### ISSUE THREAD

**Issue by feross** [standard/standard#859]
ESLint just promoted this rule to their 'eslint:recommended' rule set, so it's probably pretty reliable. I want to check how much of the ecosystem this effects and consider enabling it.

`Array` has several methods for filtering, mapping, and folding. If we forget to write `return` statement in a callback of those, it's probably a mistake.

This rule enforces usage of `return` statement in callbacks of array's methods.

This rule finds callback functions of the following methods, then checks usage of return statement.

```js
Array.from
Array.prototype.every
Array.prototype.filter
Array.prototype.find
Array.prototype.findIndex
Array.prototype.map
Array.prototype.reduce
Array.prototype.reduceRight
Array.prototype.some
Array.prototype.sort
```

https://github.com/eslint/eslint/blob/master/docs/rules/array-callback-return.md

**Comment by dcousens** [comment]
Yes.

**Comment by dcousens** [comment]
Though,  I have used `.some` in the past to short-circuit a forEach loop

**Comment by feross** [comment]
@dcousens It's fine to use `.some` in that way. You're still using `return` in the function callback right?

**Comment by dcousens** [comment]
> If we forget to write return statement in a callback of those, it's probably a mistake.

I misread it as `if we forget to write return statement [] for those`,  indeed, you are right :+1:

**Comment by feross** [comment]
About 7% ecosystem effect:

```
1..207
# tests 207
# pass  193
# fail  14
```

Examples of failures that I think are good errors to report:

```js
    const tuples = this.stringTuples().filter((tuple) => {
      if (tuple[0] === protocols.names.ipfs.code) {
        return true
      }
    })
```

```js
  tuples.map(tup => {
    const proto = protoFromTuple(tup)
    parts.push(proto.name)
    if (tup.length > 1) {
      parts.push(tup[1])
    }
  })
```

More marginal cases where more explicitness doesn't hurt:

```js
    keys.some(function (key, i) {
      tasks[key](function (err, result) { each(key, err, result) })
      if (i === limit - 1) return true // early return
    })
```

```js
    input.some(item => {
      if (typeof item === 'string') {
        opts.name = corePath.basename(item)
        return true
      } else if (!item.unknownName) {
        opts.name = item.path[item.path.length - 1]
        return true
      }
    })
```
