### ISSUE TITLE
Can provide a global config when using babel-eslint 

### ISSUE THREAD

**Issue by kimown** [standard/standard#870]
I want to use babel-eslint so I found this doc: https://github.com/feross/standard#how-do-i-use-experimental-javascript-es-next-features .

But I have a question, I want all my projects  to use babel-eslint, the only way I found is adding this config to the every package.json of all my projects.
```
  "standard": {
    "parser": "babel-eslint"
  }
```

 can standard provide a global config to make babel-eslint as default parser?

**Comment by Flet** [comment]
Unfortunately I don't think there is anything out there. There used to be a `babel-standard` package that existed before this option was available, but I think folks using `babel-eslint` are using it exactly as described in your comment.

It should be possible to do this using [standard-engine](https://github.com/standard/standard-engine) directly with a custom eslint config based off [eslint-config-standard](https://github.com/standard/eslint-config-standard).

Sorry we were not able to help more! Closing this issue, but feel free to comment.
