### ISSUE TITLE
Website: git pre-commit hook should use `xargs -r`

### ISSUE THREAD

**Issue by ttencate** [standard/standard#887]
git diff --name-only --cached --relative | grep '\.jsx\?$' | xargs -r standard
                                                                       ^^

This way, `xargs` won't run `standard` if no JavaScript files were changed in this commit. This is useful because without arguments, `standard` needlessly checks everything.

**Comment by Flet** [comment]
Nice! Would you mind updating the README in this repo? The website gets its content from here. I'll happily merge it!
