### ISSUE TITLE
Problem with no-callback-literal

### ISSUE THREAD

**Issue by saratitan** [standard/standard#888]
I fail to see what's invalid with the following code, what makes this callback literal?
```js
  ], (err, result) => {
    callback(...response(err, (result ? result.paymentProvider : '')))
  })
```
results in
```
Unexpected literal in error position of callback  standard/no-callback-literal
```

**Comment by rkurbatov** [comment]
Confirm, it complains about callback with rested arguments.

**Comment by toddself** [comment]
Also, it is complaining about:

```js
    if (err) {
      log.error(err, 'Cannot get from database')
      return cb({
        message: 'Cannot get data',
        code: 500
      })
    }
```

We use this frequently since we don't actually want the end user to see the backend message since it is 100% useless to them (and could potentially leak table names, etc), so we return an object that our HTTP framework understands.

**Comment by LinusU** [comment]
@toddself We have a similar setup at work, but we still use `Error` instances instead of a plain object. Something like this:

```js
class UserError extends Error {
  constructor (...args) {
    super(...args)
    this.name = this.constructor.name
    Error.captureStackTrace(this, this.constructor)
  }
}
```

```js
app.use((err, req, res, next) => {
  if (err instanceof UserError) {
    // send nice detailed error
  } else {
    // send generic 500 and log error
  }
})
```

**Comment by toddself** [comment]
This was easy to fix by just moving the object creation to a new variable and returning that variable.

Not sure if this is a bad thing though?

**Comment by maxbrunsfeld** [comment]
I think this rule should simply be removed. Not all callbacks need to take errors as their first argument.

**Comment by bcomnes** [comment]
I’m guessing the rule semantics didn’t take spread operators into account. Perhaps there is a newer version of he rule?

**Comment by catdaddy23** [comment]
I agree. It should be removed all together

**Comment by LinusU** [comment]
> I agree. It should be removed all together

I really don't think so. E.g. the code posted by @toddself is exactly the code we want to specifically want to disallow, since it breaks assumptions that people have on how Node.js-style callbacks works.

> I’m guessing the rule semantics didn’t take spread operators into account.

This problem would be nice to fix though, this should be reported upstream to ESLint, anyone feel up for doing that?

**Comment by feross** [comment]
> @LinusU This problem would be nice to fix though, this should be reported upstream to ESLint, anyone feel up for doing that?

The problem is that we're the maintainers of the `no-callback-literal` rule ;) https://github.com/standard/eslint-plugin-standard

**Comment by feross** [comment]
Let's move discussion here: https://github.com/standard/standard/issues/1352
