### ISSUE TITLE
Rule about new lines after curly-less arrow function bodies 

### ISSUE THREAD

**Issue by tunnckoCore** [standard/standard#889]
Recently seen an article that has this snippet

```js
const arr = [{ name: 'first', value: 13 }, { name: 'second', value: 7 }]
const enrichElementWithCalculatedValue =
  elem => ({ name: elem.name, calculatedValue: elem.value * 10 })
const filterElementsByValue = value =>
  elem => elem.calculatedValue > value
const aggregateElementInObject = (acc, elem) => ({
  [elem.name]: elem.calculatedValue,
  ...acc
})
const res = arr
  .map(enrichElementWithCalculatedValue)
  .filter(filterElementsByValue(100))
  .reduce(aggregateElementInObject, {})
```

I thought that it isn't very readable for my eyes. Not seeing such thing for the first time. So i'm thinking, is there rule for this? And if yes, could we include it in standard? A lot better would be to have a new line after the arrow function bodies. Probably, it would be good for beginners to understand that it is a function body and where it ends.

Sorry if issue is duplicate or discussed, just don't have the time to scroll over the issues right now.

Cheers :)

edit: Side note, probably it would be against Prettier's formatting, sadly?

**Comment by dcousens** [comment]
Maybe a maximum density of 120 characters per 80*5 character space?

**Comment by feross** [comment]
It's not clear that there's an ESLint rule for this, so I'm going to close this issue. If this is not the case, please comment or re-open.
