### ISSUE TITLE
Possible new rule-disallow naming a variable in a function the same as a function parameter

### ISSUE THREAD

**Issue by capaj** [standard/standard#891]
I'd like to have a rule against naming variables in a function the same as a function parameter.
It makes code unreadable, because it requires the reader to resolve the scope of current variable based on scoping rules and that's not always easy, especially with `let`.
I don't think there is an eslint rule for this, but if there would be a a positive stance toward this rule by standard maintainers I'd love to write such a rule.

example of invalid code:
```javascript
function (a) {
  let a
}
```

**Comment by dcousens** [comment]
http://eslint.org/docs/rules/no-redeclare

It is enabled...

**Comment by capaj** [comment]
@dcousens sorry, what I meant was:
```javascript
function (a) {
  if (a) {
    let a = 1
  }
}
```
this one is valid currently.

**Comment by feross** [comment]
It seems like the `no-redeclare` rule has gotten stricter because this example is caught by the latest standard v15:

```js
function test (a) {
  if (a) {
    var a = 1
    console.log(a)
  }
}
```

Closing this issue.

**Comment by LinusU** [comment]
@feross your example is using `var` (instead of `let`) which creates a function scoped variable which is why I believe that it's flagged as an error. Changing it to `const` (or `let`) make the snippet pass Standard style.

I'm personally not 100% sure that it's bad to have a variable named the same in a more narrower scope though 🤔

**Comment by feross** [comment]
Yeah, I think it's fine to "shadow" variables (which is what `const` or `let` lets you do in this context).
