### ISSUE TITLE
Proposal: conditional operator in string concatenation

### ISSUE THREAD

**Issue by delvedor** [standard/standard#893]
Hi all! :)
I got this weird issue that was not trivial to debug until I found the cause.
If you use a conditional operator without the parenthesis inside a string concatenation the result will not be what you are expecting (at least for me!).
Example:
```js
'hello' + true ? 'a' : 'b' + 'world' // 'a'

'hello' + (true ? 'a' :'b') + 'world' // 'helloaworld'
```

Standard didn't warn me about this behaviour, it is worth make a new rule?
Thanks!

**Comment by yoshuawuyts** [comment]
Think when concatenating constants it might make sense that it's indeed not
what you want. If it uses vars it's a v different case. A specific rule for
this could indeed be helpful

**Comment by delvedor** [comment]
Happens the same if I do:
```js
var h = 'hello'
var w = 'world'
console.log(h + true ? 'a' : 'b' + w) // 'a'
console.log(h + (true ? 'a' : 'b') + w) // 'helloaworld'
```

**Comment by feross** [comment]
Thanks for the suggestion. There's not an ESLint rule to catch this case, as far as I'm aware. But I'll keep my eyes out for if one gets added and enable it.

**Comment by delvedor** [comment]
Great, and thank you this awesome project! :)
