### ISSUE TITLE
Input files whose name contains a backslash are quietly ignored

### ISSUE THREAD

**Issue by ttencate** [standard/standard#899]
Admittedly, it's a bit twisted to have backslashes in filenames, but this might point towards a broader escaping or error handling issue:

```bash
$ echo "wrong();" > foo.js
$ echo "wrong();" > foo\\bar.js
$ standard *.js
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /tmp/foo.js:1:1: 'wrong' is not defined.
  /tmp/foo.js:1:8: Extra semicolon.
```

Similarly, input files that don't exist are silently ignored:

```bash
$ standard qux.js
$ echo $?
0
```

**Comment by feross** [comment]
Confirmed. There are two issues here. The second is a known behavior that I agree we should improve.

**Comment by feross** [comment]
Both of these issues ("backslashes in filenames" and "input files that don't exist are silently ignored") has been fixed in `standard` 16.

Cheers!
