### ISSUE TITLE
Strong arguments for dangling commas

### ISSUE THREAD

**Issue by lohfu** [standard/standard#907]
Hi,

I chose standard to avoid bikeshedding, and decided to force myself to use it for a few weeks before even considering changing a rule. Most rules are aesthetic anyway and easy to learn to live with. However, there is one rule that after a few weeks still seems very counter productive; namely forcing the omission of dangling commas.

The (strong and, in my opinion, objective) cases for using dangling commas are:

1. Resorting an array will never require adding and/or removing a dangling comma.
2. Adding an item to the end of an array does not require adding a dangling comma to the previous line.
3. Removing the last item in an array does not require removing the dangling comma from the previous line.
4. Commenting out the last item of an array does not require the dangling comma of the previous line to be removed.
5. There are no redundant diffs in version control systems relating to added or removed dangling commas.

Is there any possibility of a rule being reconsidered? I don't really see this as bikeshedding as it actually has strong benefits.

EDIT: Added 4th point & made it make sense

**Comment by ematipico** [comment]
And I thought the argument was about the semicolons... 

I think those arguments are just for comfort

**Comment by Flet** [comment]
Some previous related issues:
https://github.com/feross/standard/issues/787
https://github.com/feross/standard/issues/586
https://github.com/feross/standard/issues/240
https://github.com/feross/standard/issues/159

**Comment by lohfu** [comment]
@Flet 

hmmm, thought i had searched through the closed issues as well. apparently i had not. or did it miserably.

i still stand fast by the point this is a real productivity booster (or hassle reducer, depending on how you want to see it). just like semi-colon omission, it is one of those things you just never want to ditch once you have taken the plunge.

**Comment by feross** [comment]
I appreciate the arguments for dangling commas but I think they are very confusing to beginners. A dangling comma arguably looks like an error -- did the programmer intend to add another item to the list?

One thing I can suggest that alleviates points 3-4 in your list is to run `standard --fix` as a pre-commit hook. This will remove extra dangling commas automatically and save you the extra typing.

**Comment by SirRade** [comment]
@feross I definitely see your point. 

Wouldn't you agree though that, down the line, a beginner would profit more from a rule that enforces a coding style that leads to less complications?   

The [officially linked ESLint](http://eslint.org/docs/rules/comma-dangle) brings up the same points as @lohfu and suggests that the only downside of trailing commas is IE8 compatibility, which at this point is a relic of the past.

Take note that newer languages like Rust even enforced these trailing commas from the beginning, which leads me to belief that switching this rule in the standard is just a natural step forwards.

**Comment by charlike** [comment]
Yea, i'm agree too. Fix is an option, really, i always use fix on save, so i never think for such things, but i have preferences to enable it for "where is allowed in es5", because really, it will ugly to force including commas in the function arguments (i'm agree to require comma there, but only if there are multiline arguments)

**Comment by mmieluch** [comment]
Just my three cents. I myself am a big proponent of enforcing dangling commas in multiline arrays, objects and arguments lists, and all of my co-workers agree with me on this. I find it very convenient not having to go to the previous line just to remove a coma.

Also - and I realise this is purely aesthetic and personal - it gives code this nice symmetry. But that may be just my OCD :)

I agree with @SirRade that this rule would enforce better code. The only browsers that would be incompatible with this would be IE8 and below, as stated on the [ESLint rule page](http://eslint.org/docs/rules/comma-dangle):

> Trailing commas in object literals are valid according to the ECMAScript 5 (and ECMAScript 3!) spec. However, IE8 (when not in IE8 document mode) and below will throw an error when it encounters trailing commas in JavaScript.

Anyway, if there was any vote on this, I'd give a big +1 in a heartbeat. This is mainly the reason we don't use standard `standard`, but override the ruleset with `always-multiline` option for dangling commas.

**Comment by yoshuawuyts** [comment]
As per https://github.com/standard/standard/issues/907#issuecomment-307159881, this topic has been widely discussed already, and there's little chance of this happening now, if ever.

Thanks everyone for chiming in!

**Comment by SirRade** [comment]
@feross Would you mind letting me know why you've deleted my comment?  
It was meant to be constructive, so I would be happy for some feedback.

**Comment by SirRade** [comment]
ping @feross

**Comment by yoshuawuyts** [comment]
@SirRade Any form of discrimination against for race, religion, or otherwise isn't welcome in the StandardJS project. Using a known white supremacist symbol as an avatar (knowingly, or otherwise) will not be tolerated.

Locking this thread, because as per https://github.com/standard/standard/issues/907#issuecomment-322509938 the topic in this thread has been exhausted, and further discussion only adds noise.
