### ISSUE TITLE
object-curly-even-spacing with comments inside curly braces

### ISSUE THREAD

**Issue by anikolaev** [standard/standard#911]
Sometimes I wish to comment out some part of code:
```javascript
import { Map /*, List */ } from 'immutable'
Map()
```
It generates error: " 1:1  error  Expected consistent spacing  standard/object-curly-even-spacing"
https://standardjs.com/demo.html?gist=9ebb58abdda75f49d4bad0016594853d

Is this a bug? If not what is recommended in this case? One-line comments?

**Comment by feross** [comment]
Confirmed, this is a bug.

**Comment by feross** [comment]
This is no longer an issue. I just tested on the latest `standard` 16 and it appears to have been fixed!
