### ISSUE TITLE
Proposal: Case Sensitive Dependencies

### ISSUE THREAD

**Issue by kt3k** [standard/standard#915]
Digging more and more in ESLint rules, i found some good ones which enforces good style and more readable code. This issue is for [dependencies/case-sensitive](https://github.com/zertosh/eslint-plugin-dependencies#dependenciescase-sensitive) rule - **not fixable**.

Suggested configuration.

```json
{
  "dependencies/case-sensitive": "error"
}
```

This rule verifies that `require("…")`, `require.resolve(…)`, `import "…"` and `export … from "…"` ids match the case that is reported by a directory listing.

On mac and windows, `require` works in case-**insensitive** way, but in case-sensitive way on linux. The case mismatches in module ids cause platform-dependent bugs. This rule detects them and enforces platform independent style.

**Comment by Flet** [comment]
This is a neat idea! I recall we had some performance issues with some rules that search the filesystem. I'll see if I can find the reference.

**Comment by ematipico** [comment]
Is this rule applied also on specific files or just on node packages? 
```js
require('lodash')
// vs
require('my/path/to/fileBar.js')
```

**Comment by ematipico** [comment]
If your project has babel, it will warn you about naming problem. If you work on a UNIX machine, this will end up to be a problem during compilation (the OS is case sensitive on filenames). I think rule should be a must have.

**Comment by LinusU** [comment]
> I recall we had some performance issues with some rules that search the filesystem. 

Could be nice with a rule that just enforced that it was all lower case. That way a part of standard would also be to name your javascript files in lower case which I think would be nice.

**Comment by feross** [comment]
https://github.com/zertosh/eslint-plugin-dependencies appears unmaintained, so I'm closing this.
