### ISSUE TITLE
Add NodeJS to the users lists

### ISSUE THREAD

**Issue by feross** [standard/standard#917]
I just noticed that `node/nodejs.org` uses `standard`! 🎉 

https://github.com/nodejs/nodejs.org

**Comment by munierujp** [comment]
It seems that [node/nodejs.org](https://github.com/nodejs/nodejs.org) is still using standard.
Why don't you add it to the users lists?

**Comment by feross** [comment]
Fixed in https://github.com/standard/standard/commit/bd44694ae5b63a758da4fdf5e113d7431dea2ae1
