### ISSUE TITLE
Best way to ignore //= requires in rails?

### ISSUE THREAD

**Issue by tom-sherman** [standard/standard#918]
So with the rails asset pipeline you do things like

```
//= link_directory ../javascripts .js
```

What's the best way to ignore these missing space offences?

**Comment by tom-sherman** [comment]
Ok there was an obvious solution that I somehow missed; enclose the requires in an `eslint-disable` commend like so:
```
/* eslint-disable */
//= require jquery
//= require jquery_ujs
//= require turbolinks
//
// Pull compiled from /public/assets/javascripts
//= require global
/* eslint-disable */
```

**Comment by feross** [comment]
We should consider not treating `=` as an error, like we've done for other extensions: https://github.com/feross/eslint-config-standard/blob/bff0a4bb3447b90fc65a2de57be5d123842f6f69/eslintrc.json#L162-L165
