### ISSUE TITLE
upgrade to eslint@4.

### ISSUE THREAD

**Issue by Aladdin-ADD** [standard/standard#925]

**Comment by sartaj** [comment]
For me standard is currently failing due to an issue in eslint  (https://github.com/eslint/eslint/issues/8401). 

Upgrading to the latest would resolve this issue.

**Comment by bcomnes** [comment]
I noticed this the other day.

**Comment by zemzela** [comment]
Same problem here with eslint 4.5.0

**Comment by AndreMaz** [comment]
Same problem here
eslint v4.7.2
standard 10.0.3
npm 5.4.2

**Comment by bjedrzejewski** [comment]
I raised kind of a duplicate but for another reason: https://github.com/standard/standard/issues/995

**Comment by ReeceLangerock** [comment]
Having the same issue

"eslint": "^4.8.0",
"standard": "^10.0.3",

**Comment by AndreMaz** [comment]
Upgrading to eslint v4.8.0 didn't help. The problem persists

**Comment by undeadcat** [comment]
This is also relevant when using eslint-plugin-html.

eslint-plugin-html v4.0.0 contains some [important fixes](https://github.com/BenoitZugmeyer/eslint-plugin-html/blob/master/CHANGELOG.md), but also 
dropped compatibility with ESLint < 4.7, so not compatible with any current version of standard.

**Comment by Flet** [comment]
The next version of `standard` has been updated to the latest version of `eslint`.

Can you give it a try? `npm install standard@beta`

**Comment by feross** [comment]
🗣 Standard 11 is released! Run `npm install standard@latest --save-dev` to update to the latest version. This will also update the version in `package.json` ✨

Changelog: https://github.com/standard/standard/blob/master/CHANGELOG.md#1100---2018-02-18
