### ISSUE TITLE
Indentation/alignment within ternary branches (consequent/alternate)

### ISSUE THREAD

**Issue by josephfrazier** [standard/standard#927]
(extracted from https://github.com/feross/standard/issues/811#issuecomment-309860797)

Currently (commit 05595b5929d0300e87fe277555ba9b013844592a), standard formats the following code:

```js
let options
const events = typeof options.trigger === 'string'
  ? options.trigger.split(' ').filter(trigger => {
      return ['click', 'hover', 'focus'].indexOf(trigger) !== -1
    })
  : []
console.log(events)
```

as:

```js
let options
const events = typeof options.trigger === 'string'
  ? options.trigger.split(' ').filter(trigger => {
    return ['click', 'hover', 'focus'].indexOf(trigger) !== -1
  })
  : []
console.log(events)
```

That is, it unindents the function body and closing brace. Here's the diff:

```diff
diff --git a/p.js b/s.js
index c778a36e..0ccb242f 100644
--- a/p.js
+++ b/s.js
@@ -1,7 +1,7 @@
 let options
 const events = typeof options.trigger === 'string'
   ? options.trigger.split(' ').filter(trigger => {
-      return ['click', 'hover', 'focus'].indexOf(trigger) !== -1
-    })
+    return ['click', 'hover', 'focus'].indexOf(trigger) !== -1
+  })
   : []
 console.log(events)
```

If ESLint makes it possible (see https://github.com/eslint/eslint/issues/6606 and https://github.com/eslint/eslint/issues/7698), would it be acceptable to have standard use the original indentation in this case?

I might be able to hack together a way to test breakage by postprocessing standard's output with [prettier-miscellaneous](https://github.com/arijs/prettier-miscellaneous), which produces standard-formatted code with `prettier --no-semi --single-quote --jsx-single-quote --space-before-function-paren` (with the exception of this issue, as far as I know).

EDIT: This is similar to https://github.com/feross/standard/issues/521

**Comment by feross** [comment]
I agree that we should auto-format to the former example. Re-opening and setting this as a goal for `standard` v12.

**Comment by brodybits** [comment]
This would definitely resolve an unfortunate consistency with Prettier (<https://github.com/standard/standard/issues/811#issuecomment-455858483>).

Unfortunately both eslint/eslint#6606 and eslint/eslint#7698 reports are now "archived due to age".

I suspect the best solution would be for someone to make an eslint plugin, similar to the following:
- [`divyagnan/eslint-plugin-ternaries`](https://github.com/divyagnan/eslint-plugin-ternaries) ([`eslint-plugin-ternaries`](https://www.npmjs.com/package/eslint-plugin-ternaries))
- [`dugokontov/eslint-plugin-formatting`](https://github.com/dugokontov/eslint-plugin-formatting) ([`eslint-plugin-formatting`](https://www.npmjs.com/package/eslint-plugin-formatting))

**Comment by sheerun** [comment]
This is similar to #1451 that I've recently reported. This indeed makes indentation inconsistent

**Comment by mightyiam** [comment]
More examples in #1451.

**Comment by sheerun** [comment]
I believe the right thing to do right now is to disable this rule and leave ternary expressions untouched. Implementing this rule in eslint can take long time or even never

**Comment by sheerun** [comment]
Never mind, I've prepared pull request for eslint, please upvote:

https://github.com/eslint/eslint/pull/12556

**Comment by sheerun** [comment]
Here's one more example from @Janpot: https://github.com/eslint/eslint/pull/12556#issuecomment-552483310

**Comment by sheerun** [comment]
`offsetTernaryExpressions` indent rule is available in eslint 7.0, it should fix this issue :) https://github.com/eslint/eslint/pull/12556

**Comment by feross** [comment]
@sheerun Thanks for championing this new option for the `indent` rule in ESLint. We'll ship it in standard v15.

```
1..215
# tests 215
# pass  206
# fail  9
```

Affects 4% of the ecosystem. 

These packages need PRs to update to the new style:

- [ ] [testdouble](https://github.com/testdouble/testdouble.js)
- [ ] [pino](https://github.com/pinojs/pino)
- [ ] [leveldown](https://github.com/Level/leveldown)
- [ ] [webtorrent-desktop](https://github.com/webtorrent/webtorrent-desktop)
- [ ] [bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker)
- [ ] [electron-mocha](https://github.com/jprichardson/electron-mocha)
- [ ] [webtorrent](https://github.com/webtorrent/webtorrent)
- [ ] [buffer](https://github.com/feross/buffer)
- [ ] [dependency-check](https://github.com/dependency-check-team/dependency-check)

**Comment by feross** [comment]
It seems like this rule makes some silly decisions. For example:

```js
    var bytesPerSequence = (firstByte > 0xEF) ? 4
      : (firstByte > 0xDF) ? 3
          : (firstByte > 0xBF) ? 2
              : 1
```

It's doing 4 spaces after the first ternary. However, when I also enable `multiline-ternary` (https://github.com/standard/standard/issues/1558) then this works:

```js
    var bytesPerSequence = (firstByte > 0xEF)
      ? 4
      : (firstByte > 0xDF)
          ? 3
          : (firstByte > 0xBF)
              ? 2
              : 1
```

Which makes a lot more sense.

**Comment by feross** [comment]
@sheerun @mightyiam @brodybits @josephfrazier Any interest in helping send PRs to the remaining 5 repos in https://github.com/standard/standard/issues/927#issuecomment-713982481 ?

**Comment by feross** [comment]
From https://github.com/standard/standard/issues/1564#issuecomment-718567370 there is one downside of this rule. Standard doesn't like this code:

```js
export const y = new Date().getTime() % 2
  ? (
    <span>
      ghi
    </span>
  )
  : 'jkl'
```

Instead it wants:

```js
export const y = new Date().getTime() % 2
  ? (
    <span>
      ghi
    </span>
    )
  : 'jkl'
```

I think that ideally, we'd make an exception to this rule when an expression wrapped in parens or an array or object appears as the value in the ternary. In this case, we don't want the closing paren/bracket/brace to also be indented.

**Comment by brodybits** [comment]
@feross @sheerun you can blame me for dropping the ball on prettierx. But it looks to me like Prettier may go in a different direction: https://github.com/prettier/prettier/issues/9561

I do happen to like the Standard 15 way better, would recommend some input on https://github.com/prettier/prettier/issues/9561 before it is too late.

**Comment by sheerun** [comment]
@brodybits Thanks for letting us know, I've commented there what I find clean

**Comment by sheerun** [comment]
@feross This probably should read:

```es6
export const y = new Date().getTime() % 2
  ? (
      <span>
        ghi
      </span>
    )
  : 'jkl'
```

but parens are not really necessary:

```es6
export const y = new Date().getTime() % 2
  ? <span>
      ghi
    </span>
  : 'jkl'
```
