### ISSUE TITLE
Parsing error: Unexpected token =  null

### ISSUE THREAD

**Issue by webchaz** [standard/standard#931]
I'm using standard with standard-loader and babel-eslint parser in webpack.

```
      {
        enforce: 'pre',
        test: /\.jsx?$/,
        loader: 'standard-loader',
        exclude: /(node_modules|bower_components)/,
        options: {
          error: false,
          snazzy: true,
          parser: 'babel-eslint'
        }
      }
```

In my `.eslintrc` I have 
```
{
  "parser": "babel-eslint",
  "parserOptions": {
    "sourceType": "module",
    "allowImportExportEverywhere": false,
    "codeFrame": false
  },
  "plugins": ["react"]
}
```

However, I'm receiving this unexpected token for the `static` in the following block:

```
export default class SelectDropdown extends React.Component {
  static propTypes = {
    selected: PropTypes.object.isRequired,
    onChange: PropTypes.func.isRequired,
    data: PropTypes.arrayOf(PropTypes.shape({
      key: PropTypes.string.isRequired,
      label: PropTypes.string.isRequired
    }).isRequired).isRequired
  }
```

Any idea if there's a config missing or how I can get standard to work with stage-0

**Comment by feross** [comment]
I'm not sure how you would configure `standard-loader` to support stage-0. You should probably open an issue on that repo or ask @timoxley.

However, I see that you're using an `.eslintrc` file. `standard` doesn't look at those. If you want to pass options to the `babel-eslint` parser, try a `.babelrc` file?
