### ISSUE TITLE
Fat arrow method definitions

### ISSUE THREAD

**Issue by dadamssg** [standard/standard#935]
Is disallowing defining methods via fat arrows a rule or a bug? This is valid syntax with babel and I'm using babel-eslint but the rule is `no-undef` which I believe is wrong. 

![image](https://user-images.githubusercontent.com/881986/27545390-556f9418-5a55-11e7-9c36-15ad07034a2d.png)

This is really helpful because it auto-binds `this` to the component instance. If you were to use the non fat arrow syntax, you would need to manually bind `this` to that method. 

This is enabled by the [transform-class-properties](https://babeljs.io/docs/plugins/transform-class-properties/) babel plugin which i have enabled in my .babelrc

```js
{
  "presets": [
    "stage-0",
  	["es2015", {"modules": false}],
  	"react"
  ],
  "plugins": [
    "transform-class-properties"
  ]
}
```

**Comment by eddiemonge** [comment]
That plugin also enables
```
static PropTypes = {
  ...
}
```
which Standard is complaining about

**Comment by Talor-A** [comment]
another example that I believe is related, standard doesn't like it when writing your react state this way: 
```
class MyComponent extends Component {
  state = {}
  ...
```

**Comment by bcomnes** [comment]
Is it a matter of setting up https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features  ?

**Comment by c2crm** [comment]
I think it has something to do with babel-eslint but i have this in my package.json and it still isn't working.

![image](https://user-images.githubusercontent.com/9008484/27659161-1b49cea6-5c18-11e7-9bbf-16cc47f8ffbb.png)

**Comment by dadamssg** [comment]
I think it has something to do with babel-eslint but i have this in my package.json and it still isn't working.

![image](https://user-images.githubusercontent.com/881986/27659206-4011be60-5c18-11e7-9855-cabdf12de2d8.png)

**Comment by eddiemonge** [comment]
If I use `babel-eslint` then that complains about double quotes in JSX.

**Comment by dadamssg** [comment]
That's just a normal rule. Second bullet point here: https://standardjs.com/#the-rules

**Comment by eddiemonge** [comment]
Except its not. If I don't use `babel-eslint` as the parser, then Standard does not complain about it.

**Comment by dadamssg** [comment]
It might not have been linting your jsx at all if you weren't using the babel-eslint parser

`¯\_(ツ)_/¯`

**Comment by bcomnes** [comment]
I think if you are not using `babel-eslint` with JSX, the standard linter won't parse the JSX blocks, thus missing any lint errors that may be in those sections of code.  Not 100% on that.

**Comment by dadamssg** [comment]
https://github.com/standard/eslint-config-standard-jsx/blob/master/eslintrc.json#L16

**Comment by bcomnes** [comment]
The other issue is that class properties assigned to arrow functions is still in babel land iirc: http://babeljs.io/docs/plugins/transform-class-properties/

If you are using babel transforms to access future JS features, you are definately going to want to turn on the babel parser.

**Comment by bcomnes** [comment]
Yeah class properties are still in the ES Next zone: http://kangax.github.io/compat-table/esnext/#test-class_fields_class_properties

If you are using these features, you must have the `babel-eslint` parser enabled.

**Comment by feross** [comment]
If `babel-eslint` is set up correctly then using experimental syntax should work. Can you share the output of:

```bash
$ standard --version
$ npm ls standard
$ npm ls babel-eslint
```

**Comment by dadamssg** [comment]
```
standard --version  = 10.0.2
npm ls standard     = standard@10.0.2
npm ls babel-eslint = babel-eslint@7.2.3
```

**Comment by dadamssg** [comment]
i think i figured it out. I was attempting to convert my project from using my own set of eslint rules to standard. Incidentally, I had `"eslint": "^4.0.0",` in my package.json file. 

After noticing the unmet peer dependency that standard has on `eslint@3.19.0`, i installed that and now the only error/warning i'm getting is: 

```
The react/jsx-space-before-closing rule is deprecated. Please use the react/jsx-tag-spacing rule with the "beforeSelf
Closing" option instead.
```

**Comment by joke2k** [comment]
Hi @dadamssg, your solution doesn't work for me.
My project was started with create-react-app script then I `yarn add standard` and in my package.json:
```
"standard": {
    "parser": "babel-eslint"
  },
```

class Please extends Component {
  work = () => { console.log('cmon') }
}


npm ls standard
└── standard@10.0.3

npm ls babel-eslint
├── babel-eslint@8.0.2 
└─┬ react-scripts@1.0.16
  └── babel-eslint@7.2.3

npm ls eslint
├─┬ react-scripts@1.0.16
│ └── eslint@4.10.0 
└─┬ standard@10.0.3
  └── eslint@3.19.0

**Comment by dadamssg** [comment]
@joke2k I can only guess that it's because you have eslint 4.10.0 installed alongside eslint 3.19.0 because of the requirement from react-scripts. I bet if you removed react-scripts, and thus eslint 4.10.0, and only had 3.19.0 it would work.

**Comment by joke2k** [comment]
Yeah! @dadamssg you were right!
But uninstalling react-script... I cannot execute start/build/test XD
This is a mess

**Comment by dadamssg** [comment]
@joke2k haha sorry to hear that! Unfortunately, I don't have any experience with create-react-app/react-scripts so I can't help you there :/

**Comment by joke2k** [comment]
It seems that we have to wait standard 11

**Comment by IlyasAbdighni** [comment]
Did someone find any solution?

**Comment by GBarkhatov** [comment]
Any solutions?

**Comment by ematipico** [comment]
Have you tried with `standard@beta`?

**Comment by GBarkhatov** [comment]
Yep, not working

**Comment by Tommos0** [comment]
I'm having the same issue. Using `parser: babel-eslint` doesn't help.

**Comment by Flet** [comment]
@Tommos0 does `npm install standard@beta` work better? It uses eslint 4 instead which should help avoid some conflicts.

**Comment by Dean177** [comment]
@Flet using the beta version of standard resolved the issues I was having with ‘babel -eslint’

**Comment by KITSMattStyles** [comment]
Upgrading to beta helped me also. Despite `npm ls eslint` showing only version 3.x under standard, something else must have installed version 4.x. Updating standard to use the same version fixed it. Pretty sure this isn't actually an issue with standard.

**Comment by franky47** [comment]
I also have this issue with the following setup:
```
$ npm -ls -g --depth=0
├── babel-eslint@8.2.1
├── eslint@4.15.0
├── standard@11.0.0-beta.0
...
```

Example code :
```js
// test.js
export default class Foo {
  // Static class fields - https://github.com/tc39/proposal-static-class-features/
  static propTypes = {}

  // Class fields - https://github.com/tc39/proposal-class-fields
  state = {
    foo: 'foo'
  }

  // Fat arrow method
  foo = () => this.state.foo
}
```
Result:
```shell
$ standard test.js
test.js:3:20: Parsing error: Unexpected token =

$ standard --parser babel-eslint test.js
test.js:3:10: 'propTypes' is not defined.
test.js:6:3: 'state' is not defined.
test.js:11:3: 'foo' is not defined.
```

**Comment by ip413** [comment]
Doesn't work with beta version 11.0.0-beta.0

Still have `Parsing error: Unexpected token =` for `xx = () => {...`

**Comment by bcomnes** [comment]
@ip413 @franky47 https://standardjs.com/index.html#how-do-i-use-experimental-javascript-es-next-features

**Comment by franky47** [comment]
@bcomnes yep, tried that initially, no luck with either local or global `standard`, `babel-eslint` and `eslint`.

**Comment by bcomnes** [comment]
iirc you also need to ensure the correct babel transforms, I forget if env ships class fields or not.

**Comment by azizhk** [comment]
babel-eslint's version is what is causing the issue, downgraded babel-eslint to ^7.0.0 and the error stopped appearing.

**Comment by jnreynoso** [comment]
Any solutions?

**Comment by azizhk** [comment]
@jnreynoso Are you using prettier-standard?
You will have to downgrade that as well.
Otherwise only downgrading babel-eslint will solve this problem.

**Comment by fedorinoGore** [comment]
Any solutions? None of the listed works for me...
"babel-eslint": "^7.2.3"

**Comment by jnreynoso** [comment]
@azizhk prettier-standard solved this problem?

**Comment by azizhk** [comment]
@fedorinoGore my setup is:
"babel-eslint": "^7.0.0"
"standard": "^10.0.3"
"eslint": "^3.19.0"

@jnreynoso
I removed prettier-standard for now. You can use prettier-eslint with standard config, that might give you better control. https://github.com/sheerun/prettier-standard/issues/30#issuecomment-363418634

**Comment by fedorinoGore** [comment]
@jnreynoso @azizhk I'm not using Prettier for now... But the problem persist.

**Comment by azizhk** [comment]
Run these three commands and write the results here.
yarn list babel-eslint
yarn list standard
yarn list eslint
or if you are using npm
npm ls babel-eslint
npm ls standard
npm ls eslint

**Comment by fedorinoGore** [comment]
`npm ls babel-eslint`
└── babel-eslint@7.2.3
`npm ls standard`
└── standard@11.0.0-beta.0
`npm ls eslint`
├── eslint@4.17.0
└─┬ standard@11.0.0-beta.0
  └── eslint@4.13.1

**Comment by azizhk** [comment]
Ok so based on these issues:
https://github.com/babel/babel-eslint/issues/566
https://github.com/babel/babel-eslint/issues/564
https://github.com/babel/babel-eslint/issues/589
I thought this was an issue with babel-eslint and downgrading it

But it might also be of having mixed dependency versions of babel (https://github.com/babel/babel-eslint/issues/585)
standard@11 depends on babel@7 which must be causing multiple babel versions.
Can you downgrade standard to 10 or all babel dependencies to 7?

**Comment by fedorinoGore** [comment]
I really do afraid to upgrade babel and all of its dependencies :)
so for the starter tried to downgrade standard. 
And things getting worse. Not standard claims that arrow function class member  is undefined
<img width="1120" alt="2018-02-12 18 17 30" src="https://user-images.githubusercontent.com/12615892/36103683-1b70ac52-1021-11e8-9de4-accfc5a71861.png">
<img width="698" alt="2018-02-12 18 17 19" src="https://user-images.githubusercontent.com/12615892/36103684-1ba079a0-1021-11e8-9b65-59ac922f1a7c.png">

**Comment by Rachomir** [comment]
I am having same problems with fat arrow functions. :(

**Comment by will-hart** [comment]
I found a combination that works for me with a `create-react-app` project. In my `package.json` (Windows 10) I have:

```
  "scripts": { 
    "lint": "./node_modules/.bin/standard --parser=babel-eslint | ./node_modules/.bin/snazzy"
  },
  "standard": {
    "parser": "babel-eslint"
  },
  "devDependencies": {
    "babel-eslint": "8.2.1",
    "eslint": "4.17.0",
    "snazzy": "^7.0.0",
    "standard": "^11.0.0-beta.0"
  }
```

At this stage `yarn lint` was passing, but class arrow functions and static properties were flagged as errors in VS Code by the `chenxsan.vscode-standardjs` plugin. I had to add the following line to my `.vscode/settings.json` file for the workspace:

```
  "standard.usePackageJson": true
```

Hopefully that helps somebody else!

**Comment by tlvince** [comment]
This is fixed for me in v11.0.0 (and using `babel-eslint`). Thanks!

**Comment by Kikobeats** [comment]
Me too!

**Comment by feross** [comment]
Sorry for all the trouble with this issue. If you install the latest version of `standard` (version 11.0.0) then this issue is resolved.

If you're not sure what version of standard you're using, run:

```bash
npx standard --version
```

Ensure that you're on at least 11.0.0 and you'll be good to go!

**Comment by jligeza** [comment]
I have version 11 and it still doesn't work.

**Comment by feross** [comment]
@jligeza Without any additional information, it's impossible to help you. Open a new issue and share a full bug report.

**Comment by jligeza** [comment]
Sorry, it works now. I just didn't use `babel-eslint` as written in the documentation.
