### ISSUE TITLE
Class static properties

### ISSUE THREAD

**Issue by eddiemonge** [standard/standard#940]
This seems like it used to be supported but isn't anymore. The part that this breaking is the class property. Is this expected to be not working since the proposal for it changed a bit?

`Parsing error: Unexpected token =`

```
export default class Banner extends Component {
  static propTypes = {
    title: PropTypes.string
  }

  render () {
    <h1>{this.props.title}</h1>
  }
}
```

**Comment by rxgx** [comment]
That feature hasn't been added to the spec yet and, for our app, requires two modules: `babel-eslint` to parse the syntax and `babel-plugin-transform-class-properties` to preview the feature.

**Comment by fedorinoGore** [comment]
Nope. Using both `babel-eslint` and `babel-plugin-transform-class-properties` doesn't worked for me...

**Comment by feross** [comment]
This issue was fixed in `standard` v11 which was released several months ago. Closing!
