### ISSUE TITLE
If I use Standards do I need to use ESlint in the project? 

### ISSUE THREAD

**Issue by jitendravyas** [standard/standard#943]
Can Standard do everything which Eslint can do?

**Comment by yoshuawuyts** [comment]
Standard is an opinionated configuration of Eslint, so if you use Standard
you don't need to use another copy of Eslint

**Comment by bcomnes** [comment]
Standard is a standalone program that uses eslint under the hood.   You just install it as a dev dependency and start using it however you like (in CI steps, as an editor linter etc).

You can use ESLint with the standard ruleset by using https://github.com/standard/eslint-config-standard but that requires more per-project configuration.
