### ISSUE TITLE
Class static properties semi

### ISSUE THREAD

**Issue by egorovli** [standard/standard#944]
Static class properties with trailing semi are not reported as `Extra semicolon`, example:

```javascript
class MyComponent extends PureComponent {
  static propTypes = {
    isVisible: PropTypes.bool.isRequired
  }; // <-- right here

  render () {
    return (
      <div />
    )
  }
}
```

**Comment by eddiemonge** [comment]
But you don't get a complaint about `static propTypes`?

**Comment by egorovli** [comment]
@eddiemonge no, I've seen your issue; my config of standard in package.json:

```json
"standard": {
  "parser": "babel-eslint"
}
```

And also I have a .babelrc file in the project root directory:

```json
{
  "presets": [
    "env",
    "react",
    "stage-2"
  ],
  "plugins": [
    "transform-decorators-legacy"
  ]
}
```

Also, standard is `^10.0.2`. Hope that helps.

**Comment by RobertPaul01** [comment]
I have this same issue with the added `"parser": "babel-eslint"` setting

**Comment by feross** [comment]
Confirmed this is an issue. Unclear what the cause is. If anyone has additional info, please share it!

**Comment by eddiemonge** [comment]
Maybe this should get a label so it isnt auto closed or something

**Comment by eddiemonge** [comment]
@feross can this be reopened? It is still an issue that I just ran across in a new project

**Comment by eddiemonge** [comment]
Nevermind. After tons of research, it appears semicolons are required. The `static` keyword however is not. https://github.com/tc39/proposal-class-fields
