### ISSUE TITLE
'standard' on TypeScript generating incorrectly claiming symbols never used

### ISSUE THREAD

**Issue by BurtHarris** [standard/standard#948]
I've tried setting up `standard` to process TypeScript files using `typescript-eslint-parser` and `eslint-plugin-typescript` as documented in the README.   It's given me some nonsensical errors claiming some of my imports are never being used, when it's plain they are.  For example, `standard src/documenter.ts` gives me these these messages:

```
standard: Use JavaScript Standard Style (https://standardjs.com)
  C:\code\tsdoc\src\documenter.ts:2:13: 'ts' is defined but never used.
  C:\code\tsdoc\src\documenter.ts:3:27: 'interfaces' is defined but never used.
  C:\code\tsdoc\src\documenter.ts:4:10: 'DocumenterOptions' is defined but never used.
  C:\code\tsdoc\src\documenter.ts:4:29: 'RunOptions' is defined but never used.
``` 

When in fact all four of these symbols are in use.   See [source code here](https://github.com/BurtHarris/tsdoc/blob/9a02897fd66942ba51ac03d2f471c2a399f8af5d/src/documenter.ts)

standard version: 10.0.2
tsc version: 2.3.4

**Comment by samvv** [comment]
With the new code on `master`, not all of them are in use, but e.g. `RunOptions` still is, and has always been.

**Comment by BurtHarris** [comment]
@samvv I just used this as an example.   The link I provided was to a particular commit, so updates to master on our example project won't get reflected in this use

**Comment by samvv** [comment]
Oh whoops, I see now, missed that.

**Comment by mightyiam** [comment]
This can be closed. Known typescript-eslint-parser issue:
https://github.com/eslint/typescript-eslint-parser/issues/77
