### ISSUE TITLE
no-redeclare in a for loop scope seems wrong

### ISSUE THREAD

**Issue by Jakobud** [standard/standard#955]
It's pretty typical ES5 syntax to do this:

```
for (var index = 0; index < arrayOne.length; index++ ) {
  // code
}

for (var index = 0; index < arrayTwo.length; index++ ) {
  // code
}
```

The `no-redeclare` has an issue with this because `index` is being defined twice. This isn't a problem when using `let` but a lot of people still use ES5 on the frontend and Babel and Webpack are transpilling ot ES5 for frontend client side code as well.

Are there any thoughts on this? Obviously the solution is to declare `index` by itself at the top of the code, but I'm just looking to keep my code simple.

**Comment by yoshuawuyts** [comment]
Like you said, the solution is to declare index at the top of the file. I
also regularly run into this, but I don't mind it too much haha

**Comment by bcomnes** [comment]
Standard should lint the pre-compile side of babel.  Machine generated code shouldn't require listing.

With hoisting the above code actually turns into:

```js
var index
for (index = 0; index < arrayOne.length; index++ ) {
  // code
}

for (index = 0; index < arrayTwo.length; index++ ) {
  // code
}
```

The rule is to remind you of this, and to make sure you don't run into the pitfalls surrounding it.

![fullsizerender 2](https://user-images.githubusercontent.com/166301/28338838-fec478f6-6bbe-11e7-9c2a-0ce87ba4fc04.jpg)
![fullsizerender](https://user-images.githubusercontent.com/166301/28338837-feb7faea-6bbe-11e7-9371-4dcebea0935d.jpg)

Closing for now.  Please let me know if there are undressed issues here and we can reopen.

**Comment by Jakobud** [comment]
That makes sense. Thanks
