### ISSUE TITLE
Conflict between `no-new` and `no-unused-vars` rules

### ISSUE THREAD

**Issue by synthecypher** [standard/standard#958]
If I want to instantiate a class as part of an initialization process but I do nothing with the instance after the fact I run into the two dilemmas.

```javascript
// no-unused-vars
const gameEngineInstance = new GameEngine()
```

If I remove the unused variable I get the following

```javascript
// no-new
new GameEngine()
```

If I do the following it won't instantiate the class.

```javascript
GameEngine()
```

So what should I do in this example to comply with standard?

**Comment by yoshuawuyts** [comment]
Change your API so new isn't used for side effects, or disable the rule for
that specific line. Warnings exist to tell you something is a bad idea.
Disabling rules is possible so you can disagree.

**Comment by LinusU** [comment]
I agree with what @yoshuawuyts said, it's very bad practice to have side effects happen in a constructor. I would recommend refactoring so that it isn't necessary.

If you do want to continue doing so, you can disable linting for that line, like so:

```js
// eslint-disable-next-line
new GameEngine()
```

**Comment by synthecypher** [comment]
@LinusU can you link me to some information or an example of how I might write such an API?

**Comment by bcomnes** [comment]
Move the side-effects into a function or method call of an instance.

**Comment by LinusU** [comment]
In this specific case, I can imagine that the GameEngine sets up some kind of loop that runs every frame or similar. Instead of doing that in the constructor move that to a `.start()` function.

e.g.

old:

```js
class GameEngine {
  constructor () {
    // ...

    setInterval(() => this.renderFrame(), 1000 / 30)
  }

  // ...
}

// ...

new GameEngine()
```

new:

```js
class GameEngine {
  constructor () {
    // ...
  }

  start () {
    setInterval(() => this.renderFrame(), 1000 / 30)
  }

  // ...
}

// ...

const engine = new GameEngine()

engine.start()
```

**Comment by synthecypher** [comment]
I'm The constructor it initialises variables with sensible defaults does
that count as a side effect?

**Comment by LinusU** [comment]
> The constructor it initialises variables with sensible defaults does that count as a side effect?

No, that is how it should be 👍 

Side effects are something that affects anything _outside_ of the class itself. So it's perfectly fine to modify anything that beings with `this.`, but you shouldn't modify anything outside of the class.

`setTimeout`, `setInterval`, `process.nextTick`, `.addEventListener`, `.requestAnimationFrame`, etc. all implicitly modifies global state and we should always think really carefully before using them in a constructor.
