### ISSUE TITLE
Closing-brace indentation is not checked for object literals

### ISSUE THREAD

**Issue by js-choi** [standard/standard#959]
All this was tested using version 10.0.2 and can be demonstrated on the [demo web page](https://standardjs.com/demo.html).

This code with an if block is Standard Style:

    const x = true

    if (x) {
      console.log(x)
    }

This code is not Standard Style; it violates `brace-style`:

    const x = true

    if (x) {
      console.log(x) }

This code with an object literal is Standard Style:

    const x = {
      a: 3
    }

    console.log(x)

This presumably isn’t Standard Style; it probably ought to violate `brace-style`:

    const x = {
      a: 3 }

    console.log(x)

But Standard considers the final code block to also be valid Standard Style.

**Comment by feross** [comment]
Looks like this rule was improved at some point in ESLint and it's no longer an issue in the latest `standard`, v15.
