### ISSUE TITLE
How to check code inside php files?

### ISSUE THREAD

**Issue by wowcut** [standard/standard#965]
I found the hint about `eslint-plugin-html` in the readme, however I would like to check code inside some php files and did not find anything similar - using `eslint-plugin-html` does not work for php files, it unfortunately produces parsing errors.

Yes, I know JS in PHP files is a very bad practice - this is a legacy code base and that is why I would love to fix all the JS inside all files with `standard --fix *.php`.

**Comment by bcomnes** [comment]
Not sure, but I would broaden the search to see if anyone has gotten eslint looking inside PHP files.

**Comment by wowcut** [comment]
Yes, I see there are overlapping responsibilities with this use case and it is not totally clear where it should be handled - why should a JS linter take care of PHP tags? Also PHP tags in JS are simply syntax errors, so eslint does the right thing to report them as syntax errors.

But _fixing_ things is sometimes done in situations where people did not care about standards or even correct syntax (unfortunately), so I feel like a solution for this kind of problem might have a place here, but I am not sure - I am just asking, not arguing. 

I just found [eslint-plugin-exclude-php-tags](https://www.npmjs.com/package/eslint-plugin-exclude-php-tags) and will try to use this with `standard` - I will report back if it helps me in my specific case which involves fixing that bad practice of 'PHP tags inside JS inside PHP files with HTML and JS' - a horrible scenario, believe me! But ignoring PHP tags is not what I really want - I would like to have it _fixed_. 

Otherwise I will try some `sed` to fix that mess, but it would be really nice to have `stabdard` handle it .

**Comment by bcomnes** [comment]
Unfortunately you might have to put a custom eslint stack together, using the shareable configs directly.  But yeah, if you find a way to do it we could add it to the FAQ.

**Comment by Flet** [comment]
I think @bcomnes is right; This will need to be done with eslint directly (with `eslint-config-standard`) since its such a particular use case.

I'm closing this issue for now. If you have questions on or need further advice please feel free to reply to the thread!
