### ISSUE TITLE
localStorage is undefined && doesn't ignore node_modules

### ISSUE THREAD

**Issue by CodeDraken** [standard/standard#976]
```js
localStorage.setItem('token', res.data.token)
```
This is giving me an error "'localStorage' is not defined. (no-undef)"

It's also checking files inside node_modules for some reason.

**Comment by dcousens** [comment]
`window.localStorage`

**Comment by bcomnes** [comment]
Correct answer! Also https://npmjs.com/global if you want to get modular about it.

**Comment by LinusU** [comment]
You could also add this comment to the top of the file, which would also work in web workers.

```js
/* eslint-global localStorage */
```

see #619 for more details :)
