### ISSUE TITLE
enhancement: standard/object-curly-even-spacing reporting range be more correct.

### ISSUE THREAD

**Issue by Aladdin-ADD** [standard/standard#977]
![image](https://user-images.githubusercontent.com/13050025/29808019-0fe25150-8cc9-11e7-96e5-8240811efce5.png)

it should start at `{`, instead of start of the line.

**Comment by charlike** [comment]
This title is pretty confusing. Second, probably more better would be to report it at [xjamundx/eslint-plugin-standard](https://github.com/xjamundx/eslint-plugin-standard/)

**Comment by timoxley** [comment]
This appears to be an issue with eslint rather than standard.
