### ISSUE TITLE
[Idea] Could we add support for js decorator ?

### ISSUE THREAD

**Issue by Jack-Kingdom** [standard/standard#979]
JS decorator cannot be recognized on current version(10.0.3). Error will be thrown like this \:
```
Unexpected character '@'
```
But, decorator is being used more and more often in actually. Maybe we should add this support.

**Comment by ematipico** [comment]
As far as I know, the plan of `standard` is to support only the proposal that reached stage-4

**Comment by kt3k** [comment]
See [here](https://github.com/standard/standard#how-do-i-use-experimental-javascript-es-next-features) for using experimental javascript features.

---
refs #829

**Comment by timoxley** [comment]
@Jack-Kingdom the above response should resolve your issue.
