### ISSUE TITLE
[Bug] Babel Static triggers parsing error

### ISSUE THREAD

**Issue by HACKHERS** [standard/standard#980]
Hello,

I tried to fix the problem but I think they are not supported. I can't find any way around that. Babel plugin that I use: [babel-plugin-transform-class-properties](https://babeljs.io/docs/plugins/transform-class-properties/)

Code:
```
class Translative {

    static instance;
```

Error:  standard: Use JavaScript Standard Style (https://standardjs.com)
  Translative.js:8:20: Parsing error: Unexpected token ;

Any ideas?

**Comment by Flet** [comment]
Ah, it looks like you'll need to use `babel-eslint` to parse this code.

https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features
