### ISSUE TITLE
Event is not defined with flow type, any way to fix this without ejecting from standard?

### ISSUE THREAD

**Issue by kellyrmilligan** [standard/standard#984]
I'd prefer not to eject, but the current setup with flow seems to be incomplete. 

these two rules should be enabled to fully support the flow definitions:

https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-define-flow-type
and 
https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-use-flow-type

I was lead to these by:

https://github.com/babel/babel-eslint#known-issues

in my setup, I am using latest babel-eslint as the parser, and built in flow stuff works. but if I try and do

```
function handleEvent(evt: Event) {
```

then I seem to be out of luck. 

thoughts?

```
"standard": {
    "parser": "babel-eslint",
    "globals": [
      "jest",
      "it",
      "expect",
      "describe"
    ],
    "ignore": [
      "/src/**/*.test.js"
    ],
    "plugins": [
      "flowtype",
      "react"
    ]
  }
```

**Comment by cgestes** [comment]
Same issue here.

A lot of undefined because of those rules.

Any PR in the pipe?

**Comment by seanng** [comment]
I'm facing the same problem :(

**Comment by ematipico** [comment]
What are the versions of your packages? eslint, flowtype plugin, standard, etc.?

**Comment by fbaiodias** [comment]
I was having a similar issue, getting a lot of `'<Type>' is not defined.`, but using `babel-eslint@7.2.1` fixed it for me.

**Comment by mcchrish** [comment]
@fbaiodias your solution works. Thanks

**Comment by doughsay** [comment]
Downgrading to `babel-eslint@7.2.1` fixed some types not being defined but not others. (It fixed my custom types from not being recognized later in the file).  But it didn't fix `Event` and `HTMLInputElement` from being undefined.  Upgrading to the latest version again fixes `Event`, but breaks the others...

What's going on here...?

**Comment by CoenWarmer** [comment]
Downgrading to `babel-eslint@7.2.1` indeed fixed this for us. Would be ideal however if we could upgrade to `8.0.2` (currently the latest and greatest).

Just for my understanding, is this flow type undef behavior due to an an issue with `babel-eslint` or with `standard`?

**Comment by de5pair** [comment]
Also work for us with babel-eslint@7.2.1, tried to upgrade to babel-eslint@7.2.3 and it breaks again.

**Comment by pietrofxq** [comment]
Is there a better workaround than downgrading `babel-eslint`?

**Comment by feross** [comment]
I'm happy to do some digging on this issue. But I'm not a Flow user.

Can you share a repo with a minimal setup that exhibits the issue so I can see it in action? Thanks!

**Comment by feross** [comment]
Related to: https://github.com/standard/standard/issues/1045
