### ISSUE TITLE
Failed to load plugin react: Cannot find module 'eslint-plugin-react'

### ISSUE THREAD

**Issue by stephen-last** [standard/standard#986]
I'm running Atom 1.20.0 and have Standard installed in a local project.

Every time I open a `.js` file I get:

> Something bad happened
> Failed to load plugin react: Cannot find module 'eslint-plugin-react'
> Referenced from: C:\node\sandbox\aws\node_modules\standard\eslintrc.json

The contents of `C:\node\sandbox\aws\node_modules\standard\eslintrc.json`:

```json
{
  "extends": ["standard", "standard-jsx"]
}
```

This project doesn't use React at all, however the page type in the bottom right-hand corner of Atom says `JavaScript (JSX)`.

This hasn't been a problem before, and I certainly don't want to have to change all my React projects to `.jsx` rather than `.js` to avoid this error.

How do I make this error go away..?

**Comment by Flet** [comment]
I suggest re-installing a fresh copy `standard`. It looks like there may have been an issue pulling down some dependencies.

Hope this helps! I'm going to close this issue, but feel free to comment if you're still seeing problems,
