### ISSUE TITLE
Disallow the use of `only` in mocha tests

### ISSUE THREAD

**Issue by owennicol** [standard/standard#988]
Could we add in a rule for not allowing `only` in mocha tests please?

This is an ESLint plugin for the same thing if that helps: https://www.npmjs.com/package/eslint-plugin-mocha-no-only

**Comment by LinusU** [comment]
Would personally love this, too easy to accidentally commit this 😄

**Comment by Flet** [comment]
This is neat! However, I'd be a little worried that this could open the door to adding lots of framework/library specific rules, which could get hairy.

**Comment by LinusU** [comment]
Yeah, that is very true, might be a good idea to think about where to draw the line, and this could potentially be on the wrong side of that line :)

Although mocha is **very** widely used...

**Comment by ematipico** [comment]
`.only` is also support by Jest and AVA

**Comment by dcousens** [comment]
Useful,  but I don't know if this should be `standard`'s responsibility...

**Comment by blgm** [comment]
The best way that I've found to avoid committing `.only`s is to use code coverage measurement and enforcement.  Then if you accidentally try and commit a `.only` the CI will fail.

Jasmine uses `xit` instead of `.only` and it would be odd to add checks for Mocha but not Jasmine.

**Comment by feross** [comment]
I don't think this belongs in `standard` at this time. I have an idea that might accommodate additional rules for particular frameworks and I'd like to re-examine this rule if/when that becomes a thing.

**Comment by Janpot** [comment]
If I recall correctly, mocha has a `--forbid-only` flag. I think this is the right place for this functionality, not in `standard`.
