### ISSUE TITLE
Zero newlines allowed at end of file

### ISSUE THREAD

**Issue by Gryff** [standard/standard#990]
From the [standard rules](https://standardjs.com/rules.html) I see that files must end with a newline. However when running standard it tells me files that adhere to this rule are wrong.

myFile.js -
```
function hello () {
  console.log('hello')
}

module.exports = hello

```

```
$ standard --version
10.0.3
$ standard myFile.js
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /path/to/myFile.js:6:1: Too many blank lines at the end of file. Max of 0 allowed.
```

Searching the issues here I see [this comment](https://github.com/standard/standard/issues/733#issuecomment-271819691) about enforcing no more than 1 newline at the end of a file.

[Eslint's rules](https://eslint.org/docs/rules/no-multiple-empty-lines) imply that this is wrong and we should use `maxEOF: 1`.

Maybe eslint fixed the wonkiness mentioned in the issue comment above?

**Comment by LinusU** [comment]
It seems like your file ends with two newlines? (one blank line)

The rule comes from the fact that a unix text file is defined as multiple strings all terminated by `\n` (a newline). It seems like your file ends with two newlines (`\n\n`) which is the same as one blank line.

Basically, there should be exactly one newline character at the end of the file, which will result in no blank lines at the end of the file.

Hope that this made sense 😄

**Comment by Gryff** [comment]
Thanks @LinusU, that does make sense. I misunderstood. 
newline !== blank line
