### ISSUE TITLE
standard --fix    `key:.3` => `key:0 .3`

### ISSUE THREAD

**Issue by fritx** [standard/standard#994]
```js
    var matWindshield = new THREE.MeshPhongMaterial({color:Colors.white,transparent:true, opacity:.3, shading:THREE.FlatShading});;
// =>
    var matWindshield = new THREE.MeshPhongMaterial({color: Colors.white, transparent: true, opacity:0 .3, shading: THREE.FlatShading});
```

Also, the `;;` => `;`, instead of clearing them all.

**Comment by Flet** [comment]
Hello!

It looks like this bug is fixed in the next version of `standard`.

`npm  install standard@beta` to give it a try.

**Comment by feross** [comment]
🗣 Standard 11 is released! Run `npm install standard@latest --save-dev` to update to the latest version. This will also update the version in `package.json` ✨

Changelog: https://github.com/standard/standard/blob/master/CHANGELOG.md#1100---2018-02-18
